### ISSUE TITLE
🏷 Show "..." tag, if tags don't fit into row instead of ellipsizing all

### ISSUE THREAD

**Issue by q-wertz** [stefan-niedermann/nextcloud-deck#494] opened 2020-05-14 08:17 UTC
**Describe the bug**
The calculated width of the tags seems wrong (width raises from left to right) if many tags are next to each other (see screenshot)

**To Reproduce**
1. Create new Task
2. Add some tags
3. See error

**Expected behavior**
The Tags should all have the same size. Maybe also split them over two lines when there are too many (e.g. less than first 4 letters can be shown) or only show the first ones and make a hint "..." that there are more and by pressing it the "..." all are shown

**Screenshots**
![Screenshot_20200514-092334](https://user-images.githubusercontent.com/20948931/81910316-52df2480-95bb-11ea-8b6b-e99de722d75a.png)

**Smartphone (please complete the following information):**
- Device: (Nokia 7 plus
- Android-Version: (e.g. 10)
- App-Store:
  - [ ] Google Play Store
  - [x] F-Droid

**Comment by stefan-niedermann** [comment] 2020-05-14 08:25
Not a bug, compare to web interface (`≥ 1.0.0`):

![grafik](https://user-images.githubusercontent.com/4741199/81910710-94c49680-95cc-11ea-825f-34154bddec7b.png)

Two lines would take up too much space and focus from the title. But if anyone is capable of implementing the `LabelLayout` in the way you described (Put as much labels as space is available. If they don't fit, put a "ellipsize" label as last item): Pull Requests are welcome :rocket:

**Comment by stefan-niedermann** [comment] 2020-05-14 08:40
The longer i think about it, the more i believe that the current behavior is better than only displaying 2-3 tags and an "..." tag, because:

- You can see all tags and guess them by the start of their name
- Even if they are displayed so small, that there is no text anymore, you can guess them based on their color

Alternative is to only display a subset of all tags which might be critical for other users if they cannot directly see all labels on their card.

**Comment by q-wertz** [comment] 2020-05-14 08:42
In the browser (on PC) the advantage is, that by hovering over the tag it get's "expanded".
How is the width of the tags calculated? For me it looks like it's depending on the full size text lenght and then downscaled (which I personally don't think is a good way because the length of the tagname does not necessarily correspont to the importance...)
Wouldn't it make more sense to just distribute the width equally between the tags?

**Comment by stefan-niedermann** [comment] 2020-05-14 08:54
Currently it's in a flexbox layout and therefore the final width is based on the text length, correct.

While this does not match the importance of the text, it will help to recognize labels by the length. If you have an important label like "bug" (which you typically will color in red), you will remember and recognize a small red label.

> Wouldn't it make more sense to just distribute the width equally between the tags? 

This won't fix the problem you described (width does not match importance), because the width will depend on how many tags are on one card and therefore also be different from card to card.

Also this will lead to short tags having lots of "empty" space which is not actually empty but a colored surface which will take much attention.

We had a similar layout a few versions ago (fixed display the first few characters of the tags), but people started complaining because they use prefixes for their tags ("feature/xyz", "feature/abc") and the first few characters are actually the *less* importants :smile: 

It's tricky and i think the "best" layout highly depends on how people actually are *using* the tags - everyone seems to have a different use-case and workflow.

After all i think, the current layout is a good compromise and it follows the layout in the web interface.

**Comment by q-wertz** [comment] 2020-05-14 09:33
Ok. Thanks for the explanation :)
I also already thought of the prefix case but in the end it's a matter of taste and there is no "perfect" solution...

**Comment by stefan-niedermann** [comment] 2020-05-14 09:42
Guess so, but discussions from time to time are good to reflect decisions which have been made in the past, therefore closing as "won't fix" - for now 🙂

**Closed by stefan-niedermann** 2020-05-14 09:42 UTC
Labels: enhancement, good first issue, help wanted
