### ISSUE TITLE
List widget not working on Xiaomi launcher

### ISSUE THREAD

**Issue by jmlgo** [stefan-niedermann/nextcloud-deck#741] opened 2020-11-21 19:02 UTC
**Describe the bug**

Regardless what list I pick, the widget never appears on my home screen. 

**To reproduce**
Issue is reproducible with an account from [try.nextcloud.com](https://try.nextcloud.com):
- [ ] Yes

1. Go to widgets
2. Click on Nextcloud Deck List (3x2)
3. Pick one of the available lists

**Expected behavior**
The widget should be on the home screen.

**Versions**
 - Nextcloud: 20.0.1.1
 - Nextcloud Deck: 1.2.1
 - Nextcloud Android: 3.14.0
 - Nextcloud Android Deck: 1.12.1

**Smartphone (please complete the following information):**
- Device: Xiaomi Mi9
- Android-Version: Android 10 QKQ1 (MIUI global 12.0.3 stable)
- App-Store:
  - [ ] F-Droid

**Are you using LDAP?**
- [ ] No

**Comment by stefan-niedermann** [comment] 2020-11-21 19:04
Which launcher are you using?

**Comment by jmlgo** [comment] 2020-11-21 19:05
Default MIUI system launcher.

**Comment by stefan-niedermann** [comment] 2020-11-21 19:08
Does the Single Card widget work flawlessly?

**Comment by jmlgo** [comment] 2020-11-21 19:11
Indeed, it does.

There two options for the MIUI launcher:
![IMG_20201121_200847](https://user-images.githubusercontent.com/16480649/99885486-959e4b00-2c35-11eb-8152-5acc03fcff32.jpg)

Tried both of them with the list widget, unsuccessfully.

**Comment by stefan-niedermann** [comment] 2020-11-21 19:12
Can you try steps 1-4 [mentioned here](https://www.guidingtech.com/fix-miui-widgets-not-working/) please? It seems to be an issue on Xiaomi launcher only.

**Comment by jmlgo** [comment] 2020-11-21 19:20
Tried all but the MIUI optimizations one.
To require this option whould be a major flaw, since the behavior of the system changes completly.
I'll try this option with my old xiaomi phone, since disabling the optimizations requires a reboot and affects the usability.
I'll try to get and post here a trace from the logcat after adding the widget.

**Comment by stefan-niedermann** [comment] 2020-11-21 19:25
Yep, in the first place it's to help us finding the root cause of the issue, it's not meant as a proper solution.
I hope to get information whether it is caused by Xiamo or whether an exception is thrown (widgets are damn shitty to debug). If it works with one of those options, i can be sure that our code works actually correct, then we can try to find a workaround for xiaomi. Otherwise we will need to debug the widget (though i don't have a xiaomi device to test)...

**Comment by stefan-niedermann** [comment] 2020-11-22 19:53
cc @dan0xii do you have a Xiaomi device?

**Comment by jmlgo** [comment] 2020-11-22 20:29
I couldn't find anything relevant on the logcat after trying to add the widget; only this warning, maybe it says something to you:

`11-22 21:16:35.195 W/XSpaceManagerService(1637): checkXSpaceControl, from:android, to:it.niedermann.nextcloud.deck, with act:android.appwidget.action.APPWIDGET_CONFIGURE, callingUserId:0, toUserId:0`

I have experience debbuging desktop software and embedded devices, but I've never worked before with android. I can try to help to debug this issue if you have any clues where to look, since it seems to affect only xiaomi phones. I've tried with a lenovo yoga book and a recent samsung phone and worked flawlessly.

**Comment by stefan-niedermann** [comment] 2021-02-19 11:43
@jmlgo could you please check whether the same issue appears with the "Upcoming cards" widget?

**Comment by jmlgo** [comment] 2021-02-19 11:46
Checked. Seems to work like a charm! (v1.14.4)

**Comment by stefan-niedermann** [comment] 2021-02-19 11:53
Okay, we plan to rewrite the list widget from scratch (and write it like the Upcoming cards widget), so let's close this issue in favor of #767 - please subscribe to this issue to get news about the current progress. :+1:

**Closed by stefan-niedermann** 2021-02-19 11:53 UTC
Labels: 🐞 bug
