### ISSUE TITLE
🏷️ Auto complete: Display all available tags on click (scrollabel)

### ISSUE THREAD

**Issue by armaccloud** [stefan-niedermann/nextcloud-deck#263] opened 2020-01-11 08:15 UTC
**Is your feature request related to a problem? Please describe.**
When applying a tag to a card, there are only three tags shown, even though there are more tags defined for the board. The only in which you can select a tag that is not shown, is to know the name so you can filter the  tags by name.

**Describe the solution you'd like**
An option would be to show all tags in the list and have the ability to scroll down. Having it limited to showing 25 in the scroll-down menu can secure performance, having it only load 25 more when scrolling to the bottom of the list each time.

Also, there is a lot of empty space in between the tags unused. They could be displayed as they are in the full application to save space both horizontally and vertically.

**Comment by klawdhfzasjhaa** [comment] 2020-01-21 13:40
I would like to add:

I want to use years as tags: 2020, 2021... But only "20" is shown, although there would be enough place left. Especially on a tablet in landscape mode, it would be good to have a more responsive design.

**Comment by stefan-niedermann** [comment] 2020-01-21 15:32
Did i understand you correct, that this is a direct duplicate of https://github.com/stefan-niedermann/nextcloud-deck/issues/192 ?

**Comment by armaccloud** [comment] 2020-01-21 17:44
This issue is unrelated to #192, but I think the comment from @klawdhfzasjhaa is.

**Comment by stefan-niedermann** [comment] 2020-01-21 17:48
Yes, i meant @klawdhfzasjhaa's comment :)

**Comment by stefan-niedermann** [comment] 2020-04-25 12:20
I agree, performance shouldn't be an issue even if one has 100 tags in one board because we already are using a `RecyclerView`.

**Comment by stefan-niedermann** [comment] 2020-04-26 16:36
All tags will be shown beginning with version `0.7.0` (not yet released). When typing, matching tags are shown only (like the current behavior).

**Closed** 2020-04-26 16:36 UTC
Labels: UI / UX, enhancement
