### ISSUE TITLE
IllegalStateException: Not a JSON Object: "xxxxxx"

### ISSUE THREAD

**Issue by treuss** [stefan-niedermann/nextcloud-deck#564] opened 2020-06-28 13:23 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**

After factory reset of my Smartphone, Nextcloud Deck for Android cannot log into my Nextcloud instance anymore. Nextcloud server is working fine - no problems when logging in using apps like Nextcloud for Android, Nextcloud News for Android, Nextcloud Bookmarks etc.
I even tried to log in using a freshly created App-Password

**To Reproduce**
1. Open Nextcloud Deck for Android (F-Droid or Google Play Store - doesn't make any difference)
2. Log into your Nextcloud server
3. There'll show up a stack-trace, but unfortunately so short, that not even a screenshot is possible
4. Error shows up too shortly to be read

**Expected behavior**

App logs into Nextcloud Server instance.

**Screenshots**

**Versions**
 - Nextcloud: 18.0.6
 - Nextcloud Deck: 1.0.4
 - Nextcloud Android: 3.12.0
 - Nextcloud Android Deck: 1.4.4

**Smartphone (please complete the following information):**
- Device: Google Pixel 3
- Android-Version: 10, Build QQ3A.200605.001
- App-Store:
  - [x] Google Play Store
  - [x] F-Droid

**Stacktrace**

Unfortunately it disappears long before I could even copy.

**Comment by stefan-niedermann** [comment] 2020-06-28 13:41
Hey @treuss ,

- Have you tried to clear the storage of **both** apps [as described here](https://github.com/stefan-niedermann/nextcloud-deck/wiki/FAQ)?
- Are you using Nextcloud News also with the Single Sign On mechanism?
- Can you please create a test account and send the credentials to info@niedermann.it so we can have a look what's going on?
  - You can also try to login to this test account to make sure that the issue is not account related but instance- or app related.

Regards

**Comment by treuss** [comment] 2020-06-28 14:10
* Yes, I even erased both apps multiple times
* Using it per SSO-Mechanism. Just verified it once again. Works like a charm.
* Will send a test-account in a few minutes.

**Comment by stefan-niedermann** [comment] 2020-06-28 14:29
Test-Account works like a charm:

![grafik](https://user-images.githubusercontent.com/4741199/85950323-5d336300-b95c-11ea-8a6b-b475ab5fb07f.png)

Are you able to connect to this test account, too? I will send you the password i just set for the account via E-Mail.

**Comment by stefan-niedermann** [comment] 2020-06-28 14:34
Are you able to connect to your account from another device (family or friends)? (If you need free Play Store vouchers for testing purposes, let me know via info@niedermann.it)

**Comment by treuss** [comment] 2020-06-28 14:37
Ok, I could log in using the test-account. This is weird. My personal account works perfectly well.
Is there any chance to get some logs for this behavior?

**Comment by treuss** [comment] 2020-06-28 14:48
Don't know if this helps. I get the following stacktrace when klicking on the hamburger menu:

```
App Version: 1.4.4
App Version Code: 1004004
App Flavor: play

Files App Version Code: 30120090

---

OS Version: 4.9.210-g28c696160049-ab6386370(6392402)
OS API Level: 29
Device: blueline
Manufacturer: Google
Model (and Product): Pixel 3 (blueline)

---

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Long it.niedermann.nextcloud.deck.model.Account.getId()' on a null object reference
	at it.niedermann.nextcloud.deck.ui.filter.FilterLabelsFragment.onCreateView(FilterLabelsFragment.java:34)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2698)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1187)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:442)
	at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2169)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1992)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1947)
	at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1818)
	at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:297)
	at androidx.viewpager2.adapter.FragmentStateAdapter.placeFragmentInViewHolder(FragmentStateAdapter.java:341)
	at androidx.viewpager2.adapter.FragmentStateAdapter.onViewAttachedToWindow(FragmentStateAdapter.java:276)
	at androidx.viewpager2.adapter.FragmentStateAdapter.onViewAttachedToWindow(FragmentStateAdapter.java:67)
	at androidx.recyclerview.widget.RecyclerView.dispatchChildAttached(RecyclerView.java:7556)
	at androidx.recyclerview.widget.RecyclerView$5.addView(RecyclerView.java:860)
	at androidx.recyclerview.widget.ChildHelper.addView(ChildHelper.java:107)
	at androidx.recyclerview.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:8601)
	at androidx.recyclerview.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:8559)
	at androidx.recyclerview.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:8547)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1641)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3540)
	at android.view.View.measure(View.java:25086)
	at android.view.ViewGroup.measureChild(ViewGroup.java:6843)
	at androidx.viewpager2.widget.ViewPager2.onMeasure(ViewPager2.java:498)
	at android.view.View.measure(View.java:25086)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:25086)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:25086)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:25086)
	at androidx.appcompat.widget.AlertDialogLayout.tryOnMeasure(AlertDialogLayout.java:134)
	at androidx.appcompat.widget.AlertDialogLayout.onMeasure(AlertDialogLayout.java:64)
	at android.view.View.measure(View.java:25086)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
	at android.view.View.measure(View.java:25086)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:25086)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:25086)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:25086)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6872)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:742)
	at android.view.View.measure(View.java:25086)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3083)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1830)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2146)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1745)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7768)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:967)
	at android.view.Choreographer.doCallbacks(Choreographer.java:791)
	at android.view.Choreographer.doFrame(Choreographer.java:726)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by treuss** [comment] 2020-06-28 14:49
> Are you able to connect to your account from another device (family or friends)? (If you need free Play Store vouchers for testing purposes, let me know via [info@niedermann.it](mailto:info@niedermann.it))

Thanks for the offer, but I gladly already purchased.

**Comment by stefan-niedermann** [comment] 2020-06-28 15:08
> Don't know if this helps. I get the following stacktrace when klicking on the hamburger menu:

Unfortunately not, this is a follow up of a defect account import and does not provide any useful information.

> Ok, I could log in using the test-account. This is weird. My personal account works perfectly well except for the Android Deck app.

At least we know now, that this is an account specific issue.

> Is there any chance to get some logs for this behavior?

You could try to fetch some logs using any [logcat reader](https://play.google.com/store/apps/details?id=com.dp.logcatapp) of your choice (though i think root access is required for this). If you are familiar with Android Studio, the easiest would be to read the logs there directly.

I see your instance is running at home behind a dynamic dns service. Does it run on a Raspberry Pi (it's a bit slow)? I suspect some kind of network or server hiccup. Since when does the issue persist?

**Comment by treuss** [comment] 2020-06-28 15:40
> > Don't know if this helps. I get the following stacktrace when klicking on the hamburger menu:
> 
> Unfortunately not, this is a follow up of a defect account import and does not provide any useful information.

I guessed so ;)

> > Ok, I could log in using the test-account. This is weird. My personal account works perfectly well except for the Android Deck app.
> 
> At least we know now, that this is an account specific issue.
> 
> > Is there any chance to get some logs for this behavior?
> 
> You could try to fetch some logs using any [logcat reader](https://play.google.com/store/apps/details?id=com.dp.logcatapp) of your choice (though i think root access is required for this). If you are familiar with Android Studio, the easiest would be to read the logs there directly.

Android Studio shouldn't be an issue. It'd take some time though.

> I see your instance is running at home behind a dynamic dns service. Does it run on a Raspberry Pi (it's a bit slow)? 

I started the whole thing using a Raspberry Pi 3B, which actually was pretty slow. It did it's job though, and since my main objectives were privacy (getting out of Google and other cloud services), a low energy footprint and having a fun server project, it was ok.
Next step was the 4GB version of the Raspberry Pi 4, which significantly improved performance, especially after I've finally gotten faster DSL. 
Now it's running on the 8 GB version Raspberry Pi 4, and it honestly feels similarly performant (if not better) to the 2-Core Intel VM our work-instance is running on. Did quite some tuning (nginx, OPCache and APCu) in order to get it as fast as possible.

> I suspect some kind of network or server hiccup. Since when does the issue persist?

Not exactly sure. I think it was the day, when I noticed I can purchase it on Google Play and switched over from the free version.
 
> Ah, and please check whether you can connect to your problematic account from another device.

I'll try that and let you know.
Thanks a lot for your help!

**Comment by treuss** [comment] 2020-06-28 15:48
I could reproduce the error on my (sluggish) Kindle after deleting my account an doing a re-login.
`treuss` is my username:

```
App Version: 1.4.4
App Version Code: 1004004
App Flavor: play

Deck Server Version: 0.6.4

Files App Version Code: 30120090

---

OS Version: 4.4.146+(0017884837764)
OS API Level: 28
Device: maverick
Manufacturer: Amazon
Model (and Product): KFMAWI (maverick)

---

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Not a JSON Object: "treuss"
	at com.google.gson.Gson.fromJson(Gson.java:944)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.nextcloud.android.sso.api.NextcloudAPI.performRequest(NextcloudAPI.java:101)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservable$0$NextcloudAPI(NextcloudAPI.java:86)
	at com.nextcloud.android.sso.api.-$$Lambda$NextcloudAPI$yhhE-DMCe81fXF-bhjup5Tra-6o.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.IllegalStateException: Not a JSON Object: "treuss"
	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:91)
	at it.niedermann.nextcloud.deck.api.JsonToEntityParser.parseCard(JsonToEntityParser.java:237)
	at it.niedermann.nextcloud.deck.api.JsonToEntityParser.parseStack(JsonToEntityParser.java:408)
	at it.niedermann.nextcloud.deck.api.JsonToEntityParser.parseJsonObject(JsonToEntityParser.java:45)
	at it.niedermann.nextcloud.deck.api.NextcloudArrayDeserializer.deserialize(NextcloudArrayDeserializer.java:36)
	at it.niedermann.nextcloud.deck.api.NextcloudArrayDeserializer.deserialize(NextcloudArrayDeserializer.java:18)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	... 15 more

```

**Comment by stefan-niedermann** [comment] 2020-06-28 15:56
Could you please try this version: https://niedermann.it/deck156.apk ? It *might* actually contain a fix for that, at least it's worth a try.

It will replace the app you got from Google Play. Of course: Clear storage of both apps again, before trying it!

> Thanks a lot for your help!

You're welcome, we try to fix the issue :slightly_smiling_face:

**Comment by desperateCoder** [comment] 2020-06-28 16:06
> Not a JSON Object: "treuss"

God, please, NO! Not _this_ again! :sob: 

We had quite some issues with this already, the cause is, that the server in some (unknown) constellation decides to send the owner of a board as a simple string instead of an object. The weird thing here is this: https://github.com/stefan-niedermann/nextcloud-deck/blob/a51df7357ec8cd561922acac1a75adb5ef95d3c8/app/src/main/java/it/niedermann/nextcloud/deck/api/JsonToEntityParser.java#L237

I DO check on that already, why the hell would this result in this error? 

To actually hunt this down we could make a special, more verbose log output to see what you actually get from the server. Would this be ok for you?

**Comment by stefan-niedermann** [comment] 2020-06-28 16:07
@desperateCoder noticed that he still used `1.4.4` because the current version at Play Store is not yet rolled out completely? Let's wait if it works with the apk i shared above...

**Comment by desperateCoder** [comment] 2020-06-28 16:13
@stefan-niedermann but... i didn't change anything since then here... I mean... the line mentioned above is there for like forever, (including the TODO). I planned to remove this, as soon as the server _always_ returns the correct data, but unfortunately we see this every here and then... I think I'm about to cry.

But sure, it's definitely worth a try. Plan B: Build a debug-version which dies instantly at this point and provides more information about the actual data from the server ( => the suggestion in my comment above)

**Comment by treuss** [comment] 2020-06-28 16:14
@desperateCoder I'm sorry, surely didn't want to ruin your Sunday! :-/
I did wipe my caches and rebooted the whole server, hoping it might be some nasty cache anomaly....

It's perfectly ok for me to wait for a new version. Willing to help you guys.

**Comment by desperateCoder** [comment] 2020-06-28 16:22
@treuss god, none of this is your fault buddy! I just hate the fact, that anything i do to prevent this one fails at some point with the weirdest symptoms. Please ruin all my days if you have any issues, this app is kind of Stefans an my baby and we hate it, if it gets sick :laughing: 

So thanks for your effort and cooperation with this! This doesn't only help you and other users, but it helps us too, since we can't recreate any constellation out there while testing. 

I don't have much hope that the new version will solve the issue, but when it doesn't please ruin my day again until I am able to ruin the hell out of this bugs day :wink: 

As mentioned above, we have quite some more options to get behind the cause of this.

**Comment by loicvh** [comment] 2020-06-29 11:30
If I may "jump" into this issue, I got exactly the same issue as @treuss and I managed to find a workaround.

It seems that only some boards were causing issues, deleting them (not archiving), fixes the issue for me. I don't know if this can help, but maybe this could be some backward compatibility issue?

Also, to quickly detect which boards cause problems, I first added an account without any board to the app and then, I added my real account. Doing this, the app does not crash and all boards are loaded but only the ones without any problem have loaded the cards.

**Comment by treuss** [comment] 2020-06-29 12:39
Thanks for the heads up @loicvh . Actually I was thinking of deleting all my boards, since [I seem to have run into another bug (not related to the Android App)](https://github.com/nextcloud/deck/issues/2083).

**Comment by desperateCoder** [comment] 2020-07-11 17:22
@loicvh Yep, this is kind-of known. The problem is, that some owners or sharees should be user-objects, but in some constellation they come as a simple string. Why? Don't know...

I don't want to tell the users "let's delete some boards!" as a solution, that wouldn't match my understanding of "help", depending on the importance of the data. But nice research though, especially how to determine, which one is the bad guy!

We plan to implement some helping feature on this (https://github.com/stefan-niedermann/nextcloud-deck/issues/586).

Please be patient, i have to admit, that things aren't easy these days for me, very much stuff preventing me from contributing, but things will go on soon i guess.

**Comment by stefan-niedermann** [comment] 2020-07-13 22:19
@treuss since you had a [defect database migration](https://github.com/stefan-niedermann/nextcloud-deck/issues/564#issuecomment-651091950) on your server side app, i would propose to close this in favor of #586.

In fact there is nothing we can directly do if the state of the server side database is corrupt. Let's focus on helping the users to find the root cause and fix them (instead of hiding them in the Android app).

In the meantime i recommend you to remove all shares of your boards. Maybe it is not even necessary to actually delete the boards. Just unshare all your boards and give it another try.

> SysAdmin. Because even developers need heroes. Linux enthusiast & Metal Head

Made my day, by the way :laughing: :metal: :guitar:

**Closed by stefan-niedermann** 2020-07-13 22:19 UTC
Labels: ❔ needs info, 🐞 bug

**Comment by treuss** [comment] 2020-07-14 07:08
> @treuss since you had a [defect database migration](https://github.com/stefan-niedermann/nextcloud-deck/issues/564#issuecomment-651091950) on your server side app, i would propose to close this in favor of #586.
> 
> In fact there is nothing we can directly do if the state of the server side database is corrupt. Let's focus on helping the users to find the root cause and fix them (instead of hiding them in the Android app).

Yes, this sounds more reasonable. 
You might want to check though, why the pop-up window showing the stacktrace disappears in about 500 to 600ms on my device.
 
> In the meantime i recommend you to remove all shares of your boards. Maybe it is not even necessary to actually delete the boards. Just unshare all your boards and give it another try.

Since it's on to me to drop the boards, I'm actually thinking of dropping all Deck-related tables in the database. I guess a fresh, clean restart makes sense.

> 
> > SysAdmin. Because even developers need heroes. Linux enthusiast & Metal Head
> 
> Made my day, by the way 😆 🤘 🎸

Hehe, glad to see a fellow here! 😉 🤘

**Comment by desperateCoder** [comment] 2020-07-14 07:16
> Hehe, glad to see a fellow here! 😉 🤘

Make it double! 😉 🤘

**Comment by stefan-niedermann** [comment] 2020-07-14 07:33
>  You might want to check though, why the pop-up window showing the stacktrace disappears

Yeah, i will have a look. I think it's because while syncing there happen multiple errors and each new error dismisses the previous errors. I just thought that at least the last error would stay longer 🤔 and i can't reproduce it yet unfortunately. But i'll have a look into it.
