### ISSUE TITLE
Labels in cards are added with every save action

### ISSUE THREAD

**Issue by JoergPalmer** [stefan-niedermann/nextcloud-deck#644] opened 2020-08-04 14:28 UTC
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**
When a card is created from the Android app, every "save" adds another one to all existing labels, so that the label is included multiple times. The effect does not show when a card is created in the web interface and then saved from Android.

**To reproduce**
Issue is reproducible with an account from [try.nextcloud.com](https://try.nextcloud.com):
- [X] Yes
- [ ] No

1. Create a card (in any board)
2. Click on 'Label' and pick one or more labels
3. Click 'Save' in the top right corner of the card editor window
4. Check labels in web interface
5. Click 'Save' in the top right corner of the card editor window
6. Check labels in web interface -> there are now two labels of each previously selected labels

... on any save action, one more label of previous selected labels is added

**Expected behavior**
A save action should only save what's on the editor screen 

**Screenshots**
![CP-1086 COMPART-2020-08-04-08:51 29](https://user-images.githubusercontent.com/24966707/89305413-e4b47600-d66e-11ea-9b33-aec1fec4c2ec.png)
![CP-1086 COMPART-2020-08-04-08:51 46](https://user-images.githubusercontent.com/24966707/89305417-e5e5a300-d66e-11ea-99ea-79682944c5ca.png)

**Versions**
 - Nextcloud: 18.0.7
 - Nextcloud Deck: 1.0.5
 - Nextcloud Android: 3.12.1
 - Nextcloud Android Deck: 1.9.3

**Smartphone (please complete the following information):**
- Device: Xiaomi Poco F1
- Android-Version: 10
- App-Store:
  - [X] Google Play Store
  - [ ] Google Play Store (Beta channel)
  - [X] F-Droid
  - [ ] Huawei AppGallery

**Are you using LDAP?**
- [ ] Yes
- [X] No

**Stacktrace**

**Comment by stefan-niedermann** [comment] 2020-08-04 14:31
Thank you for the report. While i agree that the Android app has  clearly a bug here, i still would like to mention @juliushaertl as this should be fetched at least at the API 😄

**Comment by reox** [comment] 2020-08-05 08:24
on the web app it is really weird how to get rid of the multiple labels. If you click on the label in the list one dissappears at a time, not all at once...

**Comment by JoergPalmer** [comment] 2020-08-05 08:29
> on the web app it is really weird how to get rid of the multiple labels. If you click on the label in the list one dissappears at a time, not all at once...

True .. also for me all Android app created cards get labels added, not just the one I'm saving.

**Comment by stefan-niedermann** [comment] 2020-08-05 08:33
@reox In the Web UI, click on the tags, you will see your label with a check in front of it. You can click multiple times on it (without leaving the edit mode or save the card). Click as often as you need to remove all the wrong labels as a workaround.

@JoergPalmer 

> Please use GitHub reactions 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add.

**Comment by JoergPalmer** [comment] 2020-08-05 12:50
For me, **all** cards created from the Android app get additional labels, not just the one I'm saving.

**Comment by desperateCoder** [comment] 2020-08-05 13:46
Ok, I was able to reproduce it. Most likely my fault, I'll fix that as soon as possible.

**Comment by desperateCoder** [comment] 2020-08-05 20:03
Yep, I found it, it is the same as here: #640 

Root cause:
https://github.com/nextcloud/Android-SingleSignOn/issues/231

I guess we're blocked here.

**Comment by aproposnix** [comment] 2020-08-07 09:45
Can I get confirmation of one thing? Until there is fix for this issue, I should avoid creating cards within the Android app, correct? My understanding is that cards created from the web app don't have the same issue.

**Comment by desperateCoder** [comment] 2020-08-07 09:50
@aproposnix almost, you can create cards as many as you want, the problem relies in the labels **assignment**

what actually happens:
- you create a card (no problem)
- the label is assigned -> call to server
- server assigns, but doesn't return any data (ok so far)
- the SSO-Library fails internally, telling our app it didn't work
- so at the next sync **(!)** the card is still marked as "not synced yet", so it tries again (procedure starts again at the second point)
-> you end up with a sh*itload of assigned labels

Again: @juliushaertl yep, we have a bug here, but the backend should answer 200 and not do anything else, if the label is already assigned.

**Comment by stefan-niedermann** [comment] 2020-08-09 15:03
Fix shipped with `1.9.7`.

**Closed** 2020-08-09 15:02 UTC
Labels: 🐞 bug, 🚫 blocked

**Comment by aproposnix** [comment] 2020-08-11 11:06
thank you everyone who worked to resolve this! I can confirm from my side that I'm not getting duplicated tags.

**Comment by desperateCoder** [comment] 2020-08-11 11:09
@aproposnix you're welcome 😄, sorry for the inconveniences!

**Comment by MartinMai** [comment] 2021-09-04 16:32
I can reproduce creating many duplicate labels when clonig a board with cards in the android app.
The duplicate labels seem to appear only on the web-vie not in the app. The number of duplicate labels seems to vary (from 2 to many).
App Version 1.19.3, Deck Server Version 1.5.1, Nextcloud 22.1.1

**Comment by desperateCoder** [comment] 2021-09-04 16:47
Hi @MartinMai, thanks for your report and thanks for using the search! In this case, considering the fact you cloned a board, I guess your issue isn't really related to this one. 

Please open a new issue for this, including the steps to reproduce (like stated in the issue template). That way we won't bother all the involved people here and we can focus on your actual problem. 

Thanks in advance!
