### ISSUE TITLE
no description  or assigned user info

### ISSUE THREAD

**Issue by zamantech** [stefan-niedermann/nextcloud-deck#1401] opened 2023-01-11 07:42 UTC
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

the user have normal permission.. 

1. Go to 'the board'
2. Click on 'the task'
3. See the task without view of description and assigned user (can't see anything)
![deckissue](https://user-images.githubusercontent.com/64734686/211745981-db56083e-56d5-4bc8-a881-981d01eb17b1.jpg)

**Expected behavior**

I believe it should be like the web version..

**Screenshots**

![image](https://user-images.githubusercontent.com/64734686/211746419-bc1c8513-160b-413d-9955-9f2f6a12000a.png)

**Versions**

 - Nextcloud: 24.0.6
 - Nextcloud Deck: 1.7.1
 - Nextcloud Android: 3.23.1
 - Nextcloud Android Deck: 1.21.7 and 1.21.3

**Smartphone (please complete the following information):**
- Device: redmi k20 pro
- Android-Version: 11
- App-Store:
  - [ ] Google Play Store
  - [ ] Google Play Store (Beta channel)
  - [x] F-Droid
  - [ ] Huawei AppGallery

**Comment by stefan-niedermann** [comment] 2023-01-11 07:51
Can you please tell us a bit more about the environment?
- Eho owns the board? You or someone else?
- Is the board shared? With which permissions? (read, write, ...)
- Are you using a LDAP backend for your user?
- Is the board shared with a single user, a group or a circle?

**Comment by zamantech** [comment] 2023-01-11 14:34
1- with read permission show as i said
2- sure
3- Y
4- both

**Comment by stefan-niedermann** [comment] 2023-01-11 15:08
That's interesting. The description seems to be there as the checkmarks are directly generated from the content.

Could you please try to set your device language temporarily to english or any other left-to-right language and check the behavior then?

**Comment by zamantech** [comment] 2023-01-12 05:44
> That's interesting. The description seems to be there as the checkmarks are directly generated from the content.
> 
> Could you please try to set your device language temporarily to english or any other left-to-right language and check the behavior then?

Actually it's an English language,I try with an Arabic (Huawei Phone) the same with another user
![deck](https://user-images.githubusercontent.com/64734686/211987026-ee0815ce-b951-4cf1-aed5-e014bd6915b9.jpg)

**Comment by zamantech** [comment] 2023-01-12 06:01
what i try:
- to remove group and user direct user
- use another device 
- use another account 
- user other device language 
Note:
- when switch to another account with higher permission there is no issue
- after click on task the description shown on edit mode not on read mode

**Comment by stefan-niedermann** [comment] 2023-01-12 13:33
> are there way to show logs or something like that?

You can enable logging in the Deck Android apps settings and export then by pressing the beetle icon in the sidenav.

⚠️ Please remove sensitive personal data before sending oe posting the logs
⚠️ Please disable the logging after exporting the logfile. Quite a large amount of data will be generated and fill your RAM otherwise

I am still not sure whether this is an actual permission issue (given there **are** no permissions on field level right now) or it is a synchronization issue - logs will be helpful in this case. Please send them to info@niedermann.it

Could you also please test removing your entire account and import it again in the Deck Android app (after generating logs of course). Does the issue persist?

**Comment by zamantech** [comment] 2023-01-14 07:18
> till not sure whether this is an actual permission issue (given there **are** no permissions on field level right now)

the permission is normal (not edit,share or manage)
Yea, i try re-add account ,upgrade system..the same
by the way i had another account with edit permission and there is no issue with it
the email was send to u
Best Regards

**Comment by zamantech** [comment] 2023-01-16 13:21
any news?

**Comment by stefan-niedermann** [comment] 2023-01-16 14:20
Not yet. We will provide you a test build these days with extended logging for your use case, which you will need to install to get some more logs - instructions will follow :)

**Comment by stefan-niedermann** [comment] 2023-01-18 11:50
Given the tasks indicator (:heavy_check_mark: in the list view) seems to work correctly, I assume that the description is correct in the database and the issue is only when displaying the content - I added some logs in this part of the app so we can see what the UI actually queries form the database when it tries to display the description.

1. Please download, unzip and install [this debug build](https://github.com/stefan-niedermann/nextcloud-deck/suites/10438047321/artifacts/516329834). You can safely install it parallel to the F-Droid version and you will recognize it by the `Dev` label on the app icon
2. Go to the Deck Android apps, enable logging
3. Open the card with the not working description
4. Go to the sidebar and click the :lady_beetle: icon - send the log file to the mail address as the last time

Also please check whether the description is displayed in the preview mode (clicking on the :eye: icon at the top right of the description field).

**Comment by zamantech** [comment] 2023-01-21 21:39
the details was sent to you

**Comment by zamantech** [comment] 2023-01-27 11:31
**any update?**

**Comment by stefan-niedermann** [comment] 2023-01-27 11:32
Yes, I think I found the origin of the problem and it indeed is related to the permissions as you already riddled out.

I'll post here when the issue has been fixed.

**Comment by zamantech** [comment] 2023-01-28 05:31
Ok,Thank u

**Comment by stefan-niedermann** [comment] 2023-02-01 07:56
Alright, I think I fixed both, description and assignees. Rolling out on Play Store and F-Droid will take some time, but you can [download this debug build](https://github.com/stefan-niedermann/nextcloud-deck/suites/10705896449/artifacts/536243576) to test and verify the fix in the meantime :) Thanks for the report!

Final fix will be in `1.21.8`

**Closed by stefan-niedermann** 2023-02-01 07:56 UTC
Labels: 🐞 bug
