### ISSUE TITLE
Multiple duplicate cards, lists or boards after creating them offline, then enabling data/wireless and syncing to server

### ISSUE THREAD

**Issue by himarmajhool** [stefan-niedermann/nextcloud-deck#1287] opened 2022-06-04 21:04 UTC
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

1. Disable data and wireless on smartphone
2. Create and/or edit new cards/lists
3. Enable data or wireless
4. Duplicate boards/cards/lists are created. Boards are usually duplicated once, but lists and card are duplicated multiple times. Existing labels are sometimes duplicated up to 10 times.

**Expected behavior**

After syncing with the server, there should be only one created board/list/card with the assigned name. Likewise, moving around an existing board/list/card should not duplicate them (especially since they already have an assigned ID in NextCloud)

**Screenshots**

![image](https://user-images.githubusercontent.com/89733413/172024806-c246fa6c-b322-46e1-a78a-a8500c06e3d2.png)

**Versions**

 - Nextcloud: 
 - Nextcloud Deck: 1.6.1
 - Nextcloud Android: 3.20.1
 - Nextcloud Android Deck: 1.20

**Smartphone (please complete the following information):**
- Device: Samsung Galaxy S9
- Android-Version: 10
- App-Store:
  - [ ] Google Play Store
  - [ ] Google Play Store (Beta channel)
  - [x] F-Droid
  - [ ] Huawei AppGallery

**Stacktrace**
Unavailable (no admin access to server)

**Comment by desperateCoder** [comment] 2022-06-09 11:25
Hi @himarmajhool, thanks for your report, and sorry for the delay, we were on a music festival these days.

Could you please check, if the following version does fix anything for you?

[(≧︿≦) APK](https://github.com/stefan-niedermann/nextcloud-deck/suites/6595843800/artifacts/247583160)

You can safely install it beside your current app, it will be installed as a second deck app with a "DEV" label. Test it with that version and give some feedback please.

**Comment by desperateCoder** [comment] 2022-06-09 14:02
Thanks for your fast reply!

The provided bugreport indeed helped a lot, thanks for sharing. A method I was using is standard java, but not available on every Android device, as it seems.

I replaced it with an alternative one and I'm hoping the following one will work better:

[(⌐⊙_⊙) APK](https://github.com/stefan-niedermann/nextcloud-deck/suites/6863435515/artifacts/265290235)

Before you install it, clear the storage of the DEV app and uninstall it (do both just to make sure, Android can be quite weird regarding dead data).

**Comment by desperateCoder** [comment] 2022-06-10 10:44
Ping @himarmajhool (don't know if you hadn't time to test yet or didn't get a notification because i forgot to tag you, just making sure you see it)

**Comment by himarmajhool** [comment] 2022-06-10 14:49
@desperateCoder sorry for the delay. I just downloaded and installed the new APK, I cleaned the storage and uninstalled the older version as instructed (BTW, I had uninstalled the release version too the first time to make sure there would be no interference while syncing).
The good news is that all my boards, lists and cards got imported successfully.
The bad news is that the problem remains. To give you more details here's what I did exactly to reproduce the bug with more accuracy.
1. turned off 4G and Wifi
2. created a new board with two new lists named To-Do and Done respectively
3. created a couple cards in To-Do
4. turned on Wifi and manually synced with the server
5. My board and its lists got successfully synced, I could see them on the Webapp
6. turned off 4G and Wifi again
7. added a couple cards to the To-Do list in the previously created board
8. moved one of them to an older board
9. turned on Wifi again and manually synced
10. the card I had moved from the new board to the older board got duplicated

I tested that twice with the same result. I'll test again and give you some feedback if I have anything new.

**Comment by desperateCoder** [comment] 2022-06-10 15:10
@himarmajhool thanks for your feedback, i didn't want to distress you though 😅 

Oh boy, ok, so the problem seems to lay deeper in the already very complex sync mechanism. Can you at least confirm, that the duplicated labels attached to the cards are gone? That's where I put the focus on in the build above in the first place. 

To test that, just attach some labels to a couple of cards before going online again.

Thanks for your help finding the core issue btw, that helps a lot since nextcloud is decentralized by design and we're not able to test each and every constellation out there.

I'll keep diving deeper into this, since you're unfortunately not the only one having this kind of issues lately. It might be a change in the server API or maybe I messed up something I'm not aware of, really hard to tell for the time given. I just want to say: sorry for the inconveniences! I'll do my best to solve this as fast as I can, but it might take it's time since we maintain this project in our spare time and the term "sync" is way more complex than it sounds 😩

**Comment by himarmajhool** [comment] 2022-06-10 15:46
Just tested with new labels. The card does get duplicated but the labels are not (I mean I have the same labels in the duplicated card.)

It's a very tricky bug indeed, I don't think I could reproduce _exactly_ what happened the first time my boards got messed up (I made a lot of changes indeed, I wasn't aware I was offline at that time).

> I just want to say: sorry for the inconveniences! I'll do my best to solve this as fast as I can, but it might take it's time since we maintain this project in our spare time and the term "sync" is way more complex than it sounds weary

Thank you for your time and help and no need to apologize. It's Free/Open Source Software and AFAIC I'm neither contributing any code nor paying for support, so I have no right to complain 😉

**Comment by himarmajhool** [comment] 2022-06-11 10:49
Hi @desperateCoder, I tested the new APK, I ran the procedure to reproduce the bug twice and everything seemed to work as intended (labeling included).

**Comment by desperateCoder** [comment] 2022-06-11 10:54
@himarmajhool glad to hear!

regarding the duplicated lists and cards: Not sure how exactly to reproduce that tbh... We had something similar when cloning boards, but i think i already had this resolved within the versions i provided here. Is there any issue left? Or should i consider this issue done now, whats your opinion?

If anything is still not working properly, don't hesitate to tell us.

**Comment by himarmajhool** [comment] 2022-06-11 11:29
@desperateCoder, I guess it's safe to close the issue for now. I'll try to come back with more data (maybe logs from a local instance of NextCloud server, to see what happens exactly on syncing and exclude any possible server-side bugs) if ever the issue emerged in the future.

**Comment by desperateCoder** [comment] 2022-06-11 12:04
Yeah, just open a new issue in case you encounter more difficulties.

Thanks again for your contributions, have a nice weekend!

**Closed by desperateCoder** 2022-06-11 12:04 UTC
