### ISSUE TITLE
crash on start

### ISSUE THREAD

**Issue by Solar-Simon** [stefan-niedermann/nextcloud-deck#686] opened 2020-09-22 20:46 UTC
**Describe the bug**
When I start the Deck App following Error appears:

```

`Attempt to invoke virtual method '...Account.getUserName()' on a null object reference

App Version: 1.9.7
App Version Code: 1009007
App Flavor: fdroid

Deck Server Version: 0.6.4

Files App Version Code: 30130090

---

OS Version: 3.10.84-g2f8811e(df0c828a8f)
OS API Level: 25`
```

The App was running fine till I moved the hole server to another provider. The dns was still the same, leading to a different IP

**Versions**
 - Nextcloud: 19.0.3
 - Nextcloud Deck: 1.1.0
 - Nextcloud Android: 3.13.0
 - Nextcloud Android Deck: 1.9.7

**Comment by desperateCoder** [comment] 2020-09-22 21:02
Hi @Solar-Simon, thanks for your report! First time seeing this kind of issue, so I think you just nailed it by mentioning, that you moved your server. 

Have you already set up your new account at the files app? 
1. If yes: Try to delete the app-data of the Deck app and relogin into your account, just like as you would after first installation.
2. If no: do so, then do the steps in 1. 

Please provide some feedback if that helped, I'd bet we'll get this running :smiley:

**Comment by Solar-Simon** [comment] 2020-09-22 21:07
I tried all that.
* I deleted app-data
* I uninstalled the app and reinstalled
* I uninstalled the nextcloud app and reconnected the account from beginning.

it happend already several month ago and I was just waiting for some update to maybe solve it. But no its time to act ;)
The Error Log says: "Deck Server Version: 0.6.4", But isn't it 1.1.0? Is there something wrong?

**Comment by stefan-niedermann** [comment] 2020-09-23 05:59
> The Error Log says: "Deck Server Version: 0.6.4", But isn't it 1.1.0? Is there something wrong?

`0.6.4` is our minimum supported server version and will be used as default in case the actual server didn't respond as expected. It's just the log, imagine it as `unkown`

**Comment by desperateCoder** [comment] 2020-09-23 10:41
> I tried all that.

Did you try it in the mentioned order? Because you need to reconnect the Nextcloud files app first, then reconnect Deck.
Does the files app work flawlessly with your new server? 

> But now its time to act ;)

No need to wait, unless you're lazy :smile: We're happy to help as fast as we can and we aren't afraid of duplicates. It is better to know the issues fast than having unhappy users out there waiting for a fix for a problem we don't even know about :wink:
Due to the fragmentation and different server-setups, we can't check each and every constellation out there, so we rely very much on you, the users. Thanks again for reporting!

More Background:
Our app gets the Account information from the Nextcloud files app by using a library called "SSO" (SingleSignOn). After you chose your account on the "welcome" screen, we gather the Account information via SSO. That's what seems to be broken in your case. That's why I was asking about the order of the things you tried.

If your Files app works well and you have resetted Deck **afterwards**, we'll need to ask our friends from the SSO-lib in which cases the returned account may be null. We never had this case before to be honest...

**Comment by goldengel** [comment] 2020-09-26 10:08
I had same issue since several month. I solved i by the following:

Nextcloud Version: 19.0.3
Server Version: Deck 1.0.5
App Version 1.9.7

Problem: Deck App does crash on startup
Reason: Some conflicts on parsing attached files
Solution: Delete attached files in SQL database ‘oc_deck_attachment’

Connect in Deck App with account > wait 1 minute (if nothing is responding in app) > kill app > re-open app. 

Attachments are gone but the app is working again.

**Comment by desperateCoder** [comment] 2020-09-26 14:02
@goldengel thanks for your suggestion! Are you really sure the error mentioned something like `Account.getUserName()` has failed? At this point, the app didn't even attempt to connect to the server, since it hasn't any information about it :thinking: 
I'm pretty sure you had some different problems than @Solar-Simon, but great that you care enough to suggest your solution! Thanks for sharing!

**Comment by desperateCoder** [comment] 2020-09-26 14:06
@Solar-Simon would you mind providing us a test account on your instance? I'd like to see, if I get the same error on my development machine, I'd be able to track down the root cause.
No need for much disk space or stuff, just a regular account with minimum permissions would be enough.
If you're fine with it, please create it and send the credentials to info@niedermann.it - thanks in advance!

**Comment by Solar-Simon** [comment] 2020-09-29 09:38
Hey, not so sure weather this is a good message now:
I reinstalled the Deck App on my phone once again - now it's working all fine.
So I cant reproduce the error anymore.
For now this Issue could be closed, from my side. 
Any further questions? Thanks for your quick and friendly help!!!

**Comment by stefan-niedermann** [comment] 2020-09-29 09:44
Well first of all: good news for you! Thank you for the update. 🙂 

I guess it will be nearly impossible to find the exact root cause, especially since you can not longer reprouce it yourself.

Let's close it for now and spend more time on an analysis in case you ever experience it again.

It might have to do with your server migration (anything not fully initialized or so) or a server hickup or maybe even some kind of upstream bug that has been fixed in the meantime by an update.

Just reopen it if you ever have the issue again!

**Closed by stefan-niedermann** 2020-09-29 09:44 UTC

**Comment by desperateCoder** [comment] 2020-09-29 09:56
Glad it worked out for you! 

> Any further questions?

I guess it was just the order of things you tried - I'm fine with that as long as it works for you. 

>  I'm willing to help, if you wanna investigate further...

Very appreciated, thanks!

> Thanks for your quick and friendly help!!!

Sure, you're welcome, any time!
