### ISSUE TITLE
No sync with OnePlus until battery saving is disabled

### ISSUE THREAD

**Issue by jakobroehrl** [stefan-niedermann/nextcloud-deck#826] opened 2021-02-14 20:56 UTC
Tested with Oneplus 5T, 7T and Huawei P30 some days.
With both OnePlus Phones after some hours this problem occurs https://github.com/stefan-niedermann/nextcloud-deck/issues/680 (it does not matter if background sync is on or off) till I disable battery saving for the deck app like here: https://dontkillmyapp.com/
With the P30 on the other hand I have no problems, here I don't have to disable the battery saving for the deck app.

Maybe we should add a hint on the account creation. Otherwise it seams like the app doesn't work.

**Comment by stefan-niedermann** [comment] 2021-02-14 21:02
Hm. Yeah, we have it mentioned [in our FAQ](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md) and since it affects all apps which use the Single Sign On mechanism, i think we should aim for a more genral solution.

We already have a similar issue here: https://github.com/nextcloud/Android-SingleSignOn/issues/162

**Comment by stefan-niedermann** [comment] 2021-02-15 08:20
Actually, if the `NextcloudApiNotRespondingException` would pop up to the UI, we could display a dialog with a few hints. But it seems like it doesn't get thrown and instead an answer never comes to the UI which causes the spinner to turn forever. @desperateCoder  can you check why / where this particular exception is caught?

**Comment by desperateCoder** [comment] 2021-02-15 11:00
I don't catch this exception at all. It is propagated up to the UI, just as an `OfflineException` or any other `Throwable` would (except special cases like ETag mismatch). I bet you don't trust me, so feel free to have a look at the `SyncHelper` class.

**Comment by stefan-niedermann** [comment] 2021-03-20 17:48
@jakobroehrl i think i found the lost exception (in another context) and now it should be displayed.

Therefore my question, since you have one of those shitty-manufacturer-devices: Would you mind to re-enable the battery "optimizations" (🤮), verify that the sync doesn't work anymore and **then** try [this](https://github.com/stefan-niedermann/nextcloud-deck/suites/2305185756/artifacts/48364039) build?

Expected behavior: It should also **not** work, but show you a dialog with a hint about disabling the battery "optimization" (🤮).

**Comment by stefan-niedermann** [comment] 2021-03-28 19:11
Closing this because i expect the issue to be fixed with `1.15.6` - Feel free to reopen if this is not the case. (I can't test it myself unfortunately because i don't have a device which makes this kind of trouble)

**Closed by stefan-niedermann** 2021-03-28 19:11 UTC
Labels: 🔐 single-sign-on

**Comment by jakobroehrl** [comment] 2021-04-24 11:11
> Therefore my question, since you have one of those shitty-manufacturer-devices: Would you mind to re-enable the battery "optimizations" (🤮), verify that the sync doesn't work anymore and **then** try [this](https://github.com/stefan-niedermann/nextcloud-deck/suites/2305185756/artifacts/48364039) build?


@stefan-niedermann 
Do you have a list of non shitty manufacturers?

**Comment by stefan-niedermann** [comment] 2021-04-24 11:23
Unfortunately nope. They are all shitty in terms of their shipped software :slightly_frowning_face:

Using a custom ROM like Lineage, Graphene, Resurrection Remix etc. seems to be the only way to get an Android like it *should* behave, without any special corners like "We kill each app to advertise with battery optimizations - except Whatsapp, because then people would complain."

Well, the issue is tracked upstream in the Single Sign On repository, since each 3rd party app will have to deal with this issue: https://github.com/nextcloud/Android-SingleSignOn/issues/162 - Deck should display an appropriate message starting with `1.15.6`, so users are at least aware of whats happening.

**Comment by desperateCoder** [comment] 2021-04-24 11:45
Got a brand new Poco f3 here laying in the corner, waiting for a ROM which makes it actually usable...

Nice hardware and stuff, but an UX of a vasectomy. I curse MI UI and anyone who thought it would be a great idea pissing users off with tons of bloatware and virtual walls preventing it to do what the user wants for the sake of financial profit!

/rant
