### ISSUE TITLE
When opening an item from the "pending widget", there should be a way to move the card to a different list

### ISSUE THREAD

**Issue by tomtom** [stefan-niedermann/nextcloud-deck#1525] opened 2023-09-22 12:05 UTC
**Is your feature request related to a problem? Please describe.**
I added the "pending cards" widget to my start screen. When I open a card from the widget, the card is displayed. After modifying the card, I usually want to move the card to a different list. But there is no easy way to achieve this, without having to switch to the deck and the list containing the respective card. This requires that user remember where the card is located.

**Describe the solution you'd like**
In the card view, there should be a button/menu item "Move card".

**Additional context**
I use the current version from the Google App store.

**Comment by stefan-niedermann** [comment] 2023-09-22 12:52
Closing as duplicate of https://github.com/stefan-niedermann/nextcloud-deck/issues/1193 since a <kbd>Move</kbd> operation would belong into this menu.

**Closed by stefan-niedermann** 2023-09-22 12:52 UTC
Labels: enhancement
