### ISSUE TITLE
No autocompletion for usernames with only one character while trying to share board

### ISSUE THREAD

**Issue by smaugilein** [stefan-niedermann/nextcloud-deck#746] opened 2020-11-26 21:33 UTC
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

While using the collaborate feature to share a board it is not possible to pick users whose username consists of single characters. These usernames do not show up in the autocomplete form.

1. Click on "Share board" (german: "Board freigeben")
2. Type in the first and only character of a user whose username consists of a single character only. (In my case: "J")
3. Result: All usernames containing this character show up but the wanted one.

**Expected behavior**

Username (in my case: "J") should show up.

**Screenshots**

![signal-2020-11-26-222919](https://user-images.githubusercontent.com/63549111/100392489-00d18e00-3037-11eb-80ea-f139646b2f44.jpeg)

**Versions**
 - Nextcloud: 20.0.1
 - Nextcloud Deck: 1.2.2
 - Nextcloud Android: 3.14.0
 - Nextcloud Android Deck: 1.12.1

**Smartphone (please complete the following information):**
- Device: LG G6
- Android-Version: 10 (Havoc-OS 3.11)
- App-Store:
  - [ ] Google Play Store (Beta channel)
  - [ ] F-Droid
  - [X] Google Play Store
  - [ ] Huawei AppGallery

**Are you using LDAP?**
- [ ] Yes
- [X] No

**Stacktrace**

**Comment by stefan-niedermann** [comment] 2020-11-27 06:26
Actually not a bug but another intented implementation for a better performance when querying users. Usually the usernames have at least two characters. What happens if you enter the username and press submit on your virtual keyboard?

I will make a branch and test how it feels if we already propose results when the first character has been entered.

**Comment by smaugilein** [comment] 2020-11-27 07:02
The submit button on the keyboard does not submit (or close) the form. It seems necessary to choose a name from the drop-down list to submit data.

**Comment by stefan-niedermann** [comment] 2020-11-27 07:29
Actually only a title is mandatory. It might take a moment to save the stuff (we currently are waiting until everything is safed until we close it - maybe you have a slow device?).

I will hav a look into this issue, thanks for reporting.

**Comment by smaugilein** [comment] 2020-11-27 07:35
Neither the username nor preferences for setting the permissions show up after submitting. The window stays as it is. When choosing an user from the autocomplete list everything works as expected immediately...

**Comment by smaugilein** [comment] 2020-11-27 07:36
(Device is an modded LG G6 with Android 10 running smooth like butter... ;-) )

**Comment by stefan-niedermann** [comment] 2020-11-27 07:41
Aaah, sorry, i was wrong. I thought we were talking about the editing of a card. 😄 

I'm currently busy, but i will have a look as soon as i can.

**Comment by smaugilein** [comment] 2020-11-27 10:15
Take your time! :smiley:

**Comment by stefan-niedermann** [comment] 2020-12-21 18:08
@desperateCoder do you see any potential performance issues when we start querying users already with the first character?

**Comment by desperateCoder** [comment] 2020-12-21 18:32
I can clearly say: it depends. I think in most of the cases it would be totally fine to do this. If used by a bigger corporation or something, the whole thing will blow up and the phone might catch fire. Maybe we can make it depend on the amount of Users in the according `Account`. From UX-perspective, I think you would be also concerned if you have a hundred users there, and every second one has an 'a' in his/her name, you'd have a lot of fun finding the right person in the 50 suggestions. You'd end up entering another character, while your phone would like to ask you if it's a joke to you to look up all that data for nothing.

So I'd propose something like:
* up to 15 users -> threshold 1 char
* up to 35 users -> threshold 2 chars
* above -> 3

Maybe something like this? And as always: we should also consider making it a setting. (knobs! knobs! we need more knobs!)

@smaugilein: How many users do you have on your instance approximately?

**Comment by stefan-niedermann** [comment] 2020-12-21 18:52
@smaugilein can you confirm that the user `J` has access to the board and is not yet assigned to the card? Are you able to assign the user via the web UI?

**Comment by smaugilein** [comment] 2020-12-21 21:21
@desperateCoder Thank you for insights into the technique used. This means that the filtering of the user or user list happens on the device and not via server query? The server can load matching users via database query much faster than the device. I think your app is not the only one with this issue either. How do other programs solve the query?
Regarding the number of users in the installation: I noticed the problem with a small installation of 10+ users.

**Comment by smaugilein** [comment] 2020-12-21 21:21
@stefan-niedermann Yes, "J" has access and can be added normally from the browser UI. As a workaround, I also did this exactly the same way. About the app, of course, it would be more elegant.

**Comment by desperateCoder** [comment] 2020-12-22 12:35
> This means that the filtering of the user or user list happens on the device and not via server query

Exactly.

> The server can load matching users via database query much faster than the device.

Uhm... Wait. Our app also has a database. We query data from the server and save it into out local database. We're almost fully functional without internet connection because of that. As soon as you get an connection, you can sync your local changes up to the server to synchronize both databases. The point, why the server lookup might be faster is, that the server has *slightly* more power (hardware) than our little phones in our pockets. The server won't mind using several MB of RAM since it has plenty of it. But we support devices down to Android 4.4 I think. If all our users would have 2 GB of total RAM, we'd be happy. You got my point?

> How do other programs solve the query?

I can't even tell if other programs have the same problems or just similar problems. I don't think there are too much apps out there, who have to deal with extremely scalable backends, while having full offline capabilities. But no worries, we'll get this working. In our style :smile: 

> I noticed the problem with a small installation of 10+ users.

I hope you didn't get me wrong: Your Nextcloud-instance isn't the problem at all, even if you had 50 users, this would still work, but maybe with some minor loading-lags. We just want to make sure, that our solution fits for all our users, not only the ones with smaller instances.

@stefan-niedermann thankfully did some testing yesterday. He created a user called "J" on his instance and tested it. Somehow it worked for him :unamused:. 

Could you please try the following:
* make sure your local changes are synced to the server
* clear the Storage of the Deck app (only) like described [here](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md#i-have-experienced-an-error)
* open Deck and reimport your account
* try again assigning J

Maybe we have a weird local state or something...

**Comment by desperateCoder** [comment] 2020-12-22 12:46
By the way: this is the query we are using: 

https://github.com/stefan-niedermann/nextcloud-deck/blob/0bb2388916a8f4e4191d20571e09f6a5ab2d3564/app/src/main/java/it/niedermann/nextcloud/deck/persistence/sync/adapters/db/dao/UserDao.java#L47-L55

So there are two rules:
* "J" will not be displayed, if "J" is the owner of the board (-> "J" created it)
* "J" will not be displayed, if the board already has been shared with "J"

What happens, if you try to assign a card to "J" within a board, which won't let you to share it with "J"?

**Comment by stefan-niedermann** [comment] 2021-03-20 18:37
@smaugilein ping :slightly_smiling_face: 

> What happens, if you try to assign a card to "J" within a board, which won't let you to share it with "J"?

**Comment by stefan-niedermann** [comment] 2021-05-26 18:35
Closing due to missing response. In case this is still a valid issue, please feel free to reopen answering @desperateCoder s question [above](https://github.com/stefan-niedermann/nextcloud-deck/issues/746#issuecomment-749523219) considering the rules @desperateCoder mentioned.

The issue [was not reproducible](https://github.com/stefan-niedermann/nextcloud-deck/issues/746#issuecomment-749519127):

> @stefan-niedermann thankfully did some testing yesterday. He created a user called "J" on his instance and tested it. Somehow it worked for him unamused.

**Closed by stefan-niedermann** 2021-05-26 18:35 UTC
Labels: enhancement
