### ISSUE TITLE
Board sort order of Lists

### ISSUE THREAD

**Issue by kuumaur** [stefan-niedermann/nextcloud-deck#1585] opened 2024-02-17 22:02 UTC
### This issue respects the following points:

- [X] I have read the [FAQ](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md)
- [X] I have searched for existing issues
- [X] The issue affects the Deck Android app, neither the [Deck server app](https://github.com/nextcloud/deck/issues/) nor the [Nextcloud Android app](https://github.com/nextcloud/android/issues).

### Describe the bug

In the Nextcloud Deck Web App:
When I create a new Board and add several Lists, often I re-order the lists to my needs.

In the Android Deck App:
The order of the lists in the newly created Board is different from what I did in the Nextcloud Deck Web App.

Not exactly sure, when that will happen, but I often create Boards with lots of Lists inside (>20). I have the impression, that at a certain amount of list entries the sort order gets messed up.

Often, I cant yet descripe a rule, the sort order of the lists is stored/saved. When I now go back to the Nextcloud Deck Web App, the wrong sort order will also show up here.

Apple IPad Air 2 is not affected. App works as expected in regards to the issue with the sort order of the lists.

Version:
Server App: 1.8.8
Android Deck App: 1.23.4

Thanx in advance, Kuumaur

### Deck Android version

1.23.4

### Deck server version

1.8.8

### Nextcloud Android version

3.27.0

### Nextcloud version

28

### Device

Samsung Tab A510 / Google Pixel 6a / Samsung A34 5G / IPad Air 2

### Android Version

11 / 13 / 14

### App Store

- [ ] Google Play Store
- [ ] Google Play Store (Beta channel)
- [X] F-Droid
- [ ] Huawei App Gallery

**Comment by j-lakeman** [comment] 2024-02-20 10:57
Possibly related to https://github.com/stefan-niedermann/nextcloud-deck/issues/1586

**Comment by stefan-niedermann** [comment] 2024-02-20 12:54
@kuumaur are you sure, you *actually* read the FAQ as you commited in the issue?

https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md#known-issues

Closing as duplicate of https://github.com/stefan-niedermann/nextcloud-deck/issues/1586 (as stated by @j-lakeman)

**Closed by stefan-niedermann** 2024-02-20 12:54 UTC
