### ISSUE TITLE
Crash while synchronising

### ISSUE THREAD

**Issue by benjamindahl** [stefan-niedermann/nextcloud-deck#607] opened 2020-07-17 10:19 UTC
While synchronising my deck boards I get following error repeatedly

```
App Version: 1.5.6
App Version Code: 1005006
App Flavor: play

Files App Version Code: 30120190

---

OS Version: 3.18.71-perf-g1c8179f(7f8a6)
OS API Level: 27
Device: montana_n
Manufacturer: motorola
Model (and Product): Moto G (5S) (montana_n)

---

java.lang.RuntimeException: Exception while computing database live data.
	at androidx.room.RoomTrackingLiveData$1.run(RoomTrackingLiveData.java:92)
	at androidx.room.TransactionExecutor$1.run(TransactionExecutor.java:45)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. # Open Cursors=1 (# cursors opened by this proc=1)
	at android.database.CursorWindow.<init>(CursorWindow.java:108)
	at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:138)
	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:220)
	at android.database.AbstractCursor.moveToNext(AbstractCursor.java:269)
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.dao.CardDao_Impl.__fetchRelationshipLabelAsitNiedermannNextcloudDeckModelLabel(CardDao_Impl.java:3659)
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.dao.CardDao_Impl.access$100(CardDao_Impl.java:34)
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.dao.CardDao_Impl$6.call(CardDao_Impl.java:1391)
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.dao.CardDao_Impl$6.call(CardDao_Impl.java:1316)
	at androidx.room.RoomTrackingLiveData$1.run(RoomTrackingLiveData.java:90)
	... 4 more

```

**Comment by stefan-niedermann** [comment] 2020-07-17 10:42
Thank you for the report. This is a duplicate of #515.

If you have any further information, like whether
- this only happens with one account
- this happens each single time
- you can create / edit cards and they get syned
- this only happens (or happens not?) when you pull down to refresh

please post them in #515.

**Closed by stefan-niedermann** 2020-07-17 10:42 UTC
