### ISSUE TITLE
Order of lists does not sync from desktop

### ISSUE THREAD

**Issue by deadwax** [stefan-niedermann/nextcloud-deck#1249] opened 2022-04-08 00:47 UTC
I'm using Deck in a way in which the order of lists is important.  After making changes in the order of lists on the desktop the changes do not then sync to the Android client

1. Create a board and populate it with some lists on the desktop
2. Open the board on the android app
3. Edit the board on the desktop, changing the order of lists
4. Open android app and find that the lists are still in the old order.  Pulling to refresh does not help.

Versions
 - Nextcloud: 23.0.3
 - Nextcloud Deck: 1.6.1
 - Nextcloud Android: 3.19.1
 - Nextcloud Android Deck: 1.20.0 F-Droid

Smartphone
- Device: Galaxy S5
- Android-Version: 10

**Comment by stefan-niedermann** [comment] 2022-04-08 04:34
Hey @deadwax 

i assume that this is caused by a [known bug](https://github.com/nextcloud/deck/issues/2866) in the (not by us developed) Deck server app.

To verify can you please open the settings in the Deck Android app (you can find them at the bottom of the sidebar) and **ttemporarily** disable `ETag`s? The next synchronization will take *very* long (up to multiple minhtes, depending on the amount of data on your Deck server app).
Please check whether the list position has been updated and then enable `ETag` support again.

**Comment by stefan-niedermann** [comment] 2022-04-16 08:25
Closing due to missing feedback. Please feel free to reopen if the aforementioned steps did not work.

**Closed by stefan-niedermann** 2022-04-16 08:25 UTC

**Comment by deadwax** [comment] 2022-04-17 23:14
Apologies, it has been a very busy few weeks.

Yes, disabling etags fixed the issue.
