### ISSUE TITLE
Deck crashed due to color marks changing

### ISSUE THREAD

**Issue by neerro** [stefan-niedermann/nextcloud-deck#1015] opened 2021-06-12 13:02 UTC
**Describe the bug**
When I try add new or change existing color marks, I can observe Deck crashing.

1. When I open card or deck menu
2. Click on mark field and try to add a new one mark or add mark, or change or delete. 
2.1. Click on deck menu and try to add new mark, or change color of existing mark, or change name or something else. 
3. See error (report of full crash attached in the end issue). And then app closed.

**Expected behavior**

**Screenshots**
No

**Versions**
    Nextcloud: latest
    Nextcloud Deck: latest
    Nextcloud Android: latest
    Nextcloud Android Deck: latest

**Smartphone (please complete the following information):**
    Device: Honor 10 lite
    Android-Version: 10
- App-Store:
  - [x] Google Play Store
  - [ ] Google Play Store (Beta channel)
  - [ ] F-Droid
  - [ ] Huawei AppGallery

**Stacktrace**

```
Full Crash:

App Version: 1.18.3
App Version Code: 1018003
App Flavor: play

Files App Version Code: 30160190

---

OS Version: 4.14.116(10.0.0.221C10)
OS API Level: 29
Device: HWHRY-H
Manufacturer: HUAWEI
Model (and Product): HRY-LX1 (HRY-LX1RU)

---

java.lang.IllegalStateException: Fragment ManageLabelsDialogFragment{e19908f} (67bfeb54-4472-4080-88e3-067ec1533e3a) not attached to an activity.
	at androidx.fragment.app.Fragment.requireActivity(Fragment.java:928)
	at it.niedermann.nextcloud.deck.ui.board.managelabels.ManageLabelsDialogFragment.toastFromThread(ManageLabelsDialogFragment.java:194)
	at it.niedermann.nextcloud.deck.ui.board.managelabels.ManageLabelsDialogFragment.access$000(ManageLabelsDialogFragment.java:33)
	at it.niedermann.nextcloud.deck.ui.board.managelabels.ManageLabelsDialogFragment$3.onError(ManageLabelsDialogFragment.java:183)
	at it.niedermann.nextcloud.deck.api.ResponseCallback$1.onError(ResponseCallback.java:76)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.DataPropagationHelper$2.lambda$onError$1(DataPropagationHelper.java:97)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.-$$Lambda$DataPropagationHelper$2$IH089WI93lgRHdgt4VwjDwmfT9U.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:929)

```

**Comment by stefan-niedermann** [comment] 2021-06-17 15:02
A few assumptions since the terminology you used is not clear to me.
Just correct me if i misunderstood something:

- > color marks changing

  I assume that you mean "tag" when you write "mark".
- > When I open card or deck menu

  I assume you opened the sidebar and clicked on the three dots menu of any board.
  I assume you chose "Manage tags" in this menu and then the "Manage tags" dialog appeared. (Since colors of tags can not be changed within a card, as you mentioned in step 2.1)

---

1. Are not able to reproduce this crash every time you are performing the steps to reproduce?
2. Is it possible, that you switched from Deck to another app or put Deck into the background and returned to it later to continue editing?

**Comment by neerro** [comment] 2021-06-17 19:45
>  I assume that you mean "tag" when you write "mark".

Definitely yes I've been checked and in English version it's named as tags.  
     
>  I assume you opened the sidebar and clicked on the three dots menu of any board.

Yes, correct.

>   I assume you chose "Manage tags" in this menu and then the "Manage tags" dialog appeared. (Since colors of tags can not be changed within a card, as you mentioned in step 2.1)

1. Open sidebar menu
2. Click on three dots of any deck
3. Click on manage tags
4. Choose one of tags and click on pencil for editing
5. Then the color can be changed by clicking on the rounded colored mark.

>  1. Are not able to reproduce this crash every time you are performing the steps to reproduce?

In my observation, that crash could not be appeared every time when I try to reproduce it. Those crash were appeared from time to time, not permanently.

>  2. Is it possible, that you switched from Deck to another app or put Deck into the background and returned to it later to continue editing?

As I remember - not. In that period I worked in Deck only and didn't switch between another apps.

**Comment by stefan-niedermann** [comment] 2021-07-26 08:40
We analyzed this issue and are aware of the problem. Unfortunately we haven't been able to find the root cause of this yet. We therefore [put a bounty](https://help.nextcloud.com/t/looking-for-an-android-developer-who-can-solve-a-bug-in-nextcloud-deck/119482) on this issue for a freelancer who is able to help fixing this issue and keep looking for solutions to this platform related problem...

Closing this issue as a duplicate of #478 to keep all information regarding it in one place. Feel free to subscribe tk #478 to get notified if new infos arrive.

**Closed by stefan-niedermann** 2021-07-26 08:40 UTC
