### ISSUE TITLE
tag assignment misbehaving on server app

### ISSUE THREAD

**Issue by dberardo** [stefan-niedermann/nextcloud-deck#649] opened 2020-08-09 13:50 UTC
i am surprised this issue hasn't been reported yet:

adding tags on a card in the Android deck app results in various duplicates of the same tag on the deck app in the nextcloud server.

i am running the latest nextcloud + deck combination both on Android and webhosted server.

steps to reproduce:
1- add an existing tag on an existing card on Android
2- navigate in the same board on server and check the mess up

**Comment by desperateCoder** [comment] 2020-08-09 13:54
Duplicate of #644

**Comment by dberardo** [comment] 2020-08-09 13:55
this issue might link to https://github.com/stefan-niedermann/nextcloud-deck/issues/644#issue-672837168

**Closed by desperateCoder** 2020-08-09 13:54 UTC

**Comment by desperateCoder** [comment] 2020-08-09 14:01
If you wonder, this is what actually happens: https://github.com/stefan-niedermann/nextcloud-deck/issues/644#issuecomment-670434233

Sorry for the inconvenience, there is an error in a library we use to communicate with your server... I already fixed it and hope it gets released soon

**Comment by desperateCoder** [comment] 2020-08-09 15:05
Fyi: we just released the fixes, next update will get rid of the issues, sorry for the label-spamming tho :unamused:
