### ISSUE TITLE
Unable to add Deck Stack List Widget to android home screen.

### ISSUE THREAD

**Issue by FHFS** [stefan-niedermann/nextcloud-deck#726] opened 2020-11-12 21:19 UTC
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

Unable to add Deck Stack List Widget to android home screen.

**To reproduce**
Issue is reproducible with an account from [try.nextcloud.com](https://try.nextcloud.com):
- [x] Yes
- [ ] No

1. Go to 'Android Homescreen'
2. Hold on 'Homescreen to modify, and add a widget'
3. Scroll down to 'Nextcloud Deck'
4. Add the widget "List 3x2" by tapping on it, or dragging it to an empty space on your homescreen.
5. In the "Add stack widget" keep defaults or any other stack/list combination.
6. Press the "Add" button.
7. Widget not present on homescreen. No error or such.

**Expected behavior**

I expect the widget to appear on the homescreen.

**Screenshots**

**Versions**
 - Nextcloud: 20.0.1-1
 - Nextcloud Deck: 1.1.2
 - Nextcloud Android: 3.13.1
 - Nextcloud Android Deck: 1.11.1

**Smartphone (please complete the following information):**
- Device: Doogee S68
- Android-Version: 9.0
- App-Store:
  - [ ] Google Play Store
  - [ ] Google Play Store (Beta channel)
  - [x] F-Droid
  - [ ] Huawei AppGallery

**Are you using LDAP?**
- [ ] Yes
- [x] No

**Stacktrace**

**Comment by stefan-niedermann** [comment] 2020-11-13 09:10
Hm. Can you please try to
- Completely uninstall and reinstall the app
- Import your account from the Files app
- Disable battery optimizations
- Restart the phone

Without any error message we have no chance to fix this issue, i can't reproduce it. @desperateCoder are you able to reproduce it?

@FHFS maybe you can install any Logcat reader from F-Droid and check whether you are able to fetch any logs which might be useful.

**Comment by FHFS** [comment] 2020-11-16 11:10
@stefan-niedermann 
I've tried your suggestion, but that gives the same result.
I've just installed a logcat reader. I will try to get some logs soon.

**Comment by FHFS** [comment] 2020-11-16 19:55
[Logcat output @pastebin](https://pastebin.com/AVjpQyCQ)
Hope this helps, let me know if I can do anything else

**Comment by stefan-niedermann** [comment] 2020-11-16 20:22
Thanks so far! I'll have a look whether we can find a useful hint in it.

Are you using a custom ROM or a 3rd party launcher or something like this?

**Comment by stefan-niedermann** [comment] 2020-11-16 20:23
And also:

- Doesn't the widget appear at all or is the widget there but not showing any cards?
- Is the Single Card Widget working for you without any issues?

**Comment by FHFS** [comment] 2020-11-16 22:10
@stefan-niedermann 
- Thanks so far! I'll have a look whether we can find a useful hint in it.
  - No, thank you! =D
- Are you using a custom ROM or a 3rd party launcher or something like this?
  - **Yes, poco launcher, I just tested it. It does work in the normal launcher. Should I close the issue?**
- Doesn't the widget appear at all or is the widget there but not showing any cards?
  - nothing appears in poco launcher
- Is the Single Card Widget working for you without any issues?
  - this is working perfectly

**Comment by stefan-niedermann** [comment] 2020-11-16 22:19
> Yes, poco launcher, I just tested it. It does work in the normal launcher. Should I close the issue?

Well, that's a good question. We have tested the widget in Trebuchet Launcher, Pixel Launcher and Lawnchair. If it just isn't working in Poco Launcher, i guess it is a bug there. Since it is proprietary as far as i know, i can't check it unfortunately.

It would definitely make sense to report this issue upstream - i think it's from Xiaomi, right?

**Comment by stefan-niedermann** [comment] 2020-11-18 11:59
Closing this as an upstream bug - @FHFS it would be great if you could keep us updated (and post a link to an issue, if you report it upstream). :slightly_smiling_face:

**Closed by stefan-niedermann** 2020-11-18 11:59 UTC
