### ISSUE TITLE
Wrong time

### ISSUE THREAD

**Issue by rad-li** [stefan-niedermann/nextcloud-deck#731] opened 2020-11-16 17:41 UTC
The execution time is displayed incorrectly. This happens if the local time differs from UTC. In all other cases, there is no error. In my case, the difference is +3 hours. WebUI.

 - Nextcloud: 20.0.1
 - Nextcloud Deck: 1.2.0
![Снимок экрана_2020-11-16_20-38-08](https://user-images.githubusercontent.com/74559754/99287963-ff8cae00-284b-11eb-976c-baba67ec46f1.png)
![Снимок экрана_2020-11-16_20-38-33](https://user-images.githubusercontent.com/74559754/99287971-01567180-284c-11eb-8054-18ea652f97b4.png)

**Comment by stefan-niedermann** [comment] 2020-11-16 17:49
Dear @rad-li 

if i understand you correctly the time in the Web UI is displayed incorrect.

But is it displayed correctly in the Android App?

Because this repository is only for issues in the Android App.
You can open bug reports for the Web UI in [this repository](https://github.com/nextcloud/deck/issues/new?template=Bug_report.md).

**Comment by rad-li** [comment] 2020-11-16 18:32
I haven't used the Android app before, but now I've installed it and checked it out. The app also has this error.  I think the error is in the server side.

I opened error reports in https://github.com/nextcloud/deck/issues/2565

**Comment by stefan-niedermann** [comment] 2021-07-12 07:45
Since this issue also appears without using the Deck Android app, we assume that the root cause is in the server.

We'll close this issue therefore in favor of https://github.com/nextcloud/deck/issues/2565 - feel free to reopen if the issue persists in the Deck Android app after the corresponding server issue has been fixed.

**Closed by stefan-niedermann** 2021-07-12 07:45 UTC
Labels: 🖥 server

**Comment by desperateCoder** [comment] 2021-07-12 08:10
https://github.com/nextcloud/deck/issues/2565 is closed as a duplicate of https://github.com/nextcloud/deck/issues/2276

**Comment by stefan-niedermann** [comment] 2021-07-12 08:11
Thanks for the addition, i had the wrong issue in the clipboard :)
