### ISSUE TITLE
sync fail after upgrading to 1.9.2

### ISSUE THREAD

**Issue by Emporea** [stefan-niedermann/nextcloud-deck#628] opened 2020-07-26 11:41 UTC
```
App Version: 1.9.2
App Version Code: 1009002
App Flavor: fdroid

Deck Server Version: 1.0.5

Files App Version Code: 30120190

---

OS Version: 4.9.229(eng.rpbota.20200705.125217)
OS API Level: 29
Device: starlte
Manufacturer: samsung
Model (and Product): SM-G960F (starltexx)

---

java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Long it.niedermann.nextcloud.deck.model.interfaces.IRemoteEntity.getLocalId()' on a null object reference
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.AbstractSyncDataProvider.findDelta(AbstractSyncDataProvider.java:44)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.CardDataProvider.handleDeletes(CardDataProvider.java:284)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.SyncHelper$1.onResponse(SyncHelper.java:66)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.SyncHelper$1.onResponse(SyncHelper.java:34)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.CardDataProvider$1.onResponse(CardDataProvider.java:53)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.CardDataProvider$1.onResponse(CardDataProvider.java:48)
	at it.niedermann.nextcloud.deck.api.RequestHelper$ResponseConsumer.accept(RequestHelper.java:62)
	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onNext(ObservableSubscribeOn.java:58)
	at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:62)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher$PublisherSubscriber.onNext(ObservableFromPublisher.java:56)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$NextcloudAPI(NextcloudAPI.java:98)
	at com.nextcloud.android.sso.api.-$$Lambda$NextcloudAPI$HPzOdi9LOc_f-wA9GNnhc9LKQSM.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```

**Comment by stefan-niedermann** [comment] 2020-07-26 11:53
@Emporea are you using Nextcloud Projects via the Web UI?

**Comment by desperateCoder** [comment] 2020-07-26 12:07
@stefan-niedermann I think I know why you are asking this, but I am pretty confident, this isn't the cause. I'd suspect a hickup or just another exotic constellation.

@Emporea does it keep failing or does that only happen from time to time?

**Comment by desperateCoder** [comment] 2020-07-26 12:43
@Emporea I honestly can't tell how this could happen, very weird. But I think I have a quite straight solution for this, which souldn't break anything else. 
Please have a look at the following APK: [> click <](https://github.com/stefan-niedermann/nextcloud-deck/suites/965492204/artifacts/12196212)
It is safe to install it beside your current version. Please try to work with that and tell us, if you encounter any problems with this version.

**Comment by Emporea** [comment] 2020-07-26 16:10
Ok, so I installed the debug apk and it hasn't happen with this app. With the regular app from F-Droid it doesn't occur everytime when I sync, and new items will get synced even when the error does appear, which is weird. It's hard to reproduce the error, it seems to be random ( obviously not, there must be a reason, but I do not change any behavior on purpose and sometimes it happens, sometimes not.)

One thing is constant tho, the refresh circle in the F-Droid  version 1.9.2 wont disappear. It keeps spinning forever.

**Comment by desperateCoder** [comment] 2020-07-26 16:21
Ok, thanks for trying out @Emporea! So, would you say the debug version solves the issue for you? Since I "fixed" that on the master branch, this would be included in the next upcoming version. To be honest, I have no clue why this happens. But on the other hand: We have thousands of NC instances on thousands of different servers with different configurations, with an app running on thousands of different devices. Who can know, what constellations out there? We try to make our app as robust as we can, so sorry for the inconveniences. If this works for you, it most likely will for a huge bunch of others, so if you have any other issues, please tell us! If you are happy with this solution, we will happily ship this in the next version.

**Comment by stefan-niedermann** [comment] 2020-07-26 16:57
Will be shipped in `1.9.4`. Thanks for reporting.

**Comment by Emporea** [comment] 2020-07-26 17:38
Yeah, it seems like this problem got fixed in the dev app you provided. Thank you for your very fast support, even on a sunday!

**Comment by stefan-niedermann** [comment] 2020-07-26 17:42
You're welcome 😊 Have a nice weekend and much fun with the app! Don't hesitate to open a new issue if you are stumbling about another bug or have a feature request.

Thank you for your testing help! 🙂 

Regards

**Comment by stefan-niedermann** [comment] 2020-07-26 17:43
oh, @desperateCoder you fixed the bug, maybe you want to close the issue? 😄

**Comment by desperateCoder** [comment] 2020-07-26 17:58
Nope, honor is to @Emporea. Whoever finds it, may keep it! 😆 

@Emporea feel free to close! ❤️

**Closed** 2020-07-26 18:07 UTC
