### ISSUE TITLE
Searching feature in decks

### ISSUE THREAD

**Issue by neerro** [stefan-niedermann/nextcloud-deck#847] opened 2021-02-21 21:53 UTC
It would be great if you'll add to Android  Deck app a searching feature whether in deck itself or in all decks in common.

**Comment by stefan-niedermann** [comment] 2021-02-21 22:05
Please use the search function before opening new issues.

Duplicate of https://github.com/stefan-niedermann/nextcloud-deck/issues/630

**Closed by stefan-niedermann** 2021-02-21 22:05 UTC
Labels: enhancement

**Comment by neerro** [comment] 2021-02-25 14:42
Of course I tried search the issue/enhancement before I've created the topic but unfortunately I found nothing. I think that I incorrect used the GitHub search.
