### ISSUE TITLE
Android 9. Integer cannot be cast to Long

### ISSUE THREAD

**Issue by tomeinstein** [stefan-niedermann/nextcloud-deck#99] opened 2019-06-23 07:04 UTC
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
	at android.app.SharedPreferencesImpl.getLong(SharedPreferencesImpl.java:310)
	at it.niedermann.nextcloud.deck.ui.DrawerActivity.lambda$null$2$DrawerActivity(DrawerActivity.java:133)
	at it.niedermann.nextcloud.deck.ui.-$$Lambda$DrawerActivity$bCpozhu_AVJ_lTe_ch2lk50NFgg.onChanged(Unknown Source:4)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:113)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:131)
	at androidx.lifecycle.LiveData.setValue(LiveData.java:289)
	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:33)
	at androidx.lifecycle.LiveData$1.run(LiveData.java:91)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6694)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by Aquariu** [comment] 2019-06-25 16:48
Had this issue also when updateding to 0.3.
Completely remove the app and reinstall fixed it.

**Comment by stefan-niedermann** [comment] 2019-06-25 17:52
@tomeinstein can you reproduce this issue while the app is running? If not, please don't be mad, but i will close this issue, because we consider each "Update" currently breaking change that will at least require a complete deletion of the app storage.

I remember the code part that has changed (we switched a shared preferences item from `int` to `long`, so this exception is understandable from my PoV and we should ignore it as long as we are in "non-productive" mode.

But thanks of course for reporting. Please keep filing bugs and issues and don't be disappointed that we consider some bugs as not as critical as you would currently do from a users perspective :)

**Closed by stefan-niedermann** 2019-06-25 17:52 UTC
