### ISSUE TITLE
JsonArray cannot be cast to JsonObject

### ISSUE THREAD

**Issue by sh2515** [stefan-niedermann/nextcloud-deck#443] opened 2020-05-01 05:52 UTC
```
App Version: 0.6.0
App Version Code: 6000
App Flavor: fdroid

Files App Version Code: 30110190

---

OS Version: 4.4.153-perf+(00WW_1_400_SP01)
OS API Level: 28
Device: DDV_sprout
Manufacturer: HMD Global
Model (and Product): Nokia 7.2 (Daredevil_00EEA)

---

java.lang.RuntimeException: Exception while computing database live data.
	at androidx.room.RoomTrackingLiveData$1.run(RoomTrackingLiveData.java:92)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: android.database.sqlite.SQLiteDatabaseCorruptException: database disk image is malformed (code 11 SQLITE_CORRUPT)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:859)
	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:149)
	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:137)
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:220)
	at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:259)
	at androidx.room.RoomOpenHelper.checkIdentity(RoomOpenHelper.java:147)
	at androidx.room.RoomOpenHelper.onOpen(RoomOpenHelper.java:135)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onOpen(FrameworkSQLiteOpenHelper.java:195)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:409)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:298)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:145)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:106)
	at androidx.room.RoomDatabase.inTransaction(RoomDatabase.java:476)
	at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:281)
	at androidx.room.RoomDatabase.query(RoomDatabase.java:324)
	at androidx.room.util.DBUtil.query(DBUtil.java:83)
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.dao.AccountDao_Impl$5.call(AccountDao_Impl.java:220)
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.dao.AccountDao_Impl$5.call(AccountDao_Impl.java:217)
	at androidx.room.RoomTrackingLiveData$1.run(RoomTrackingLiveData.java:90)
	... 3 more

```

If you need anymore details let me know.

**Comment by stefan-niedermann** [comment] 2020-05-01 06:52
Hi @sh2515,

yes, we will need more information to tackle this issue i guess.

please describe the exact steps you did to get this error message. Did you freshly install it? Did you use it for a while? Did you perform an update lately? Did you create a tag or a card or did?

Can you reproduce this issue?

Have you tried to de- and reinstall the app? Does it happen again?

I also see you used an old version `0.6.0` - Have you tried the latest released version `1.0.0`?

@desperateCoder Would it be helpful for you to treat `SQLiteException`-screens special? e.g. dumping the database or trying to print any information from the database?

**Comment by stefan-niedermann** [comment] 2020-05-01 09:22
@sh2515 can you try to clear the storage of the app (Android settings → Apps → Nextcloud Deck → Storage → Clear storage), install version `1.0.0` from F-Droid and try it again?

**Comment by desperateCoder** [comment] 2020-05-01 09:42
> @desperateCoder Would it be helpful for you to treat SQLiteException-screens special? e.g. dumping the database or trying to print any information from the database?

Anything i could do something about is printed in the exception-screen, i don't think it would make any sense trying to gather more information, since the error could be caused by pretty much anything. Dumping the whole thing could actually help, but i guess not many users use nextcloud just to dump their private data to random guys on the internet? :grin: 

In most cases i think just reinstalling the app will do it just fine. Not nice, for sure, but i have no clue how to handle this without violating the privacy of our users.

**Comment by stefan-niedermann** [comment] 2020-05-04 17:23
@sh2515 please feel free to reopen this issue if it still occurs after clearing the storage of both apps, Nextcloud Android and Nextcloud Deck Android, and provide the [requested information](https://github.com/stefan-niedermann/nextcloud-deck/issues/443#issuecomment-622274153).

Regards

**Comment by sh2515** [comment] 2020-05-07 15:55
I tried: 
1  reinstalled the app
2. Deleted the data and cache
3. Updated the app to the one of Google play
![Screenshot_20200507-165048](https://user-images.githubusercontent.com/5173444/81316236-41f65680-9083-11ea-9a31-a8c9819e0785.png)
I get the attached error. Not sure what is wrong with it.

Let me know if you need the information sending through as you describe above.

**Comment by stefan-niedermann** [comment] 2020-05-07 16:06
Which version of the Deck server app are you using exactly, please?

**Comment by stefan-niedermann** [comment] 2020-05-08 10:33
Ping @sh2515

**Comment by stefan-niedermann** [comment] 2020-05-09 13:30
@sh2515 we need to know the exact server version. There was a bug in a beta version of the server which can cause this behavior.

**Comment by sh2515** [comment] 2020-05-10 17:54
I don't think it's a bug in your app, I think it's my phone. I am having lots of issues with other apps also after buying a new phone. Sorry.On 9 May 2020 2:30 pm, Niedermann IT-Dienstleistungen <notifications@github.com> wrote:
@sh2515 we need to know the exact server version. There was a bug in a beta version of the server which can cause this behavior.

**Comment by stefan-niedermann** [comment] 2020-05-10 18:20
Thank you for the feedback. In this case i will close the issue. Feel free to reopen or create a new issue in case you think it's about the app and you can provide more information :slightly_smiling_face: 

Good luck with your device

**Closed by stefan-niedermann** 2020-05-10 18:20 UTC
Labels: bug
