### ISSUE TITLE
Do not moving deck lists (to the left/right) in Android app which were created in server app

### ISSUE THREAD

**Issue by neerro** [stefan-niedermann/nextcloud-deck#977] opened 2021-05-13 00:02 UTC
**Describe the bug**
So if I get try to move lists in any deck which were created in server deck app it could not be possible neither left nor right. Lists were created in Android app has not such issues.

1. In one of deck select list
2. Click on vertical dots in right corner
3. Click on move to the right or left
4. And nothing's the matter (if list was created on server)

**Expected behavior**
Correct behavior as moving lists to the left or right side and not depended on where it were created in Nextcloud server or android app. 

**Versions**
 - Nextcloud: 20.0.0
 - Nextcloud Deck: 1.4.2
 - Nextcloud Android: 3.16.0
 - Nextcloud Android Deck: 1.18.2

**Smartphone (please complete the following information):**
- Device: Honor Lite 10
- Android-Version: 10
- App-Store:
  - [x] Google Play Store
  - [ ] Google Play Store (Beta channel)
  - [ ] F-Droid
  - [ ] Huawei AppGallery

**P/S.**
---
@stefan-niedermann is that enough information for you, or should I complete more to prevent closing my bug report by you as it was done before?

**Comment by stefan-niedermann** [comment] 2021-05-13 06:09
Yes. That's how it works. Seems to be related to #889. Are you sure that there is a difference between lists which are created on the server app vs. list which are created on the Android app or might it have been a coincidence? Can you try a few lists?

**Comment by stefan-niedermann** [comment] 2021-05-13 07:58
@desperateCoder maybe reordering of lists is the problem? Do we have that implemented the same way as in cards? If server apps create orders like

- 1000
- 2000
- 3000

and the Android app creates new lists with

- 1000
- 1001
- 2000
- 3000

and reordering just in- or decrements.....?

**Comment by desperateCoder** [comment] 2021-05-13 12:11
@stefan-niedermann well, that's wild. Just created a new board and a couple of stacks via Web-UI. I created four stacks, now look at this:

![grafik](https://user-images.githubusercontent.com/6911132/118122492-399dcd80-b3f3-11eb-9cb1-2ed27d1eb1e6.png)

Now here's what your implementation does:

https://github.com/stefan-niedermann/nextcloud-deck/blob/c46e898a04f71cdeeb3151faa7f33657d4bec192/app/src/main/java/it/niedermann/nextcloud/deck/persistence/sync/SyncManager.java#L886-L890

So I'd say we can easily fix this with a little extra logic, let me handle this.

@neerro Sorry that we have to be that strict regarding the issue template, but we're doing this because of our experience. Look: Everyone has his/her view on a topic. Humans tend to assume, the other side has the same amount of knowledge as themselves, which is in fact wrong. We already had quite a lot of issues opened in this repository, currently yours is Nr. 977 and we had a shit-load of misunderstandings and incomplete information. We wasted so much time asking the same questions over and over again for each issue. At one point we came up with the issue template, which saves us so much time, you can't imagine. So thanks for filling it out this time. I hope you see, that we aren't mad or evil, but really trying to help you. All we want for that is a little bit of respect for the rules here and some cooperation.

I'm pretty sure we'll fix this until the next release. Would you mind testing the fix to make sure it works before we release it @neerro?

**Comment by desperateCoder** [comment] 2021-05-13 15:10
@neerro (and @birefringence because of issue #889):

I think I fixed all known list / stack moving issues in the following APK:
[Download and enjoy  (̿▀̿ ̿Ĺ̯̿̿▀̿ ̿)̄](https://github.com/stefan-niedermann/nextcloud-deck/suites/2735093919/artifacts/60393445)

Not only it should work flawlessly now, it even repairs broken orders on the fly. If you could confirm it's working, the fix will be delivered in the next release.

@neerro The link above is a special DEV build of our app, you can safely install it beside your current app and use it parallel, as @birefringence has done several times (thanks for that!). Just connect the DEV app to your instance and play around a little moving the lists as much as you want, until you can say if it works or not.

Looking forward to your feedback!

**Comment by birefringence** [comment] 2021-05-13 20:36
This fixes #889 (and I really think it's the same issue).

**Comment by stefan-niedermann** [comment] 2021-05-14 06:23
Very nice, and it also explains why i haven't been able to reproduce #889 🙂

**Comment by stefan-niedermann** [comment] 2021-05-14 15:25
Fix will be in version `1.18.3`, thank you for the report.

**Closed** 2021-05-14 15:25 UTC

**Comment by neerro** [comment] 2021-05-17 19:32
Hi guys!
I'm so sorry, but I'm a bit was busy and had late to your conversation.

> Are you sure that there is a difference between lists which are created on the server app vs. list which are created on the Android app or might it have been a coincidence?

Yes, It's definitely correct, there are difference between created lists on server app and Android that works accuracy as I described earlier.

> Would you mind testing the fix to make sure it works before we release it @neerro?

I'm afraid it's no longer actual ;)

> Sorry that we have to be that strict regarding the issue template, but we're doing this because of our experience. Look: Everyone has his/her view on a topic. Humans tend to assume, the other side has the same amount of knowledge as themselves, which is in fact wrong. We already had quite a lot of issues opened in this repository, currently yours is Nr. 977 and we had a shit-load of misunderstandings and incomplete information. We wasted so much time asking the same questions over and over again for each issue. At one point we came up with the issue template, which saves us so much time, you can't imagine. So thanks for filling it out this time. I hope you see, that we aren't mad or evil, but really trying to help you. All we want for that is a little bit of respect for the rules here and some cooperation.

Regarding this - it's OK, never mind. Of course, I was a little distracted by @stefan-niedermann reaction, but as I said it's OK. 

> Would you mind testing the fix to make sure it works before we release it @neerro?

If it still topically of course I can taste it with further feedback.

**Comment by stefan-niedermann** [comment] 2021-05-17 19:48
Nah, just reopen (or open a new) issue in case it occurs with `1.18.3` or later 👍
