### ISSUE TITLE
Crash after login

### ISSUE THREAD

**Issue by Jiack214** [stefan-niedermann/nextcloud-deck#57] opened 2019-03-17 10:13 UTC
Android version: 8.1.0 (LineageOS)
Nextcloud server: selfhosted v15.0.5
Nextcloud Deck: last version
Nextcloud Android: 3.5.0 RC2 (f-droid)

I just successfully build this app (last commit: 7cfcebd) but it crashes immediately after login.

`FATAL EXCEPTION: main
Process: it.niedermann.nextcloud.deck, PID: 16661
java.lang.NullPointerException: Attempt to invoke virtual method 'void it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.AbstractSyncDataProvider.childDone(it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.AbstractSyncDataProvider, it.niedermann.nextcloud.deck.api.IResponseCallback, boolean)' on a null object reference
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.AbstractSyncDataProvider.onError(AbstractSyncDataProvider.java:78)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.SyncHelper$1.onError(SyncHelper.java:66)
	at it.niedermann.nextcloud.deck.api.RequestHelper$ResponseConsumer$1.lambda$accept$0(RequestHelper.java:46)
	at it.niedermann.nextcloud.deck.api.-$$Lambda$RequestHelper$ResponseConsumer$1$pdGUKOypjSaz8W9wp-deyLX5HGQ.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)`

**Comment by desperateCoder** [comment] 2019-03-17 10:38
Hold on, i'll have a look at this one...

**Comment by desperateCoder** [comment] 2019-03-17 10:47
@Jiack214 the following commit should fix the NullPointerException: https://github.com/stefan-niedermann/nextcloud-deck/commit/1cba8fe0a62956789ca5a45ea31cccf22ccb72c5

But i'm afraid the real problem could persist. At least one call to the server seems to fail, but on my machine it doesn't. Please pull the master and try again. If it fails, i'd be glad to get a stacktrace.

Thanks for testing!

**Comment by desperateCoder** [comment] 2019-03-17 10:56
@Jiack214 I guess i know where the Problem is: at this week there was the Nextcloud hackweek, where i sat right beside @juliushaertl, who wrote the Nextcloud server app. We fixed a bunch of issues, but the fixes aren't released yet. There is a build you can put on your server, which includes the fixes: 
https://cloud.bitgrid.net/s/steo9XtYnYMyjwH

After patching the problems should be solved. If not, please provide a stacktrace of the Android app.

Best regards!

**Comment by Jiack214** [comment] 2019-03-17 12:46
Thank you so much.
The last commit prevents crash but app does not show any board.
Do you know when fixes are you going to be released? I'm not admin, so I prefer to wait the official update if it's soon.

**Comment by desperateCoder** [comment] 2019-03-17 13:14
@Jiack214 actually I don't. But soon Nextcloud 16 will be released. @juliushaertl can you tell us more?

**Comment by desperateCoder** [comment] 2019-03-17 14:59
@Jiack214 for now you could try the following state: https://github.com/stefan-niedermann/nextcloud-deck/commit/a7301357bb0e4df1934585189674d238ef5ace7b

As far as i remember, this one doesn't rely on the mentioned changes, while still pretty up to date. Just give it a try... good luck!

**Comment by AndyScherzinger** [comment] 2019-03-17 17:06
@desperateCoder just tried the latest master and I don't get any cards rendered noch columns (not a single stack trace in the logcat). Fetching form server seems to work fine (no logcat issues) but I only see the boards (with their title) and noting else :/

**Comment by tobiasKaminsky** [comment] 2019-03-18 11:40
Same for me as @AndyScherzinger described.
Furthermore I can see which calls are piped through NC files app. It seems that only /nc/index.php/apps/deck/api/v1.0/boards is used, but no other call.
I would at least expect boards/{boardId}/stacks" (getStacks())

**Comment by desperateCoder** [comment] 2019-03-18 11:46
Yeah, because the stacks aren't delivered by the API on the currently released NC-deck version. Do you really have the current master of the server app running? Can you provide the json of the boards call? (See Android app logs)

**Comment by juliushaertl** [comment] 2019-03-21 10:12
@Jiack214 I plan to to a beta release early next week. The stable release will be out before Nextcloud 16 is being released.

**Comment by desperateCoder** [comment] 2019-03-21 10:28
@juliushaertl will the release also contain the labels in the boards call?

**Comment by juliushaertl** [comment] 2019-03-21 10:29
@desperateCoder You mean the stacks we added last week?

**Comment by juliushaertl** [comment] 2019-03-21 10:30
The fix we did was merged for the next release: https://github.com/nextcloud/deck/pull/939

**Comment by desperateCoder** [comment] 2019-03-21 10:31
@juliushaertl nope, I assume the stacks will be released. I'd need the labels too, as i would have to select each board explicitly to get the labels of the boards, see our Telegram conversation ;)

**Comment by stefan-niedermann** [comment] 2019-05-01 16:26
I guess the [latest release](https://github.com/nextcloud/deck/releases/tag/v0.6.1) should contain all necessary fixes. Please retest and reopen this issue if errors still occur :rocket:

**Closed by stefan-niedermann** 2019-05-01 16:26 UTC
