### ISSUE TITLE
Infinite sync

### ISSUE THREAD

**Issue by accountForIssues** [stefan-niedermann/nextcloud-deck#947] opened 2021-04-21 12:42 UTC
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

1. Start app and wait for it to sync.
2. Do a pull down refresh.
3. ...
4. .... wait forever

**Expected behavior**
App syncs successfully.

**Versions**
 - Nextcloud: 21.0.1
 - Nextcloud Deck: 1.4.0
 - Nextcloud Android: 3.15.1
 - Nextcloud Android Deck: 1.17.7

**Smartphone (please complete the following information):**
- Device: Samsung S9+
- Android-Version: 10
- App-Store:
  - [ ] Google Play Store
  - [ ] Google Play Store (Beta channel)
  - [x] F-Droid
  - [ ] Huawei AppGallery

**Stacktrace**
```
2021-04-21 14:21:01 DEBUG (DeckApplication.java:151) saveCurrentStackId() → --- Write: it.niedermann.nextcloud.deck.last_stack_for_board_1_1 → 2
2021-04-21 14:21:02 DEBUG (DeckApplication.java:151) saveCurrentStackId() → --- Write: it.niedermann.nextcloud.deck.last_stack_for_board_1_1 → 3
2021-04-21 14:21:03 VERBOSE (BrandingUtil.java:64) getSecondaryForegroundColorDependingOnTheme() → Contrast ratio between brand color #800080 and primary theme background is too low. Falling back to WHITE/BLACK as brand color.
2021-04-21 14:21:07 DEBUG (DeckApplication.java:151) saveCurrentStackId() → --- Write: it.niedermann.nextcloud.deck.last_stack_for_board_1_1 → 2
2021-04-21 14:21:08 DEBUG (DeckApplication.java:151) saveCurrentStackId() → --- Write: it.niedermann.nextcloud.deck.last_stack_for_board_1_1 → 1
2021-04-21 14:21:14 DEBUG (BrandingUtil.java:44) saveBrandColors() → --- Write: it.niedermann.nextcloud.deck.theme_main | -848843
2021-04-21 14:21:14 DEBUG (DeckApplication.java:137) saveCurrentBoardId() → --- Write: it.niedermann.nextcloud.deck.last_board_for_account_1 → 4
2021-04-21 14:21:14 DEBUG (DeckApplication.java:159) readCurrentStackId() → --- Read: it.niedermann.nextcloud.deck.last_stack_for_board_1_4 → 8
2021-04-21 14:21:14 DEBUG (DeckApplication.java:151) saveCurrentStackId() → --- Write: it.niedermann.nextcloud.deck.last_stack_for_board_1_4 → 8
2021-04-21 14:21:18 DEBUG (BrandingUtil.java:44) saveBrandColors() → --- Write: it.niedermann.nextcloud.deck.theme_main | -5125012
2021-04-21 14:21:18 DEBUG (DeckApplication.java:137) saveCurrentBoardId() → --- Write: it.niedermann.nextcloud.deck.last_board_for_account_1 → 3
(MainActivity.java:640) lambda$null$17$MainActivity() → java.lang.IllegalStateException: Could not generate tab title for position 1 because list size is only 2
	at it.niedermann.nextcloud.deck.ui.MainActivity.lambda$null$17$MainActivity(MainActivity.java:640)
	at it.niedermann.nextcloud.deck.ui.-$$Lambda$MainActivity$AjqKQNgxFe_o_le2HBd0hmAxGRI.getTitle(Unknown Source:4)
	at it.niedermann.nextcloud.deck.ui.MainActivity.lambda$null$18(MainActivity.java:644)
	at it.niedermann.nextcloud.deck.ui.-$$Lambda$MainActivity$eAwH7m6-geGqOPlpOrzE7P5vbec.onConfigureTab(Unknown Source:2)
	at com.google.android.material.tabs.TabLayoutMediator.populateTabsFromPagerAdapter(TabLayoutMediator.java:177)
	at com.google.android.material.tabs.TabLayoutMediator$PagerAdapterObserver.onChanged(TabLayoutMediator.java:287)
	at androidx.recyclerview.widget.RecyclerView$AdapterDataObservable.notifyChanged(RecyclerView.java:12253)
	at androidx.recyclerview.widget.RecyclerView$Adapter.notifyDataSetChanged(RecyclerView.java:7354)
	at it.niedermann.nextcloud.deck.ui.stack.StackAdapter.setStacks(StackAdapter.java:54)
	at it.niedermann.nextcloud.deck.ui.MainActivity.lambda$setCurrentBoard$21$MainActivity(MainActivity.java:626)
	at it.niedermann.nextcloud.deck.ui.-$$Lambda$MainActivity$WMXVvIH_d1iPefPxvngGLCVcRgk.onChanged(Unknown Source:4)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
	at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
	at androidx.lifecycle.Transformations$3.onChanged(Transformations.java:188)
	at androidx.lifecycle.MediatorLiveData$Source.onChanged(MediatorLiveData.java:152)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
	at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
	at androidx.lifecycle.LiveData$1.run(LiveData.java:93)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

(MainActivity.java:640) lambda$null$17$MainActivity() → java.lang.IllegalStateException: Could not generate tab title for position 1 because list size is only 2
	at it.niedermann.nextcloud.deck.ui.MainActivity.lambda$null$17$MainActivity(MainActivity.java:640)
	at it.niedermann.nextcloud.deck.ui.-$$Lambda$MainActivity$AjqKQNgxFe_o_le2HBd0hmAxGRI.getTitle(Unknown Source:4)
	at it.niedermann.android.tablayouthelper.TabLayoutHelper.onCreateTab(TabLayoutHelper.java:160)
	at it.niedermann.android.tablayouthelper.TabLayoutHelper.createNewTab(TabLayoutHelper.java:241)
	at it.niedermann.android.tablayouthelper.TabLayoutHelper.setTabsFromPagerAdapter(TabLayoutHelper.java:269)
	at it.niedermann.android.tablayouthelper.TabLayoutHelper.access$300(TabLayoutHelper.java:37)
	at it.niedermann.android.tablayouthelper.TabLayoutHelper$3.onChanged(TabLayoutHelper.java:100)
	at androidx.recyclerview.widget.RecyclerView$AdapterDataObservable.notifyChanged(RecyclerView.java:12253)
	at androidx.recyclerview.widget.RecyclerView$Adapter.notifyDataSetChanged(RecyclerView.java:7354)
	at it.niedermann.nextcloud.deck.ui.stack.StackAdapter.setStacks(StackAdapter.java:54)
	at it.niedermann.nextcloud.deck.ui.MainActivity.lambda$setCurrentBoard$21$MainActivity(MainActivity.java:626)
	at it.niedermann.nextcloud.deck.ui.-$$Lambda$MainActivity$WMXVvIH_d1iPefPxvngGLCVcRgk.onChanged(Unknown Source:4)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
	at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
	at androidx.lifecycle.Transformations$3.onChanged(Transformations.java:188)
	at androidx.lifecycle.MediatorLiveData$Source.onChanged(MediatorLiveData.java:152)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
	at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
	at androidx.lifecycle.LiveData$1.run(LiveData.java:93)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

2021-04-21 14:21:18 DEBUG (DeckApplication.java:159) readCurrentStackId() → --- Read: it.niedermann.nextcloud.deck.last_stack_for_board_1_3 → 7
2021-04-21 14:21:18 DEBUG (DeckApplication.java:151) saveCurrentStackId() → --- Write: it.niedermann.nextcloud.deck.last_stack_for_board_1_3 → 7
2021-04-21 14:21:19 INFO (MainActivity.java:405) lambda$null$14$MainActivity() → Triggered manual refresh
2021-04-21 14:21:19 INFO (CustomAppGlideModule.java:30) clearCache() → Clearing Glide memory cache
2021-04-21 14:21:19 VERBOSE (MainActivity.java:409) lambda$null$14$MainActivity() → Trigger refresh capabilities for [username]@cloud.[domain.tld]
2021-04-21 14:21:19 INFO (CustomAppGlideModule.java:33) lambda$clearCache$0() → Clearing Glide disk cache
2021-04-21 14:21:19 VERBOSE (MainActivity.java:542) refreshCapabilities() → Refreshing capabilities for [username]@cloud.[domain.tld]
2021-04-21 14:21:19 VERBOSE (MainActivity.java:412) lambda$null$14$MainActivity() → Trigger synchronization for [username]@cloud.[domain.tld]
2021-04-21 14:21:19 VERBOSE (NextcloudDeserializer.java:29) deserialize() → {"ocs":{"meta":{"status":"ok","statuscode":200,"message":"OK"},"data":{"version":{"major":21,"minor":0,"micro":1,"string":"21.0.1","edition":"","extendedSupport":false},"capabilities":{"core":{"pollinterval":60,"webdav-root":"remote.php/webdav"},"bruteforce":{"delay":0},"richdocuments":{"version":"4.0.4","mimetypes":["application/vnd.oasis.opendocument.text","application/vnd.oasis.opendocument.spreadsheet","application/vnd.oasis.opendocument.graphics","application/vnd.oasis.opendocument.presentation","application/vnd.lotus-wordpro","application/vnd.visio","application/vnd.ms-visio.drawing","application/vnd.wordperfect","application/msonenote","application/msword","application/rtf","text/rtf","application/vnd.openxmlformats-officedocument.wordprocessingml.document","application/vnd.openxmlformats-officedocument.wordprocessingml.template","application/vnd.ms-word.document.macroEnabled.12","application/vnd.ms-word.template.macroEnabled.12","application/vnd.ms-excel","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","application/vnd.openxmlformats-officedocument.spreadsheetml.template","application/vnd.ms-excel.sheet.macroEnabled.12","application/vnd.ms-excel.template.macroEnabled.12","application/vnd.ms-excel.addin.macroEnabled.12","application/vnd.ms-excel.sheet.binary.macroEnabled.12","application/vnd.ms-powerpoint","application/vnd.openxmlformats-officedocument.presentationml.presentation","application/vnd.openxmlformats-officedocument.presentationml.template","application/vnd.openxmlformats-officedocument.presentationml.slideshow","application/vnd.ms-powerpoint.addin.macroEnabled.12","application/vnd.ms-powerpoint.presentation.macroEnabled.12","application/vnd.ms-powerpoint.template.macroEnabled.12","application/vnd.ms-powerpoint.slideshow.macroEnabled.12","text/csv"],"mimetypesNoDefaultOpen":["image/svg+xml","application/pdf","text/plain","text/spreadsheet"],"collabora":{"convert-to":{"available":false},"hasMobileSupport":true,"hasProxyPrefix":false,"hasTemplateSaveAs":false,"hasTemplateSource":true,"productName":"Collabora Online Development Edition","productVersion":"6.4.7","productVersionHash":"4f68c25"},"direct_editing":true,"templates":true,"productName":"Collabora Online Development Edition","config":{"wopi_url":"https://office.[domain.tld]","public_wopi_url":"https://office.[domain.tld]","disable_certificate_verification":"","edit_groups":null,"use_groups":null,"doc_format":null,"timeout":15}},"files":{"bigfilechunking":true,"blacklisted_files":[".htaccess"],"directEditing":{"url":"https://cloud.[domain.tld]/ocs/v2.php/apps/files/api/v1/directEditing","etag":"6226ba873373f5e73a3ef504107523f7"},"comments":true,"undelete":true,"versioning":true},"activity":{"apiv2":["filters","filters-api","previews","rich-strings"]},"ocm":{"enabled":true,"apiVersion":"1.0-proposal1","endPoint":"https://cloud.[domain.tld]/ocm","resourceTypes":[{"name":"file","shareTypes":["user","group"],"protocols":{"webdav":"/public.php/webdav/"}}]},"dav":{"chunking":"1.0"},"deck":{"version":"1.4.0","canCreateBoards":true,"apiVersions":["1.0","1.1"]},"notes":{"api_version":["0.2","1.1"],"version":"4.0.4"},"notifications":{"ocs-endpoints":["list","get","delete","delete-all","icons","rich-strings","action-web","user-status"],"push":["devices","object-data","delete"],"admin-notifications":["ocs","cli"]},"password_policy":{"minLength":10,"enforceNonCommonPassword":true,"enforceNumericCharacters":false,"enforceSpecialCharacters":false,"enforceUpperLowerCase":false,"api":{"generate":"https://cloud.[domain.tld]/ocs/v2.php/apps/password_policy/api/v1/generate","validate":"https://cloud.[domain.tld]/ocs/v2.php/apps/password_policy/api/v1/validate"}},"provisioning_api":{"version":"1.11.0","AccountPropertyScopesVersion":2,"AccountPropertyScopesFederationEnabled":true},"files_sharing":{"sharebymail":{"enabled":true,"upload_files_drop":{"enabled":true},"password":{"enabled":true,"enforced":false},"expire_date":{"enabled":true}},"api_enabled":true,"public":{"enabled":true,"password":{"enforced":false,"askForOptionalPassword":false},"expire_date":{"enabled":true,"days":"7","enforced":false},"multiple_links":true,"expire_date_internal":{"enabled":false},"send_mail":false,"upload":true,"upload_files_drop":true},"resharing":true,"user":{"send_mail":false,"expire_date":{"enabled":true}},"group_sharing":true,"group":{"enabled":true,"expire_date":{"enabled":true}},"default_permissions":31,"federation":{"outgoing":true,"incoming":true,"expire_date":{"enabled":true}},"sharee":{"query_lookup_default":false,"always_show_unique":true}},"spreed":{"features":["audio","video","chat-v2","conversation-v2","guest-signaling","empty-group-room","guest-display-names","multi-room-users","favorites","last-room-activity","no-ping","system-messages","delete-messages","mention-flag","in-call-flags","conversation-call-flags","notification-levels","invite-groups-and-mails","locked-one-to-one-rooms","read-only-rooms","listable-rooms","chat-read-marker","webinary-lobby","start-call-flag","chat-replies","circles-support","force-mute","conversation-v3","sip-support","chat-read-status","phonebook-search","raise-hand","room-description","rich-object-sharing","chat-reference-id"],"config":{"attachments":{"allowed":true,"folder":"/Talk"},"chat":{"max-length":32000,"read-privacy":0},"conversations":{"can-create":true},"previews":{"max-gif-size":3145728}}},"theming":{"name":"Nextcloud","url":"https://nextcloud.com","slogan":"a safe home for all your data and more...","color":"#800080","color-text":"#ffffff","color-element":"#800080","color-element-bright":"#800080","color-element-dark":"#800080","logo":"https://cloud.[domain.tld]/core/img/logo/logo.svg?v=6","background":"#800080","background-plain":true,"background-default":true,"logoheader":"https://cloud.[domain.tld]/core/img/logo/logo.svg?v=6","favicon":"https://cloud.[domain.tld]/core/img/logo/logo.svg?v=6"},"user_status":{"enabled":true,"supports_emoji":true},"weather_status":{"enabled":true}}}}}
2021-04-21 14:21:19 VERBOSE (JsonToEntityParser.java:516) parseCapabilities() → {"ocs":{"meta":{"status":"ok","statuscode":200,"message":"OK"},"data":{"version":{"major":21,"minor":0,"micro":1,"string":"21.0.1","edition":"","extendedSupport":false},"capabilities":{"core":{"pollinterval":60,"webdav-root":"remote.php/webdav"},"bruteforce":{"delay":0},"richdocuments":{"version":"4.0.4","mimetypes":["application/vnd.oasis.opendocument.text","application/vnd.oasis.opendocument.spreadsheet","application/vnd.oasis.opendocument.graphics","application/vnd.oasis.opendocument.presentation","application/vnd.lotus-wordpro","application/vnd.visio","application/vnd.ms-visio.drawing","application/vnd.wordperfect","application/msonenote","application/msword","application/rtf","text/rtf","application/vnd.openxmlformats-officedocument.wordprocessingml.document","application/vnd.openxmlformats-officedocument.wordprocessingml.template","application/vnd.ms-word.document.macroEnabled.12","application/vnd.ms-word.template.macroEnabled.12","application/vnd.ms-excel","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","application/vnd.openxmlformats-officedocument.spreadsheetml.template","application/vnd.ms-excel.sheet.macroEnabled.12","application/vnd.ms-excel.template.macroEnabled.12","application/vnd.ms-excel.addin.macroEnabled.12","application/vnd.ms-excel.sheet.binary.macroEnabled.12","application/vnd.ms-powerpoint","application/vnd.openxmlformats-officedocument.presentationml.presentation","application/vnd.openxmlformats-officedocument.presentationml.template","application/vnd.openxmlformats-officedocument.presentationml.slideshow","application/vnd.ms-powerpoint.addin.macroEnabled.12","application/vnd.ms-powerpoint.presentation.macroEnabled.12","application/vnd.ms-powerpoint.template.macroEnabled.12","application/vnd.ms-powerpoint.slideshow.macroEnabled.12","text/csv"],"mimetypesNoDefaultOpen":["image/svg+xml","application/pdf","text/plain","text/spreadsheet"],"collabora":{"convert-to":{"available":false},"hasMobileSupport":true,"hasProxyPrefix":false,"hasTemplateSaveAs":false,"hasTemplateSource":true,"productName":"Collabora Online Development Edition","productVersion":"6.4.7","productVersionHash":"4f68c25"},"direct_editing":true,"templates":true,"productName":"Collabora Online Development Edition","config":{"wopi_url":"https://office.[domain.tld]","public_wopi_url":"https://office.[domain.tld]","disable_certificate_verification":"","edit_groups":null,"use_groups":null,"doc_format":null,"timeout":15}},"files":{"bigfilechunking":true,"blacklisted_files":[".htaccess"],"directEditing":{"url":"https://cloud.[domain.tld]/ocs/v2.php/apps/files/api/v1/directEditing","etag":"6226ba873373f5e73a3ef504107523f7"},"comments":true,"undelete":true,"versioning":true},"activity":{"apiv2":["filters","filters-api","previews","rich-strings"]},"ocm":{"enabled":true,"apiVersion":"1.0-proposal1","endPoint":"https://cloud.[domain.tld]/ocm","resourceTypes":[{"name":"file","shareTypes":["user","group"],"protocols":{"webdav":"/public.php/webdav/"}}]},"dav":{"chunking":"1.0"},"deck":{"version":"1.4.0","canCreateBoards":true,"apiVersions":["1.0","1.1"]},"notes":{"api_version":["0.2","1.1"],"version":"4.0.4"},"notifications":{"ocs-endpoints":["list","get","delete","delete-all","icons","rich-strings","action-web","user-status"],"push":["devices","object-data","delete"],"admin-notifications":["ocs","cli"]},"password_policy":{"minLength":10,"enforceNonCommonPassword":true,"enforceNumericCharacters":false,"enforceSpecialCharacters":false,"enforceUpperLowerCase":false,"api":{"generate":"https://cloud.[domain.tld]/ocs/v2.php/apps/password_policy/api/v1/generate","validate":"https://cloud.[domain.tld]/ocs/v2.php/apps/password_policy/api/v1/validate"}},"provisioning_api":{"version":"1.11.0","AccountPropertyScopesVersion":2,"AccountPropertyScopesFederationEnabled":true},"files_sharing":{"sharebymail":{"enabled":true,"upload_files_drop":{"enabled":true},"password":{"enabled":true,"enforced":false},"expire_date":{"enabled":true}},"api_enabled":true,"public":{"enabled":true,"password":{"enforced":false,"askForOptionalPassword":false},"expire_date":{"enabled":true,"days":"7","enforced":false},"multiple_links":true,"expire_date_internal":{"enabled":false},"send_mail":false,"upload":true,"upload_files_drop":true},"resharing":true,"user":{"send_mail":false,"expire_date":{"enabled":true}},"group_sharing":true,"group":{"enabled":true,"expire_date":{"enabled":true}},"default_permissions":31,"federation":{"outgoing":true,"incoming":true,"expire_date":{"enabled":true}},"sharee":{"query_lookup_default":false,"always_show_unique":true}},"spreed":{"features":["audio","video","chat-v2","conversation-v2","guest-signaling","empty-group-room","guest-display-names","multi-room-users","favorites","last-room-activity","no-ping","system-messages","delete-messages","mention-flag","in-call-flags","conversation-call-flags","notification-levels","invite-groups-and-mails","locked-one-to-one-rooms","read-only-rooms","listable-rooms","chat-read-marker","webinary-lobby","start-call-flag","chat-replies","circles-support","force-mute","conversation-v3","sip-support","chat-read-status","phonebook-search","raise-hand","room-description","rich-object-sharing","chat-reference-id"],"config":{"attachments":{"allowed":true,"folder":"/Talk"},"chat":{"max-length":32000,"read-privacy":0},"conversations":{"can-create":true},"previews":{"max-gif-size":3145728}}},"theming":{"name":"Nextcloud","url":"https://nextcloud.com","slogan":"a safe home for all your data and more...","color":"#800080","color-text":"#ffffff","color-element":"#800080","color-element-bright":"#800080","color-element-dark":"#800080","logo":"https://cloud.[domain.tld]/core/img/logo/logo.svg?v=6","background":"#800080","background-plain":true,"background-default":true,"logoheader":"https://cloud.[domain.tld]/core/img/logo/logo.svg?v=6","favicon":"https://cloud.[domain.tld]/core/img/logo/logo.svg?v=6"},"user_status":{"enabled":true,"supports_emoji":true},"weather_status":{"enabled":true}}}}}
2021-04-21 14:21:19 VERBOSE (MainActivity.java:546) onResponse() → Finished refreshing capabilities for [username]@cloud.[domain.tld] successfully.
2021-04-21 14:21:19 VERBOSE (MainActivity.java:551) onResponse() → Maintenance mode is disabled → Stop spinner.
2021-04-21 14:21:23 DEBUG (DeckApplication.java:151) saveCurrentStackId() → --- Write: it.niedermann.nextcloud.deck.last_stack_for_board_1_3 → 6
2021-04-21 14:21:36 DEBUG (DeckApplication.java:151) saveCurrentStackId() → --- Write: it.niedermann.nextcloud.deck.last_stack_for_board_1_3 → 7
2021-04-21 14:21:37 DEBUG (DeckApplication.java:151) saveCurrentStackId() → --- Write: it.niedermann.nextcloud.deck.last_stack_for_board_1_3 → 6
2021-04-21 14:21:39 DEBUG (BrandingUtil.java:44) saveBrandColors() → --- Write: it.niedermann.nextcloud.deck.theme_main | -2905753
2021-04-21 14:21:39 DEBUG (DeckApplication.java:137) saveCurrentBoardId() → --- Write: it.niedermann.nextcloud.deck.last_board_for_account_1 → 2
2021-04-21 14:21:39 DEBUG (DeckApplication.java:159) readCurrentStackId() → --- Read: it.niedermann.nextcloud.deck.last_stack_for_board_1_2 → 5
2021-04-21 14:21:39 DEBUG (DeckApplication.java:151) saveCurrentStackId() → --- Write: it.niedermann.nextcloud.deck.last_stack_for_board_1_2 → 5
2021-04-21 14:21:40 DEBUG (BrandingUtil.java:44) saveBrandColors() → --- Write: it.niedermann.nextcloud.deck.theme_main | -5125012
2021-04-21 14:21:40 DEBUG (DeckApplication.java:137) saveCurrentBoardId() → --- Write: it.niedermann.nextcloud.deck.last_board_for_account_1 → 3
(MainActivity.java:640) lambda$null$17$MainActivity() → java.lang.IllegalStateException: Could not generate tab title for position 1 because list size is only 2
	at it.niedermann.nextcloud.deck.ui.MainActivity.lambda$null$17$MainActivity(MainActivity.java:640)
	at it.niedermann.nextcloud.deck.ui.-$$Lambda$MainActivity$AjqKQNgxFe_o_le2HBd0hmAxGRI.getTitle(Unknown Source:4)
	at it.niedermann.nextcloud.deck.ui.MainActivity.lambda$null$18(MainActivity.java:644)
	at it.niedermann.nextcloud.deck.ui.-$$Lambda$MainActivity$eAwH7m6-geGqOPlpOrzE7P5vbec.onConfigureTab(Unknown Source:2)
	at com.google.android.material.tabs.TabLayoutMediator.populateTabsFromPagerAdapter(TabLayoutMediator.java:177)
	at com.google.android.material.tabs.TabLayoutMediator$PagerAdapterObserver.onChanged(TabLayoutMediator.java:287)
	at androidx.recyclerview.widget.RecyclerView$AdapterDataObservable.notifyChanged(RecyclerView.java:12253)
	at androidx.recyclerview.widget.RecyclerView$Adapter.notifyDataSetChanged(RecyclerView.java:7354)
	at it.niedermann.nextcloud.deck.ui.stack.StackAdapter.setStacks(StackAdapter.java:54)
	at it.niedermann.nextcloud.deck.ui.MainActivity.lambda$setCurrentBoard$21$MainActivity(MainActivity.java:626)
	at it.niedermann.nextcloud.deck.ui.-$$Lambda$MainActivity$WMXVvIH_d1iPefPxvngGLCVcRgk.onChanged(Unknown Source:4)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
	at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
	at androidx.lifecycle.Transformations$3.onChanged(Transformations.java:188)
	at androidx.lifecycle.MediatorLiveData$Source.onChanged(MediatorLiveData.java:152)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
	at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
	at androidx.lifecycle.LiveData$1.run(LiveData.java:93)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

(MainActivity.java:640) lambda$null$17$MainActivity() → java.lang.IllegalStateException: Could not generate tab title for position 1 because list size is only 2
	at it.niedermann.nextcloud.deck.ui.MainActivity.lambda$null$17$MainActivity(MainActivity.java:640)
	at it.niedermann.nextcloud.deck.ui.-$$Lambda$MainActivity$AjqKQNgxFe_o_le2HBd0hmAxGRI.getTitle(Unknown Source:4)
	at it.niedermann.android.tablayouthelper.TabLayoutHelper.onCreateTab(TabLayoutHelper.java:160)
	at it.niedermann.android.tablayouthelper.TabLayoutHelper.createNewTab(TabLayoutHelper.java:241)
	at it.niedermann.android.tablayouthelper.TabLayoutHelper.setTabsFromPagerAdapter(TabLayoutHelper.java:269)
	at it.niedermann.android.tablayouthelper.TabLayoutHelper.access$300(TabLayoutHelper.java:37)
	at it.niedermann.android.tablayouthelper.TabLayoutHelper$3.onChanged(TabLayoutHelper.java:100)
	at androidx.recyclerview.widget.RecyclerView$AdapterDataObservable.notifyChanged(RecyclerView.java:12253)
	at androidx.recyclerview.widget.RecyclerView$Adapter.notifyDataSetChanged(RecyclerView.java:7354)
	at it.niedermann.nextcloud.deck.ui.stack.StackAdapter.setStacks(StackAdapter.java:54)
	at it.niedermann.nextcloud.deck.ui.MainActivity.lambda$setCurrentBoard$21$MainActivity(MainActivity.java:626)
	at it.niedermann.nextcloud.deck.ui.-$$Lambda$MainActivity$WMXVvIH_d1iPefPxvngGLCVcRgk.onChanged(Unknown Source:4)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
	at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
	at androidx.lifecycle.Transformations$3.onChanged(Transformations.java:188)
	at androidx.lifecycle.MediatorLiveData$Source.onChanged(MediatorLiveData.java:152)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
	at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
	at androidx.lifecycle.LiveData$1.run(LiveData.java:93)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

2021-04-21 14:21:40 DEBUG (DeckApplication.java:159) readCurrentStackId() → --- Read: it.niedermann.nextcloud.deck.last_stack_for_board_1_3 → 6
2021-04-21 14:21:40 DEBUG (DeckApplication.java:151) saveCurrentStackId() → --- Write: it.niedermann.nextcloud.deck.last_stack_for_board_1_3 → 6
```

Restarting didn't help. Enabling/Disabling ETags didn't help.

Error seems to be similar to the [comment](https://github.com/stefan-niedermann/nextcloud-deck/issues/889#issuecomment-822434748) in #889 but I haven't added any new lists or moved any of them. I added and edited several cards.

**Comment by stefan-niedermann** [comment] 2021-04-21 13:17
Duplicate of #680

**Closed by stefan-niedermann** 2021-04-21 13:17 UTC

**Comment by stefan-niedermann** [comment] 2021-04-21 13:20
> Restarting didn't help.

Please try to remove your account from the Deck Android app and readd it as a possible quick workaround.

If this doesn't help, wait for [`1.18.x`](https://github.com/stefan-niedermann/nextcloud-deck/releases/tag/1.18.0) being published on F-Droid which contains further fixes for endless spinners

**Comment by accountForIssues** [comment] 2021-04-21 13:59
I thought it was a different error as logs in #680 didn't seem to mirror mine. Sorry for that :)

> 
> Please try to remove your account from the Deck Android app and readd it as a possible quick workaround.
> 

That's usually what I've been doing until now. It's weird because I remember a few versions ago (can't remember which but could be right after ETag introduction), the app worked with zero issues. Background syncs and in-app changes worked perfectly.

I only had a quick look at #680 but is it communication issues with the NC app and Deck that are suddenly causing this issue as it seemed to work fine until a few days ago.
