### ISSUE TITLE
Sync card on Push Notification

### ISSUE THREAD

**Issue by tobiasKaminsky** [stefan-niedermann/nextcloud-deck#569] opened 2020-06-30 05:16 UTC
- have Deck Android app and Nextcloud App installed
- refresh Deck app
- go to web UI and create a new card, assign it to above user
- get a push notification for Deck
- see that Deck app does not know about the card yet and shows "open in browser", but not open in app

**Comment by stefan-niedermann** [comment] 2020-06-30 05:18
Nah, it's not a bug. We don't do a sync yet and can currently only open cards which are already present on the device.

The sync takes currently too long to do it this way...

**Comment by tobiasKaminsky** [comment] 2020-06-30 05:26
Hm, but in the notification you have the card ID, or?
So you could specifically only sync/check this?

**Comment by stefan-niedermann** [comment] 2020-06-30 05:42
Yeah, that's right...

**Comment by michaelsam94** [comment] 2020-07-01 12:30
does push notification work from deck app on server this enhancement of push notification need work on deck app itself I think not in deck client app. I need to work on this issue but need more clarification and to begin implementing this feature

**Comment by stefan-niedermann** [comment] 2020-07-01 12:40
Here are an [architectural overview about how Push notifications](https://github.com/stefan-niedermann/nextcloud-deck/issues/208#issuecomment-609008692) and [the concrete Pull Request which implemented this mechanism](https://github.com/stefan-niedermann/nextcloud-deck/pull/364) in the Deck Android app.
 
And *please* @michaelsam94 use some punctuation marks. It is *really* hard to understand you otherwise.

What exactly are you planning? We already are syncing the given card id and should switch the button text from `Open in browser` to `Open in Deck App` as soon as the card has been synchronized, so *in theory* this already should work.

A good starting point might probably be in the [`PushNotificationActivity`](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/app/src/main/java/it/niedermann/nextcloud/deck/ui/PushNotificationActivity.java#L78) where we receive the push event and decide whether or not we can handle it.

Let me know if you need more information. You are welcome to start a Pull Request :rocket: where we can discuss concrete changes of the implementation :slightly_smiling_face:

**Comment by stefan-niedermann** [comment] 2020-07-01 12:41
@tobiasKaminsky just for error research: Do you have "Sync only on Wi-Fi" enabled or disabled? Did you have Wi-Fi connection at this specific point where the issue appeared?

**Comment by michaelsam94** [comment] 2020-07-01 13:07
@stefan-niedermann sorry for my poor English. I will try to enhance it. I need to ask does any action on deck board like adding new list or adding new card or editing card or putting label on card. does all these actions fire a push notification. I need to ask also about notification background service does it in next cloud app or in the deck app. there should be background service to receive push notification from server like Firebase notification service

**Comment by stefan-niedermann** [comment] 2020-07-01 13:30
> does all these actions fire a push notification

No, the push notifications are only send in cases a user gets mentioned in a comment, assigned to a label or similar actions.

> notification background service does it in next cloud app

Yes, the Google Play Store flavor of the [Nextcloud Files app](https://github.com/nextcloud/android/) uses firebase, and **no, there will never be any proprietary dependencies in the Deck Android app.** That's why the File app is relaying the push notifications to the Deck app as you can see in the architectural overview i posted [in the comment above](https://github.com/stefan-niedermann/nextcloud-deck/issues/569#issuecomment-652394412).

I don't speak that good english neither, that's no shame. But you didn't tell me in a single one of your comments what the hell you actually want. :smile: *something* with push notifications. :question: :question: :question: 

So, whatever you are trying to achieve, i think it is not directly related to this issue ([see the description](https://github.com/stefan-niedermann/nextcloud-deck/issues/569#issue-647867873)). Therefore please
1. Open a new issue
2. Start at the **very beginning**
3. Describe what you are trying to implement
  - in which app you are trying to implement it (Nextcloud Deck server, Nextcloud Deck Android, Nextcloud Files Android, ...)
  - what your use case is and what you are trying to achieve / what problem you want to solve

**Comment by michaelsam94** [comment] 2020-07-01 14:01
this issue is talking about push notification If I understand it right. the use case is that when I assign card to user the user should get notification through nextcloud application. you need to make deck app has the same push notification functionality depending on nextcloud application you could make broadcast receiver in the deck app to listen to push notification that fired in next cloud app

**Comment by tobiasKaminsky** [comment] 2020-07-01 14:02
> @tobiasKaminsky just for error research: Do you have "Sync only on Wi-Fi" enabled or disabled? Did you have Wi-Fi connection at this specific point where the issue appeared?

It was on emulator, but I cannot recall if wifi was enabled.
I assume that the new card info was just not fetched yet. Do you sync in background or why is it important to ask about wifi?

**Comment by stefan-niedermann** [comment] 2020-07-01 14:40
> this issue is talking about push notification If I understand it right.

We already support Push notifications. I [have told you where the existing implementation is](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/app/src/main/java/it/niedermann/nextcloud/deck/ui/PushNotificationActivity.java#L78).

> You need to make deck app has the same push notification functionality depending on nextcloud application

We already support Push notifications. I [showed you how it works](https://github.com/stefan-niedermann/nextcloud-deck/issues/208#issuecomment-609008692) and why we decided to go this way (because we will not add any direct dependencies to proprietary services).

Please read again [what this issue is about](https://github.com/stefan-niedermann/nextcloud-deck/issues/569#issue-647867873).

**Comment by stefan-niedermann** [comment] 2020-07-01 14:42
> Do you sync in background or why is it important to ask about wifi?

We sync only this card, but the method we are calling only executes if one has connection (:heavy_check_mark:) **and** in case one has enabled "Sync only on Wi-Fi" it also checks if the current network is Wi-Fi or mobile data. We should skip the latter in case we received a push notification, but that's another issue.

**Comment by stefan-niedermann** [comment] 2020-10-03 14:38
There was an implementation error. We are working on a fix on branch `push-notification-rework`.

**Comment by stefan-niedermann** [comment] 2020-10-03 15:36
Will be fixed in version `1.10.0`.

**Closed** 2020-10-03 15:35 UTC
Labels: 🐞 bug
