### ISSUE TITLE
create card with attached photo from within app (to use it as photo note eg like google keep)

### ISSUE THREAD

**Issue by proserver1** [stefan-niedermann/nextcloud-deck#653] opened 2020-08-13 05:55 UTC
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by stefan-niedermann** [comment] 2020-08-13 06:29
Thank you for your request. This is a duplicate of https://github.com/stefan-niedermann/nextcloud-deck/issues/289.

We plan to add support and [have started the work](https://github.com/stefan-niedermann/nextcloud-deck/pull/555), but there are a few obstacles regarding permissions and storing the image to a temporary file before uploading it.

**Closed by stefan-niedermann** 2020-08-13 06:29 UTC
Labels: enhancement
