### ISSUE TITLE
Unable to see archived cards on a board

### ISSUE THREAD

**Issue by JordanDIG** [stefan-niedermann/nextcloud-deck#1441] opened 2023-03-06 20:42 UTC
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

It is impossible to see the archived cards of a table, there is no option

**Versions**

 - Nextcloud: 25.0.4
 - Nextcloud Deck: lastest
 - Nextcloud Android: lastest
 - Nextcloud Android Deck: lastest

**Smartphone (please complete the following information):**
- Device: s21
- Android-Version: 13
- App-Store:
  - [X] Google Play Store
  - [ ] Google Play Store (Beta channel)
  - [ ] F-Droid
  - [ ] Huawei AppGallery

**Stacktrace**

**Comment by stefan-niedermann** [comment] 2023-03-07 10:58
Hello there :wave: 

this is a feature we would love to implement! Unfortunately, we are not able to do so because the (not by us developed) Deck server app still does not support fetching archived cards.

We therefore [asked for this feature back in 2020](https://github.com/nextcloud/deck/issues/2613), but unfortunately there hasn't been much progress since then.

In case you have a Nextcloud [Enterprise Subscription](https://nextcloud.com/enterprise/), you might want to contact the Nextcloud GmbH directly to emphasize your needs? It would for sure be helpful for other users.

Closing as duplicate of https://github.com/stefan-niedermann/nextcloud-deck/issues/395

**Closed by stefan-niedermann** 2023-03-07 10:58 UTC
Labels: enhancement

**Comment by desperateCoder** [comment] 2023-03-07 11:01
> In case you have a Nextcloud [Enterprise Subscription](https://nextcloud.com/enterprise/)

Or at least upvote the issue in the server app repo to show the need
