### ISSUE TITLE
crash sometimes when starting app

### ISSUE THREAD

**Issue by ipoupaille** [stefan-niedermann/nextcloud-deck#500] opened 2020-05-16 08:41 UTC
```
App Version: 1.4.0
App Version Code: 1004000
App Flavor: fdroid

Files App Version Code: 30110190

---

OS Version: 3.10.84-perf-ge1ecd45(6)
OS API Level: 24
Device: kinzie
Manufacturer: motorola
Model (and Product): XT1580 (kinzie_reteu)

---

io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = io.reactivex.exceptions.CompositeException)
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
	at io.reactivex.Observable.subscribe(Observable.java:12291)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
Caused by: java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = io.reactivex.exceptions.CompositeException)
	at android.os.Parcel.writeSerializable(Parcel.java:1526)
	at android.os.Parcel.writeValue(Parcel.java:1474)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:723)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1408)
	at android.os.Bundle.writeToParcel(Bundle.java:1133)
	at android.os.Parcel.writeBundle(Parcel.java:763)
	at android.content.Intent.writeToParcel(Intent.java:8702)
	at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:3140)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1584)
	at android.app.ContextImpl.startActivity(ContextImpl.java:791)
	at android.app.ContextImpl.startActivity(ContextImpl.java:768)
	at android.content.ContextWrapper.startActivity(ContextWrapper.java:356)
	at it.niedermann.nextcloud.deck.ui.exception.ExceptionHandler.uncaughtException(ExceptionHandler.java:18)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
	at io.reactivex.plugins.RxJavaPlugins.uncaught(RxJavaPlugins.java:429)
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:383)
	at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:80)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onError(ObservableSubscribeOn.java:63)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher$PublisherSubscriber.onError(ObservableFromPublisher.java:51)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservable$0$NextcloudAPI(NextcloudAPI.java:89)
	at com.nextcloud.android.sso.api.-$$Lambda$NextcloudAPI$yhhE-DMCe81fXF-bhjup5Tra-6o.subscribe(lambda)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	... 9 more
Caused by: java.io.NotSerializableException: com.nextcloud.android.sso.model.ExceptionMessage
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1224)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1584)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1549)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1472)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1218)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:346)
	at java.util.ArrayList.writeObject(ArrayList.java:734)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:977)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1536)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1472)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1218)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1584)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1549)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1472)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1218)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1584)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1549)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1472)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1218)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:346)
	at android.os.Parcel.writeSerializable(Parcel.java:1521)
	... 32 more

```

**Comment by stefan-niedermann** [comment] 2020-05-16 09:01
The cause is known and fixed on our side as well as in the Nextcloud Single Sign On library (which causes the error).

We just need to wait for a new release of the Nextclour Single Sign On library.

Therefore i will close this issue - the fix will come some day and we cannot really speed it up here, sorry.

@tobiasKaminsky i am referring to https://github.com/nextcloud/Android-SingleSignOn/pull/203 - maybe we can do a minor release `0.5.1` for SSO so we can ship a bugfix release?

**Closed by stefan-niedermann** 2020-05-16 09:01 UTC
Labels: bug
