### ISSUE TITLE
CardAttachmentsFragment not attached to an activity

### ISSUE THREAD

**Issue by dsp77** [stefan-niedermann/nextcloud-deck#1037] opened 2021-06-29 10:18 UTC
1. Existing Entry
2. Add to the entry an attachment from the photo gallery. - Note, Nokia 8.1 camera photos are about 11 MiB in size.
3. Deck created the full crash report, however, the App did not crash.

```
Full Crash:

App Version: 1.18.3
App Version Code: 1018003
App Flavor: play

Files App Version Code: 30160190

---

OS Version: 4.9.227-perf+(00WW_6_210)
OS API Level: 30
Device: PNX_sprout
Manufacturer: HMD Global
Model (and Product): Nokia 8.1 (Phoenix_00WW)

---

java.lang.IllegalStateException: Fragment CardAttachmentsFragment{4b5f632} (12ff71a3-6d1e-443f-9b2b-474aaad36a94) not attached to an activity.
	at androidx.fragment.app.Fragment.requireActivity(Fragment.java:928)
	at it.niedermann.nextcloud.deck.ui.card.attachments.CardAttachmentsFragment$5.onResponse(CardAttachmentsFragment.java:469)
	at it.niedermann.nextcloud.deck.ui.card.attachments.CardAttachmentsFragment$5.onResponse(CardAttachmentsFragment.java:466)
	at it.niedermann.nextcloud.deck.api.ResponseCallback$1.onResponse(ResponseCallback.java:70)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.DataPropagationHelper$1.lambda$onResponse$0$DataPropagationHelper$1(DataPropagationHelper.java:55)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.-$$Lambda$DataPropagationHelper$1$-k5_QMpGMhqcuKev1nFbFkJvi4E.run(Unknown Source:16)
	at java.lang.Thread.run(Thread.java:923)

```

**Comment by stefan-niedermann** [comment] 2021-06-29 11:14
Dear @dsp77, thanks for the report and sorry for the inconveniences!

This looks like a duplicate of #478 for which we unfortunately  haven't found a final solution yet, but still trying to track down this issue.

A few questions to be sure, though:

- Have you been able to upload other files via the Deck Android app (or the same file on a second try)?
- Have you tried killing the app and restarting it (Use the Android app switcher button and swipe the Deck app away)?

**Comment by stefan-niedermann** [comment] 2021-06-29 11:18
As a side note: Next time please fill out the complete issue template. It is there for [a reason](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md#why-has-my-bug-report-been-closed), saves your and our time, avoids ping-pong-questions and usually helps us to solve reported issues faster 😉

**Comment by dsp77** [comment] 2021-06-30 18:24
> A few questions to be sure, though:
>    Have you been able to upload other files via the Deck Android app (or the same file on a second try)?

The upload of the file did work. That is the strange thing. The APP brought up the error message, but it did not crash.

>    Have you tried killing the app and restarting it (Use the Android app switcher button and swipe the Deck app away)?

No, as the image was attached as expected, I just posted the error message.

Unfortunately, I am not able to reproduce the error. I created a new entry and attached an image, without problems. I also attached another image to the existing entry, that originally crashed with the attachment, and it worked just fine.

**Comment by stefan-niedermann** [comment] 2021-06-30 18:53
Alright, it happened because a part of the UI was there two times - it shouldn't. When one of the two parts crashed, the error popped up while the rest of the app continued working.

The cause of the second part is Android killing parts of an app when it is in the background. Some other parts survive like "zombies" and then crash unexpectedly.

I'll close this issue in favor of #478 since it is the same and you have been able to successfully complete the upload of the attachment.

Thanks for the report though, and again: sorry for the inconveniences. We're looking for a final solution.

**Closed by stefan-niedermann** 2021-06-30 18:53 UTC
