### ISSUE TITLE
List widget is not synced with Deck App

### ISSUE THREAD

**Issue by foo-git** [stefan-niedermann/nextcloud-deck#783] opened 2021-01-02 08:17 UTC
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**
The list widget is not automatically synced when adding/editing cards in the Nextcloud Deck App, resulting in a stale view of cards.

**To reproduce**
Issue is reproducible with an account from [try.nextcloud.com](https://try.nextcloud.com):
- [X] Yes
- [ ] No

1. Add two list widgets (List 1 and List 2) to homescreen, you should see the current state of cards as in the Deck App.
2. Add a card in the Deck App for List 1.
3. Go back to homescreen, card is correctly shown in List 1 widget.
4. In the Deck App, move card from List 1 to List 2.
4. Go back to homescreen, List 1 widget still shows view from 3, List 2 widget does not show card.

**Expected behavior**
I expect the list widget at least to be synced upon manual changes in the Deck App. Furthermore it should get synced upon automatic/background refresh of the Deck App.

**Versions**
 - Nextcloud: 20.0.4
 - Nextcloud Deck: 1.2.2
 - Nextcloud Android: 3.14.1
 - Nextcloud Android Deck: 1.13.5

**Smartphone (please complete the following information):**
- Device: Google Pixel XL
- Android-Version: LineageOS 17.1 (Android 10)
- Launcher: Trebuchet (Standard LineageOS Launcher)
- App-Store:
  - [ ] Google Play Store
  - [ ] Google Play Store (Beta channel)
  - [X] F-Droid
  - [ ] Huawei AppGallery

**Are you using LDAP?**
- [ ] Yes
- [X] No

**Comment by stefan-niedermann** [comment] 2021-01-02 15:13
That's a bit strange, i can't reproduce the issue. Hav you already tried to remove and readd the widget? What launcher are you using?

**Comment by foo-git** [comment] 2021-01-02 16:11
First, thanks for your good work regarding the Nextcloud Apps :)
I updated the bug description, as I also could not reproduce it like that, sorry.
It seems that you need to move cards to trigger the bug (at least in my case).

**Comment by foo-git** [comment] 2021-01-03 09:17
After some more observation I think it depends also on the time passed since the widget creation:
Yesterday, directly after widget creation, the Deck App and the List widgets are perfectly synced.
Some hours later of not using Deck App/List widgets, changes in the Deck App are not synced to the List widgets.
Today that's still the case.

**Comment by itstueben** [comment] 2021-01-04 06:23
I have the Same Problem. 
Some hours later of not using Deck App/List widgets, changes in the Deck App were not synced to the List widgets.

Sony Xperia 5
Standard Launcher
Android 10

**Comment by Ruben1992** [comment] 2021-01-06 08:28
Hi guys,

I am experiencing the same problem.
However I found a way to trigger the synchronisation:
If I change my power mode (just changing it, doesn't seem to matter to what mode) the widgets suddenly refresh.
So this probably has to do with a battery save program which terminates background tasks.
However for me even if I have the settings on "high performance" and disable "optimise battery usage" for this app. The widget still does not sync. 

Samsung S9
Nova launcher
Android 10

**Comment by kartoffelheinz** [comment] 2021-02-01 21:17
Same problem here, using latest Android 11 on Pixel 4 with app version 1.14.1, installed from Google Play Store.

Refreshing of List widgets does not seem to work at all. I cannot force a refresh using power mode switching as Ruben1992 suggested.

Anything I can do to help?

**Comment by stefan-niedermann** [comment] 2021-02-01 22:22
@kartoffelheinz a Pull Request for #767 is of course appreciated - otherwise you will unfortunately have to wait until we reimplement the widget ourself. I don't think there is a "quickfix" for this issue. :slightly_frowning_face:

**Comment by kartoffelheinz** [comment] 2021-02-02 10:34
I understand. Sadly, I have zero experience in android app development :/

Since the Widget-Filter / Upcoming-Widget seems a lot more important, I vote that you put your available time into developing / improving these, as it has much more important use cases than single stack views anyway.

**Comment by Ruben1992** [comment] 2021-02-04 12:36
I have found that the widget does synchronise, but it does take quite a long time. I havent measured how long it takes, but it is in the order of days.
But I agree with kartoffelheinz, I think its better not to devote time on this, but instead focus on the reimplementation of the widget

**Comment by kartoffelheinz** [comment] 2021-02-08 18:00
As an additional sidenote: The new Upcoming Widget seems to suffer from similar refreshing problems. Since I use the beta version I would refraing from opening another issue for that at this time, this is just to let you know. Maybe it helps to narrow down what the problem is, as I believe the upcoming widget already uses the new FilterWidget infrastructure.

**Comment by stefan-niedermann** [comment] 2021-03-08 09:10
The rewritten list widget will be part of `1.15.2`. Please feel free to open new issues if starting with this version any problems occur with the list widget.

Please note that it is important to write exact steps to reproduce (e. g. "I moved a card from list B to list A on another device. I can see the changes in the Web UI and in the Android App but not in the list widget of A") - name *what* you have done, tell us your online status, tell us whether the changes are made on the same device or on another device or in the browser - the more detailed you describe what you have done, the better are the chances we can fix issues :)

**Closed by stefan-niedermann** 2021-03-08 09:10 UTC
Labels: 🐞 bug
