### ISSUE TITLE
Align "Upcoming cards" selection with deck server app

### ISSUE THREAD

**Issue by jakobroehrl** [stefan-niedermann/nextcloud-deck#986] opened 2021-05-18 08:28 UTC
show on shared boards unassigned cards to all users as mentioned here: https://github.com/nextcloud/deck/pull/3078

 - private boards: all due cards
 - shared boards: all cards assigned to me (with or without due (shown below the "No due" column)) or assigned to nobody and with due

**Comment by desperateCoder** [comment] 2021-05-18 10:15
Hi @jakobroehrl,

>  If due card is not assigned on shared board, it appears in overview

I saw the discussion, but I'm not sure if I got it. The current "logic" (SQL-Query) in **simplified** goes like this:
 `select * from cards where (hasDueDate OR isInSharedBoard) AND (isInSharedBoard OR assignedToMe)`

Now from what I have understood, the second condition after `AND` is obsolete now, right?

If I'm wrong, what would the correct logic be?

**Comment by jakobroehrl** [comment] 2021-05-18 13:14
Hey @desperateCoder 
 - all due cards from private boards
 - all cards assigned to me or to nobody from shared boards

Maybe so?
select * from cards where (hasDueDate OR isInSharedBoard) AND (isInSharedBoard OR assignedToMe) AND (isInSharedBoard OR assignedToNobody)

**Comment by desperateCoder** [comment] 2021-05-18 13:35
So from your bullet points I'd go for something like:

`(hasDueDate AND isIn_PRIVATE_Board) OR (isInSharedBoard AND (assignedToMe OR noAssignees))`

That is a simplified version of your logic, because `IsInSharedBoard` in fact is a subquery and I'd like to avoid evaluating it twice.

There is just one problem left from my point of view regarding shared boards: This would mean, that the existence of due dates are completely ignored in shared boards. The only condition would be "assigned to me" or "assigned to nobody". Is that intended?

**Comment by jakobroehrl** [comment] 2021-05-19 06:02
> There is just one problem left from my point of view regarding shared boards: This would mean, that the existence of due dates are completely ignored in shared boards. The only condition would be "assigned to me" or "assigned to nobody". Is that intended?

This is right. Cards without due of shared boards are shown in the overview under the culumn "No due".
I'm not sure if that make sense for every use case, but this is the current implementation.

**Comment by desperateCoder** [comment] 2021-05-19 10:20
Ok, I think this dev-build should behave as you wish: [ଘ(੭*ˊᵕˋ)੭* ̀ˋ](https://github.com/stefan-niedermann/nextcloud-deck/suites/2777599145/artifacts/61580387)

Plase give it a try, I can't really tell if this is exactly what you want. Looking forward to some feedback! :blush:  :heart:

**Comment by desperateCoder** [comment] 2021-05-19 13:05
So the only difference I spotted is the case when there is no assignee, it has to have a due date to be shown, right?

**Comment by desperateCoder** [comment] 2021-05-19 14:36
> So the only difference I spotted is the case when there is no assignee, it has to have a due date to be shown, right?

Assuming I got this right, please try this one: [( ͡° ͜ʖ ͡°)_/¯ Download](https://github.com/stefan-niedermann/nextcloud-deck/suites/2779804172/artifacts/61646665)

**Comment by jakobroehrl** [comment] 2021-05-19 18:30
> > So the only difference I spotted is the case when there is no assignee, it has to have a due date to be shown, right?
> 
> Assuming I got this right, please try this one: [( ͡° ͜ʖ ͡°)_/¯ Download](https://github.com/stefan-niedermann/nextcloud-deck/suites/2779804172/artifacts/61646665)

Looks good!

**Closed** 2021-07-10 20:35 UTC
Labels: enhancement

**Comment by q-wertz** [comment] 2021-08-13 10:57
Hi,
before opening a new bug report I just wanted to make sure this is not an intended behavior:
Currently in the "Upcoming Cards" section I also see cards that are not assigned to me and which are from a shared board.

To me that looks wrong :sweat_smile:

**Comment by stefan-niedermann** [comment] 2021-08-13 11:18
@q-wertz please see [upcoming-analyzer.niedermann.it](https://upcoming-analyzer.niedermann.it/) for the rule set we adapted from the Deck server app.

If the behavior of the Deck server app 1.5 (or higher) is different to the Deck Android app, please just open a new issue here, if the behavior is the same and wrong on both platforms in your opinion, open a new issue in the [Deck server app repository](https://github.com/nextcloud/deck/issues/new/choose) (and please tag me via `@stefan-niedermann`).

The Deck server app is leading and the Deck Android app will follow :slightly_smiling_face:

**Comment by q-wertz** [comment] 2021-08-14 10:25
Thanks for the hint. I didn't know about the fact that 2nd rule makes the 3rd "useless".

Not what I would expect but makes sense in some way ("hey there is something that has to be done but no one is assigned")

I just currently had the workflow for finished cards to just shift it to a "Done" row, untag me and leave the due date as there is no "Done" tag (yet). Another discussion :)

**Comment by q-wertz** [comment] 2021-08-15 21:57
Sorry, but I just checked again and the rules seem to differ. 

In the Android app I see (as described) tasks that are not assigned to me but have a due date. I don't see them in the usual Deck app. Opened an issue for that (see https://github.com/stefan-niedermann/nextcloud-deck/issues/1081).
