### ISSUE TITLE
upcoming cards in android app

### ISSUE THREAD

**Issue by grynas** [stefan-niedermann/nextcloud-deck#884] opened 2021-03-21 21:52 UTC
Dear developers, 

I`ve started to get used with kanban and Deck on the NextCloud, but unfortunately noticed that Android app has no option to see all upcoming cards. 
If that was implemented that would make posible to have GTD and other implementations without going through the projects.

Thank you in andvance.

**Comment by stefan-niedermann** [comment] 2021-03-21 22:39
Duplicate of #690 - please use the 🔍  search function before opening new issues 🙂 

You can use the [Upcoming Cards widget](https://help.nextcloud.com/uploads/default/optimized/3X/5/3/53454be7c9e862e5c15872c544a3832667622e7d_2_560x1000.jpeg) until this view has been implemented in the app itself.

**Closed by stefan-niedermann** 2021-03-21 22:39 UTC
Labels: enhancement

**Comment by grynas** [comment] 2021-03-21 23:25
Good, at least in widget!
Thanks for fast reply and sorry for duplicate.
