### ISSUE TITLE
Render card text as Markdown

### ISSUE THREAD

**Issue by simonspa** [stefan-niedermann/nextcloud-deck#447] opened 2020-05-03 19:20 UTC
**Is your feature request related to a problem? Please describe.**
In the web app the card description text is rendered as Markdown, i.e. with titles, bullet lists and most importantly checkbox lists. I do see that these are picked up already and displayed as small icon on the card.

**Describe the solution you'd like**
It would be great if the text would also be rendered in the Android app. This would allow to check off boxes directly instead of navigating there with a cursor and replacing the space with an `x`.

**Comment by stefan-niedermann** [comment] 2020-05-03 19:46
Duplicate of https://github.com/stefan-niedermann/nextcloud-deck/issues/311

**Closed by stefan-niedermann** 2020-05-03 19:46 UTC
Labels: enhancement
