### ISSUE TITLE
Feature Request: Sharing of boards with LDAP groups

### ISSUE THREAD

**Issue by TheLoxe** [stefan-niedermann/nextcloud-deck#1532] opened 2023-10-17 17:40 UTC
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Is your feature request related to a problem? Please describe.**
In the Nextcloud Deck WebUI it's possible to share a board with a LDAP group/user.
However, in the Android app it is currently not possible to share a board with a LDAP group but only with single users.

**Describe the solution you'd like**
I would like the exact same sharing possibilities and behaviour as in the Deck WebUI.

**Describe alternatives you've considered**
Share a board with LDAP groups via another possible way.

**Additional context**
Our Nextcloud instance uses OIDC via Keycloak as Single Sign-On and a LDAP backend for user/group data. This constellation shouldn't be rare nowadays.

**Comment by desperateCoder** [comment] 2024-11-22 16:57
Hi @TheLoxe ,
Sorry for the huge delay! 

I'm not sure if this issue is really related to LDAP, I think it is more with groups in general.

I did some work on this topic, can you please see if anything has improved for your use-case?

See this DEV build: [─=≡Σ((( つ◕ل͜◕)つ APK-Download](https://github.com/stefan-niedermann/nextcloud-deck/actions/runs/11976287250/artifacts/2225258193)

[How to use the DEV app](https://github.com/stefan-niedermann/nextcloud-deck/blob/dupes-at-upsync/FAQ.md#using-the-dev-app)

**Comment by TheLoxe** [comment] 2024-11-25 19:01
Hi @desperateCoder,

just wanted to try it out but unfortunately it won't install with the message "There was a problem parsing the package.".

I use a Zenfone 10 with newest Android 14 update.

**Comment by desperateCoder** [comment] 2024-11-25 19:28
@TheLoxe huh?! Weird. But just to make sure, let me ask a dumb question: you unzipped the downloaded file, right? renaming it to .apk won't work. It as a zip containing the actual apk file.

As a last resort, you could try to re-download it to make sure the file wasn't corrupted.

**Comment by TheLoxe** [comment] 2024-11-25 21:06
@desperateCoder Sorry my bad, I thought my smartphone auto-renamed the apk to zip.
Installation worked fine now.

In the sharing dialogue the groups are shown and can be removed from the sharing settings but I still don't get groups as search results when trying to allow access.
Interestingly the groups that I removed from the sharing access of a board can be found in the search of this and other boards afterwards, even after closing and reopening the app.

**Comment by desperateCoder** [comment] 2024-11-25 21:22
> Sorry my bad

Nothing to be sorry about, I'm just glad that I didn't mess up our build or something 😅 

> but I still don't get groups as search results when trying to allow access.

That's actually (kinda) "by design" as the deck API only exposes groups used in boards. I'll see if I find a way to fetch them via other Nextcloud endpoints. Plus: I discovered a problem when you share to a group via app. I know what part is dying and will fix it as soon as I find some time. For now I'm quite happy that we did at least a little progress here. I'll reach out to you within the next few days providing a new, hopefully full working version!

Thanks for your help, patience, testing and feedback so far! ❤️

**Comment by desperateCoder** [comment] 2024-11-27 20:22
@TheLoxe alright, here we go:

[ヽ(｀Д´)⊃━☆ﾟ. * ･ ｡ﾟ, (zipped) APK](https://github.com/stefan-niedermann/nextcloud-deck/actions/runs/12057603107/artifacts/2246596871)

This APK should update your current DEV app.

I'll recommend clearing off broken data caused by the old version via web-app, or trying with a dedicated testboard.

> but I still don't get groups as search results when trying to allow access.

This should be fixed as well, after the next sync after updating the app, you should see all groups you are allowed to see. 

From my point of view, everything regarding sharing and assigning of groups and users should work just fine now. If not, please don't hesitate to throw bad words at me!

I'm looking forward to hear your feedback, hope everything works! :relaxed:

**Comment by TheLoxe** [comment] 2024-12-02 22:11
@desperateCoder Now the search also for groups works like a charm, both issues are solved.

Thanks a lot, that's really helpful!

**Comment by desperateCoder** [comment] 2024-12-02 22:22
@TheLoxe Awesome! I guess there will be an update in the near future with a bunch of fixes including yours.

> Thanks a lot, that's really helpful!

You're very welcome! Thanks for your report and thanks for your patience and help :heart:

**Closed** 2024-12-02 22:22 UTC
Labels: enhancement
