### ISSUE TITLE
Add labels: possible adding a label more than once

### ISSUE THREAD

**Issue by desperateCoder** [stefan-niedermann/nextcloud-deck#276] opened 2020-02-10 18:14 UTC
**Describe the bug**
In edit mode, just add a specific label as many times as you want.

**To Reproduce**
1. Go to edit mode
2. Click on label search bar
3. Select a label
4. Repeat and select the same label again

**Expected behavior**
temporary assigned label shouldn't show up

@stefan-niedermann since the SQL selects only non-assigned labels and additionally you trigger the update after the click on the tick, i am not able to filter the freshly assigned labels. In this case you should handle this in the UI

**Comment by stefan-niedermann** [comment] 2020-02-10 18:16
But... but why should one do that? 😆

**Comment by desperateCoder** [comment] 2020-02-10 18:18
Because I can. I shouldn't be able to do that!

**Comment by stefan-niedermann** [comment] 2020-03-06 21:35
Yeah, root cause is that i query each label from the database that is not yet assigned, and since it is only assigned to database as soon as one actually saves the card, the labels will appear again. I will have to adjust the `AutoCompleteAdapters` to sort out the lables which have been added in the meantime.

**Comment by desperateCoder** [comment] 2020-03-06 21:41
✔️

**Closed** 2020-03-07 11:10 UTC
Labels: bug
