### ISSUE TITLE
No Notification

### ISSUE THREAD

**Issue by timomatrixer** [stefan-niedermann/nextcloud-deck#1531] opened 2023-10-17 06:20 UTC
**Describe the bug**
No Notification on phone, when scheduled todo expires.
App Info on Phone: This App send no notification / Diese App sendet keine Benachrichtigungen

1. Create expiration date for a todo card ![image](https://github.com/stefan-niedermann/nextcloud-deck/assets/40664333/3d70a022-6c8f-4b36-9876-cb8df569d1d8)
2. nextcloud webgui settings: Activity (see picture)
3. Expiry date is overdue and no notification is received.

**Expected behavior**
The app should generate a notification when the event occurs.

**Screenshots**
![image](https://github.com/stefan-niedermann/nextcloud-deck/assets/40664333/41ad432b-85aa-400a-8c98-6795503d25b8)
![image](https://github.com/stefan-niedermann/nextcloud-deck/assets/40664333/0fc62f0b-8691-417c-abde-26537412b086)

**Versions**
 - Nextcloud: [Hub 6](27.1.2)
 - Nextcloud Deck: 	1.11.0
 - Nextcloud Android: 3.26.0
 - Nextcloud Android Deck: 1.22.1

**Smartphone (please complete the following information):**
- Device: Pixel 7 Pro
- Android-Version: 14
- App-Store:
  - [x] Google Play Store

**Stacktrace**

**Comment by stefan-niedermann** [comment] 2023-10-17 07:38
As described in the FAQ, this can only work if the Nextcloud Abdroid app (*not* Deck Android) receives Push Notifications. Does it?

**Comment by timomatrixer** [comment] 2023-10-17 09:59
All settings enabled in nextcloud app.
![image](https://github.com/stefan-niedermann/nextcloud-deck/assets/40664333/990d130e-46ad-4c92-945c-4c092f1c1c19)

**Comment by timomatrixer** [comment] 2023-10-17 10:13
Ok I find out, push notifications only appear, when the time ist set by 5min increments. So for example:
Not working: 12:04 / 12:06 / 12:44 etc...
Working; 12:05 / 12:10 / 12:15 etc...

Could you comfirm that?

**Comment by stefan-niedermann** [comment] 2023-10-17 11:03
Maybe this is related to your cron setup? Are you using a real cronjob or one of the other two solutions?

Do other Push notification (not related to Deck, like File shares) work in general with your phone?

**Comment by timomatrixer** [comment] 2023-10-20 09:04
![image](https://github.com/stefan-niedermann/nextcloud-deck/assets/40664333/f2937d1a-0c9c-4a00-884a-6641923eefb9)
 I think so. In my opinion, that is not correct. How should I explain to my users that they will only receive push notifications if they set the reminder in 5min increments. If the Desk app synchronized every 5min ok. But push notification should work at all times.

**Comment by stefan-niedermann** [comment] 2023-10-20 10:27
To be honest: The (not by us developed) Deck server app sends the Push notification, the (not by us developed) Nextcloud Android app, which receives and displays Puah Notification. The Deck Android App handles clicking on a successfully received Push Notification.

I asked multiple times whether or not you receive *other* push notifications on your Nextcloud Android app to exclude possible error sources (like your Android device, your Google Play Services, your Nextcloud server, your used server apps, ...), you did not respond a single time and help debugging *your* personal setup.

Not sure how you expect us to solve your issue this way?

**Comment by timomatrixer** [comment] 2023-10-20 11:57
Android Nextcloud App Info: All Notification enabled and I am logged in

How do I test this correctly? I have this settings in Web App:
![image](https://github.com/stefan-niedermann/nextcloud-deck/assets/40664333/ebce8e2b-15eb-4c45-8bcc-94f451aff706)

I added a new folder and renamed it:
![image](https://github.com/stefan-niedermann/nextcloud-deck/assets/40664333/31d34bfb-fc8a-46d4-bc13-70e14e44fd88)

Nothing happened

**Comment by stefan-niedermann** [comment] 2023-10-20 15:13
So, you do *not* receive **any** push notifications of your Nextcloud instance (not matter whether Deck or Files or any other app)?

**Comment by timomatrixer** [comment] 2023-10-20 18:11
I receive messages. From the nextcloud app and as described previously, I receive deck app notifications when I set the reminder in 5-minute intervals.
![image](https://github.com/stefan-niedermann/nextcloud-deck/assets/40664333/1f0e36d4-3264-409e-85a6-438bc5091c89)

and here:
![image](https://github.com/stefan-niedermann/nextcloud-deck/assets/40664333/1b822274-624f-488e-ba8f-6529d04b25f0)

**Comment by stefan-niedermann** [comment] 2023-10-21 08:18
Indeed, what a riddle.

Given the Deck Android app only handles clicking on received notifications, we definitely can exclude this app being responsible for your issue. I am also pretty sure the Nextcloud Android App does not cause these symptoms.

However, let's try to investigate it a bit though:

- Push notifications are also send to an open browser: Does your browser also show only due dates set in a 5 minute interval or do any due dates work?
- If you change your settings in the Web UI to receive a mail notification, will this also only work if you use due dates in 5 minute intervals? Are mails send when you have a due date like 12:03 h?

**Comment by timomatrixer** [comment] 2023-10-22 21:26
I have new insights. I did the following tests.
1. Via Web App (browser): due dates: 23:14 -> Notification on Phone and Web App (browser)
2. Via Desk App: due dates: 23:16 -> No notification on Phone and no notification Web App (browser)
3. Via Web App  (browser): due dates: 23:18 -> Notification on Phone appeared at 23: 20 and yes notification Web App (browser) but only after reloading the page

**Comment by timomatrixer** [comment] 2023-10-22 21:30
No E-Mail Server configurated yet. Yahoo has actual problems with smpt PW generation

**Comment by timomatrixer** [comment] 2023-11-03 11:29
Any suggestions?

**Comment by davewhb** [comment] 2024-02-08 15:26
Deck used to send notifications without Push being enabled. Is that no longer possible? 
I do not use google services on my phone so i don't have push capability. I used to get Persistent notifications from Deck  so i added certain tasks to it so i could make sure they would get done. Now i don't even get notified of them.

**Comment by stefan-niedermann** [comment] 2024-02-08 16:29
> Deck Android app used to show notifications without Push being enabled. 

No. It. did. never (as explained multiple times in this thread). The Deck Android App did never and **does not show or send *any*** Push Notifications.

It can handle clicking on notifications shown by the [Nextcloud Android app](https://play.google.com/store/search?q=nextcloud&c=apps) sent by the [Deck server app](https://apps.nextcloud.com/apps/deck).

Yes, the Nextcloud Android app requires Google Play Services to receive Push Notifications.
No, it did never work without.

Troubleshooting:

1. Check whether the Deck Server app sends push notification
2. Check whether the Nextcloud Android app receives and shows notification
3. If, and **ONLY** if, you are experiencing an issue **after clicking** on a notification on your phone, feel free to open an issue. Everything else is completely within the responsibility of your server administrator for 1. or your smarthpone setup for 2.

Also sorry for @timomatrixer but I'll close this issue as the root cause must definitely be outside of the Deck Android app.

**Closed by stefan-niedermann** 2024-02-08 16:29 UTC
