### ISSUE TITLE
list not synchronized between apps when list is emptied

### ISSUE THREAD

**Issue by ipoupaille** [stefan-niedermann/nextcloud-deck#501] opened 2020-05-16 08:53 UTC
1. Create a list on phone 1
2. Add items in list
3. Wait for syncro on phone 2
4. Delete all items of the list with phone 1
5. Wait for synchro on phone 2 => KO
6. Add a new item with phone 1
7. Wait for synchro on phone 2 => working again

**Comment by ipoupaille** [comment] 2020-05-16 08:57
It is possible that bug #500 is because of this one

**Comment by stefan-niedermann** [comment] 2020-05-16 08:57
With "KO" you mean an app crash or just that it doesn't sync anymore?

What happens if you trigger a manual synchronization via Pull 2 Refresh?

**Comment by ipoupaille** [comment] 2020-05-16 08:59
> With "KO" you mean an app crash or just that it doesn't sync anymore?
> 
> What happens if you trigger a manual synchronization via Pull 2 Refresh?

I mean with ko no sync.
Manual sync does nothing on my device

**Comment by stefan-niedermann** [comment] 2020-05-16 14:05
Can you tell us, please whether or not the items are still visible in the web UI between step 4. and 5.? What are the versions of the android deck app and the server deck app?

**Comment by ipoupaille** [comment] 2020-05-16 15:34
> 
> 
> Can you tell us, please whether or not the items are still visible in the web UI between step 4. and 5.? What are the versions of the android deck app and the server deck app?

Elements are not visible in web ui.
server deck version is 1.0.0
android deck app version is 1.4.0

**Comment by stefan-niedermann** [comment] 2020-05-17 10:22
Thank you, i can reproduce the issue.

**Comment by desperateCoder** [comment] 2020-06-09 16:46
will be fixed in `1.5.0`

**Closed by desperateCoder** 2020-06-09 16:46 UTC
Labels: bug

**Comment by desperateCoder** [comment] 2020-06-09 16:50
ah, and btw @ipoupaille: thanks for this report. And sorry for the inconveniences, the bug was intended as "performance improvement", but stopped the sync for this particular case. Please keep complaining! :smiley:
