### ISSUE TITLE
Feature Request: View videos

### ISSUE THREAD

**Issue by ssergio-ll** [stefan-niedermann/nextcloud-deck#1561] opened 2024-01-10 09:23 UTC
When a video is uploaded to Nextcloud Deck and is viewed with the mobile app, it doesn't play directly; instead, it redirects the user to the browser and requires them to log in there. Is it possible to add the option for the user to view it within the same app?

Thank you.

**Comment by stefan-niedermann** [comment] 2024-01-12 15:08
Dear @ssergio-ll this will not happen. For technical reasons we are not able to stream video files.

The closest solution we can off is a better integration with the main Nextcloud Android app - meaning opening a video attachment will resulting in "opening" this video in the main Nextcloud Android app which is able to stream it.

Closing in favor of #1562 therefore.

**Closed by stefan-niedermann** 2024-01-12 15:08 UTC
Labels: enhancement

**Comment by stefan-niedermann** [comment] 2024-01-21 12:09
Had another look at this issue, and it ain't a duplicate of #1562. However, we managed to open files in the Nextcloud Files app when clicking on them which allows to stream videos. Hope this will enhance the situation for you.

This feature will be shipped with Deck Android `1.24.0`.
