### ISSUE TITLE
Crash on some devices caused by maxLines-ellipsize combination

### ISSUE THREAD

**Issue by ipoupaille** [stefan-niedermann/nextcloud-deck#444] opened 2020-05-01 07:37 UTC
Appear after success login

Log: 

```
App Version: 1.0.0
App Version Code: 1000000
App Flavor: fdroid

Files App Version Code: 30110190

---

OS Version: 3.4.0-perf-g5fe8ba4(15293232861a4)
OS API Level: 21
Device: g2
Manufacturer: LGE
Model (and Product): LG-D802 (g2_open_com)

---

java.lang.ArrayIndexOutOfBoundsException: length=41; index=-1
	at android.text.StaticLayout.calculateEllipsis(StaticLayout.java:733)
	at android.text.StaticLayout.out(StaticLayout.java:652)
	at android.text.StaticLayout.generate(StaticLayout.java:432)
	at android.text.StaticLayout.<init>(StaticLayout.java:145)
	at android.widget.TextView.makeSingleLayout(TextView.java:6635)
	at android.widget.TextView.makeNewLayout(TextView.java:6488)
	at android.widget.TextView.onMeasure(TextView.java:6870)
	at android.view.View.measure(View.java:17496)
	at androidx.appcompat.widget.LinearLayoutCompat.measureHorizontal(LinearLayoutCompat.java:1208)
	at androidx.appcompat.widget.LinearLayoutCompat.onMeasure(LinearLayoutCompat.java:557)
	at android.view.View.measure(View.java:17496)
	at androidx.recyclerview.widget.RecyclerView$LayoutManager.measureChildWithMargins(RecyclerView.java:9384)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1653)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1255)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1705)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1559)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1468)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1705)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1559)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1468)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2102)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1859)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1078)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5875)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
	at android.view.Choreographer.doFrame(Choreographer.java:550)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5349)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)

```

**Comment by stefan-niedermann** [comment] 2020-05-01 08:04
Can you please try version `0.6.0` and tell me if it worked there for you? I will have a look asap.

**Comment by ipoupaille** [comment] 2020-05-01 08:25
This is the same

```
App Version: 0.6.0
App Version Code: 6000
App Flavor: fdroid

Files App Version Code: 30110190

---

OS Version: 3.4.0-perf-g5fe8ba4(15293232861a4)
OS API Level: 21
Device: g2
Manufacturer: LGE
Model (and Product): LG-D802 (g2_open_com)

---

java.lang.ArrayIndexOutOfBoundsException: length=41; index=-1
	at android.text.StaticLayout.calculateEllipsis(StaticLayout.java:733)
	at android.text.StaticLayout.out(StaticLayout.java:652)
	at android.text.StaticLayout.generate(StaticLayout.java:432)
	at android.text.StaticLayout.<init>(StaticLayout.java:145)
	at android.widget.TextView.makeSingleLayout(TextView.java:6635)
	at android.widget.TextView.makeNewLayout(TextView.java:6488)
	at android.widget.TextView.onMeasure(TextView.java:6870)
	at android.view.View.measure(View.java:17496)
	at androidx.appcompat.widget.LinearLayoutCompat.measureHorizontal(LinearLayoutCompat.java:1208)
	at androidx.appcompat.widget.LinearLayoutCompat.onMeasure(LinearLayoutCompat.java:557)
	at android.view.View.measure(View.java:17496)
	at androidx.recyclerview.widget.RecyclerView$LayoutManager.measureChildWithMargins(RecyclerView.java:9384)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1653)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1255)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1705)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1559)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1468)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1705)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1559)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1468)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
	at android.view.View.layout(View.java:15654)
	at android.view.ViewGroup.layout(ViewGroup.java:4969)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2102)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1859)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1078)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5875)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
	at android.view.Choreographer.doFrame(Choreographer.java:550)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5349)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)

```

**Comment by stefan-niedermann** [comment] 2020-05-01 08:46
Seems to be a bug in android itself according to [this Stackoverflow entry](https://stackoverflow.com/a/45442154). I will try to find a workaround but i need your help @ipoupaille because i cannot reproduce it on my machines. You will need to test some fixes and tell me whether or not it works. Is this okay for you?

**Comment by ipoupaille** [comment] 2020-05-01 09:03
It is ok for me if it is not too hard. I don't know a lot about android.

**Comment by stefan-niedermann** [comment] 2020-05-01 09:17
I will just send you `.apk`-files and you only will need to install them and tell me if they crash or not :wink: pretty easy.

**Comment by stefan-niedermann** [comment] 2020-05-01 09:28
And here comes the first `.apk`-file (you obviously have to unzip before you can install it - sorry, it comes straight from our CI / CD system which always zippes the apps):

https://github.com/stefan-niedermann/nextcloud-deck/suites/645042073/artifacts/5444914

I removed some of the most probable causes for the error. We need to find the exact place that is causing the issues before we can solve it (without any drawbacks for the other users).

**Comment by ipoupaille** [comment] 2020-05-01 13:18
It is working.

**Comment by ipoupaille** [comment] 2020-05-01 13:22
Oops, I still have a problem when the application goes to background, and again to foreground:
```
App Version: 1.0.2
App Version Code: 1000002
App Flavor: dev

Files App Version Code: 30110190

---

OS Version: 3.4.0-perf-g5fe8ba4(15293232861a4)
OS API Level: 21
Device: g2
Manufacturer: LGE
Model (and Product): LG-D802 (g2_open_com)

---

java.lang.RuntimeException: Unable to start activity ComponentInfo{it.niedermann.nextcloud.deck.dev/it.niedermann.nextcloud.deck.ui.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Long it.niedermann.nextcloud.deck.model.Board.getLocalId()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2331)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2391)
	at android.app.ActivityThread.access$800(ActivityThread.java:151)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1309)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5349)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Long it.niedermann.nextcloud.deck.model.Board.getLocalId()' on a null object reference
	at it.niedermann.nextcloud.deck.ui.MainViewModel.getCurrentBoardLocalId(MainViewModel.java:43)
	at it.niedermann.nextcloud.deck.ui.stack.StackFragment.onCreateView(StackFragment.java:67)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2698)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1187)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2625)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2577)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)
	at it.niedermann.nextcloud.deck.ui.branding.BrandedActivity.onStart(BrandedActivity.java:53)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1220)
	at android.app.Activity.performStart(Activity.java:6036)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2294)
	... 10 more

```

**Comment by stefan-niedermann** [comment] 2020-05-01 22:13
Okay, can you now test this please: https://github.com/stefan-niedermann/nextcloud-deck/suites/646590678/artifacts/5482346

Does this still work for you?

**Comment by ipoupaille** [comment] 2020-05-02 07:17
No, I have again the ArrayIndexOutOfBoundsException in android.text.StaticLayout.calculateEllipsis(StaticLayout.java:733)

Regards,

**Comment by stefan-niedermann** [comment] 2020-05-02 12:55
Thanks. I isolated 3 possible locations of the error.

Next test app: https://github.com/stefan-niedermann/nextcloud-deck/suites/647626349/artifacts/5506174

**Comment by ipoupaille** [comment] 2020-05-02 13:50
This is working.
Each element is quiet height (2 lines). On another device, it is taking only one line.
I hadn't noticed it the first time.

![IMG_20200502_154725895](https://user-images.githubusercontent.com/36363815/80865922-71285480-8c8c-11ea-93bf-3ea02bd7fba0.jpg)

**Comment by stefan-niedermann** [comment] 2020-05-02 13:57
> Each element is quiet height (2 lines). On another device, it is taking only one line.

That's fine, you just haven't got the newest version on your other device. But that's another topic.

So, about the issue, it seems to be a consequence of https://github.com/stefan-niedermann/nextcloud-deck/issues/136#issuecomment-536216820

I will have a look what we can do here.

**Comment by ipoupaille** [comment] 2020-05-02 14:05
Thank you very much for the time spent.
Is the version you provided to me usable until the issue is corrected in a official version?
Regards

**Comment by stefan-niedermann** [comment] 2020-05-02 14:06
It can be used safely, but beware that it won't receive any updates.

**Comment by stefan-niedermann** [comment] 2020-05-02 14:14
First attempt to fix it: https://github.com/stefan-niedermann/nextcloud-deck/suites/647728262/artifacts/5509060

Sorry again that i have to bother you with all those attempts, but as i can't reproduce it, i have no other options to fix it :slightly_frowning_face:

**Comment by ipoupaille** [comment] 2020-05-02 14:29
I am so sorry, but it is not working. Still ArrayOutOfBoundsException.

**Comment by stefan-niedermann** [comment] 2020-05-02 14:37
Next: https://github.com/stefan-niedermann/nextcloud-deck/suites/647753824/artifacts/5509679

**Comment by ipoupaille** [comment] 2020-05-02 14:41
It is working

**Comment by stefan-niedermann** [comment] 2020-05-02 14:42
That's good news. Now i will try to restore the original behavior for current android versions and if it keeps working, we can merge this into master and publish the fix with the next version.

**Comment by stefan-niedermann** [comment] 2020-05-02 14:51
Hopefully last version: https://github.com/stefan-niedermann/nextcloud-deck/suites/647767259/artifacts/5510045

😓💨

**Comment by ipoupaille** [comment] 2020-05-02 14:58
It is working. Congratulations.

**Comment by stefan-niedermann** [comment] 2020-05-02 14:59
Thanks you! Will be released in version `1.0.0`.

I think i deserved a cake.

![gif](https://media.giphy.com/media/11qA23s14znYMU/giphy.gif)

**Closed** 2020-05-02 14:59 UTC
Labels: bug

**Comment by ipoupaille** [comment] 2020-05-02 15:01
Has version 1.0.0 not already been released?
Enjoy you peace of cake.

**Comment by stefan-niedermann** [comment] 2020-05-02 15:02
Sorry, edited - definitely the next version, likely `1.1.0`, maybe `1.0.3`, let's see...
