### ISSUE TITLE
Add a button to force sync all upcoming due cards / all cards on all boards

### ISSUE THREAD

**Issue by ahcheing** [stefan-niedermann/nextcloud-deck#1476] opened 2023-04-24 14:21 UTC
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Is your feature request related to a problem? Please describe.**

It takes way to long for changes to sync from the server to the app when cards are rescheduled via the API. 

Currently, if I reschedual a due date with the api, the only / fastest way to reflect that change in the app is to wait 15 minutes and hope that the app updates in the background (which it very, very often does not do for reasons I cant quite figure out). Otherwise the only way to refresh the app is to try to find every single list where I know a change was made by the api, add a new card to the list with the title "delme" (I have a cron job setup to periodically delete all cards with "delme" in the title), then swipe down and wait for that one list on that one board to properly refresh. Then go on to the next one. then the next. getting more annoyed each time. 

This is a big problem since I use tasker + some janky pytjon scripts to do bulk card modification / editing. To give my most used example, lets say that I see that I have 40+ cards due today (which happens freqyently). Thats to many tasks to fit in a day, so I click a tasker icon to fire a python script on my server which uses the deck api to reschedual to tomorow all cards with the "low" label. 

But I might as well not bother, because its faster to just manually modify them in the deck app. As to why I dont just do that, because Its a boring, tedious, repetitive chore that takes 5-10 minutes very early in the morning when I am not properly cafinated so it feels like it takes 100 minutes, and it makes me stupidly angry, since I spent a not-insignificant amount of free time trying to figure out how to kludge together a python script to automated the process, and I dont know the first thing about programming, I just want to make it easier to update my task list.

**Describe the solution you'd like**

There should be a button i can press to force the app to sync all of the cards in the "upcoming cards" view. 

Better yet, button to press to force the app to sync all the boards and all the cards. Although that might be to slow or something. 

**Describe alternatives you've considered**

Its probably more difficult to implement, but a way of bulk editing cards within the app would be great. IE, select multiple cards, then click a clock button to reschedual all of the selected cards.

**Comment by stefan-niedermann** [comment] 2023-04-24 16:56
Pull to refresh?

**Comment by ahcheing** [comment] 2023-04-26 12:39
I assumed, perhaps erroneously, that pull to refresh was just doing a quick check to see if changes to that list had been made since the last sync (or something) rather then doing a full "give me **all** of the non-archived cards so I can compare internal app state to server state" refresh.

Because at least in the context of my kludged together python script and the deck api, Pull to refresh does not work. even when I pull to refresh on the specific list that the card is in, the spinier just quickly rotates one or twice then stops with no changes being reflected and no error message. 

In order to update the displayed card in that list, I have to add a card, then swipe down, and only then will that specific list of cards be updated to reflect changes made with api. 

This behavior is not present when I make changes to cards in the web ui, so its very possible I'm borking something up with my python script, but when the script runs the cards update in the UI with no problem so idk. 

Would posting some of the python from the script be helpful? Its based on this [python import-export script](https://gist.github.com/svbergerem/5914d7f87764901aefddba125af99938), which I modified so that rather then creating a whole new series of boards/cards it updates the due date of all cards with a given tag.

**Comment by stefan-niedermann** [comment] 2023-04-26 12:50
In fact, pull to refresh does synchronize everything. It works that quick because we can check with `ETag`s what actually changed.

If you disable `ETag`s in the Deck Android apps preferences, you will notice that a resync will take way longer because we actually transfer *all* the data again.

The Deck server app however unfortunately has some known issues when it should update the `ETag`s, so clients arent't able to notice a change. This works for boards and cards, but especially when it comes to lists, you might stumble upon those issues.

It would be helpful if you could verify that with disabled `ETag`s Pull to refresh works as expected, please.

**Comment by ahcheing** [comment] 2023-04-26 13:34
I do use etags, and at least according to my notes the last time I tried to debug this (several months / versions of the app ago) this does not fix the issue. But, since you posted your comment I've flipped that particular switch, and I am still waiting for the app to finish syncing / stop crashing. This is not terribly surprising, because doing the initial sync takes a long time and involves many crashes, since I have 20+ boards and several hundred / thousand cards (I know deck app not designed for this, blame the tasks app for its cluttered UI and its lack of of necessary functionality like assigning people and the ability to associate a task with a project, or just quickly add a links to files from the file ui without having to copy paste links into the "notes" section for every single task that references an otherwise terribly difficult to find file)

I'll update this comment / thread if / when I get the app to sync. I wonder if there is a way to force update the etag via my python script? filing that away as something to tinker with later.

**Comment by ahcheing** [comment] 2023-04-26 15:40
The app is simply to slow without using etags to properly debug the issue. After closing down other apps and trying to sync, eventually I could confirm that one of the cards on one of the lists that changed via api was updated in the app itself. But that also happens if enough time passes when etags are enabled if enough time passes. 

I've *also* confirmed that the etags do actually update when I run the python script. or at least, I run curl to check an etag, copy paste it, run the script to update the due date, then check with curl again, and the etag has been updated. so at least in that one specific case my script is not breaking the tag. 

Since I dont really have spare tiome today to tinker with this more I'm going to give it another try this weekend to try to narrow down the bug.

**Comment by stefan-niedermann** [comment] 2024-01-14 12:15
Given this issue is quite old: Are you still working on it? I currently can still see a decision between plague or cholera:

Solution 1: Fix the `ETag` issues of the Deck server app (Just search their repository, there are plenty of them :slightly_frowning_face:)
Solution 2: Go ahead with disabled `ETag`s - which can take very much time by design (given we ensure offline capabilities, we synchronize the whole data of the current account)

**Comment by stefan-niedermann** [comment] 2024-02-08 16:35
Closing due to missing response. Please feel free to reopen the issue, otherwise referencing to my [last comment](https://github.com/stefan-niedermann/nextcloud-deck/issues/1476#issuecomment-1890935727).

**Closed by stefan-niedermann** 2024-02-08 16:35 UTC
Labels: enhancement
