### ISSUE TITLE
302 redirect not working

### ISSUE THREAD

**Issue by dodedodo** [stefan-niedermann/nextcloud-deck#1182] opened 2021-12-13 00:18 UTC
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**
I migrated my nextcloud installation to a subdomain. To aid in the migration I enabled a http 302 redirect that works flawlessly with the desktop and android nextcloud sync clients. However, deck-android throws an error `HTTP request failed with HTTP status-code: 302` Maybe this is not as much a bug as it is a design decision? But it would be a nice-to-have in my scenario.

The same is true for the android notes app, should I open this issue there as well?

1. Migrate  nextcloud to new subdomain
2. Enable 302 redirects on old domain while maintaining url paths. (i.e. HTTP 302 old.tld/apps/deck -> new.tld/apps/deck)
3. Nextcloud android app works ootb. Android deck app does not.

**Expected behavior**

The same account works in the files app, so I'd expect it to work in deck and notes as well. 

**Versions**

 - Nextcloud: 23.0.0
 - Nextcloud Deck: 1.6.0
 - Nextcloud Android: 3.18.0
 - Nextcloud Android Deck: 1.19.6

**Smartphone (please complete the following information):**
- Device: Moterola moto g8 plus
- Android-Version: 10
- App-Store:
  - [x] Google Play Store (nextcloud)
  - [x] F-Droid (deck)

## Solution
1. Re-add your account in the nextcloud files app
2. Re-add your account in the deck/notes app
3. enjoy

**Comment by stefan-niedermann** [comment] 2021-12-13 06:18
Good morning @dodedodo ,

this issue is caused by the Nextclouf Single Sign On Mechanism (see https://github.com/nextcloud/Android-SingleSignOn/issues/200) and therefore also affects the Notes app but can't be fixed there or here directly.

The only known workaround is to [clear the storage](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md#i-have-experienced-an-error) of the 3rd party app, remove the account from the Nextcloud Files app and then set it up again (as you explained yourself).

So, sorry that i don't have better news for you, but all kind of network requests are made by the SSO library.

Given there is a workaround and the scenario usually doesn't happen on a daily base, i guess the issue doesn't have top priority in the SSO lib, but upvoting is always good - mayve you even want to dig into the code and contribute a PR? 🚀 🙂

**Comment by stefan-niedermann** [comment] 2022-01-13 11:53
Closing this issue as it must be solved in the SSO library as describe above

**Closed by stefan-niedermann** 2022-01-13 11:53 UTC
