### ISSUE TITLE
Deck

### ISSUE THREAD

**Issue by Fredericstella** [stefan-niedermann/nextcloud-deck#1176] opened 2021-12-03 22:35 UTC
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

**Expected behavior**

**Screenshots**

**Versions**

 - Nextcloud: 
 - Nextcloud Deck: 
 - Nextcloud Android: 
 - Nextcloud Android Deck: 

**Smartphone (please complete the following information):**
- Device: 
- Android-Version: 
- App-Store:
  - [ ] Google Play Store
  - [ ] Google Play Store (Beta channel)
  - [ ] F-Droid
  - [ ] Huawei AppGallery

**Stacktrace**

```
App Version: 1.19.4
App Version Code: 1019004
Server App Version: 1.4.3
App Flavor: play

Files App Version Code: com.nextcloud.android.beta

---

OS Version: 4.14.180-perf+(1634120990659)
OS API Level: 30
Device: OP4B80L1
Manufacturer: OPPO
Model (and Product): CPH1941 (CPH1941EEA)

---

it.niedermann.nextcloud.deck.exceptions.UploadAttachmentFailedException: Unknown URI scheme
	at it.niedermann.nextcloud.deck.ui.card.attachments.CardAttachmentsFragment$5.lambda$onError$1$CardAttachmentsFragment$5(CardAttachmentsFragment.java:484)
	at it.niedermann.nextcloud.deck.ui.card.attachments.CardAttachmentsFragment$5$$ExternalSyntheticLambda1.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:263)
	at android.app.ActivityThread.main(ActivityThread.java:8283)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.AttachmentDataProvider.createOnServer(AttachmentDataProvider.java:71)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.providers.AttachmentDataProvider.createOnServer(AttachmentDataProvider.java:20)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.DataPropagationHelper.createEntity(DataPropagationHelper.java:48)
	at it.niedermann.nextcloud.deck.persistence.sync.helpers.DataPropagationHelper.createEntity(DataPropagationHelper.java:32)
	at it.niedermann.nextcloud.deck.persistence.sync.SyncManager.lambda$addAttachmentToCard$48$SyncManager(SyncManager.java:1775)
	at it.niedermann.nextcloud.deck.persistence.sync.SyncManager$$ExternalSyntheticLambda16.run(Unknown Source:12)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

```

**Comment by stefan-niedermann** [comment] 2021-12-04 06:37
Hello @Fredericstella 👋 

thank you for filling out the issue template (you won't believe how many people just ignore or delete it). This helps us to quickly evaluate your issue and learn more abot your specific environment 🚀 
This way we also don't have to ask the same questions over and over again, which saves much of our and your valuable freetime ⌚ 

The concise and short title you cose, will allow us to recognize your issue among the others easily and the hard work you put into the issue overall is a sign of respect that motivates us. 💪 ([See also](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md#why-has-my-bug-report-been-closed))

Have a nice weekend and stay well.in those hard times!

Regards,
Stefan

PS.: Closing as duplicate of https://github.com/stefan-niedermann/nextcloud-deck/issues/1175 (the very first issue at the very top of our quite short list 😉)

**Closed by stefan-niedermann** 2021-12-04 06:37 UTC
