### ISSUE TITLE
Error when sending attachement

### ISSUE THREAD

**Issue by wargreen** [stefan-niedermann/nextcloud-deck#1712] opened 2024-12-27 18:37 UTC
### This issue respects the following points:

- [X] I have read the [FAQ](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/FAQ.md)
- [X] I have searched for existing issues
- [X] The issue affects the Deck Android app, neither the [Deck server app](https://github.com/nextcloud/deck/issues/) nor the [Nextcloud Android app](https://github.com/nextcloud/android/issues).

### Describe the bug

1. open a card
2. go to attachement tab
3. Send an attachement
4. Crash

### Deck Android version

1.24.1

### Deck server version

1.14.2

### Nextcloud Android version

3.30.6

### Nextcloud version

3.0.2

### Device

Samsung S10e

### Android Version

13, Lineage 20

### App Store

- [ ] Google Play Store
- [ ] Google Play Store (Beta channel)
- [X] F-Droid
- [ ] Huawei App Gallery

### Stacktrace

```
App Version: 1.24.1
App Version Code: 1024001
Server App Version: 1.14.2
App Flavor: fdroid

Files App Version Code: 30300690 (PROD)

---

OS Version: 4.14.316-gd6b3f0e36572(695c01df21)
OS API Level: 33
Device: beyond0lte
Manufacturer: samsung
Model (and Product): SM-G970F (lineage_beyond0lte)

---

it.niedermann.nextcloud.deck.exceptions.UploadAttachmentFailedException: Unknown URI scheme
	at it.niedermann.nextcloud.deck.ui.card.attachments.CardAttachmentsFragment$5.onError(CardAttachmentsFragment.java:387)
	at it.niedermann.nextcloud.deck.remote.api.ResponseCallback$1.onError(ResponseCallback.java:76)
	at it.niedermann.nextcloud.deck.remote.helpers.DataPropagationHelper$1.lambda$onError$1(DataPropagationHelper.java:70)
	at it.niedermann.nextcloud.deck.remote.helpers.DataPropagationHelper$1$$ExternalSyntheticLambda1.run(Unknown Source:4)
	at it.niedermann.nextcloud.deck.util.ExecutorServiceProvider$RetryableRunnable.run(ExecutorServiceProvider.java:66)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: La requête HTTP a échoué avec le statut HTTP :400
	at it.niedermann.nextcloud.deck.remote.api.RequestHelper$ResponseConsumer.onResponse(RequestHelper.java:70)
	at com.nextcloud.android.sso.helper.Retrofit2Helper$1.lambda$enqueue$0(Retrofit2Helper.java:87)
	at com.nextcloud.android.sso.helper.Retrofit2Helper$1.$r8$lambda$n0izO5V3AflskH7z1H8dSLmVKXo(Unknown Source:0)
	at com.nextcloud.android.sso.helper.Retrofit2Helper$1$$ExternalSyntheticLambda0.run(Unknown Source:6)
	... 1 more
Caused by: java.lang.RuntimeException: HTTP StatusCode wasn't 2xx:
Got [HTTP 400] for Call [GET http://localhost//index.php/apps/deck/api/v1.0/boards/194/stacks/541/cards/1818/attachments] with Message:
[{"status":400,"message":"type must be provided and must be not empty"}
]
	at it.niedermann.nextcloud.deck.remote.api.RequestHelper$ResponseConsumer.buildCause(RequestHelper.java:87)
	... 5 more

```

**Comment by desperateCoder** [comment] 2024-12-27 19:37
Hi @wargreen , thanks for your report!

this is a duplicate of https://github.com/stefan-niedermann/nextcloud-deck/issues/1689#issuecomment-2507346390 - I'll close this one. Please see the linked comment, can you please test the  version there and provide some feedback in the other issue?

Thanks in advance!

**Closed by desperateCoder** 2024-12-27 19:37 UTC
