### ISSUE TITLE
"Upcoming cards" shows cards from different accounts

### ISSUE THREAD

**Issue by cloud2018** [stefan-niedermann/nextcloud-deck#1027] opened 2021-06-22 05:47 UTC
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

1. Android with Nextcloud app and Deck app
2. 2 users on 2 different servers registered in Nextcloud app
3. Open Deck app with one of the two users 
4. The overview (left menu) board list shows as expected only the boards of the selected user
5. "Upcoming cards" shows upcoming cards of both users

**Expected behavior**

As with board list, only upcoming cards of the selected user should be displayed.

**Versions**
 - Nextcloud: 18, 21
 - Nextcloud Deck: 1.2.7
 - Nextcloud Android: 3.16.1
 - Nextcloud Android Deck:  1.18.3

**Smartphone (please complete the following information):**
- Device: Oppo
- Android-Version: 11
- App-Store: 
  - [ ] Google Play Store
  - [ ] Google Play Store (Beta channel)
  - [x] F-Droid
  - [ ] Huawei AppGallery

**Stacktrace**

**Comment by stefan-niedermann** [comment] 2021-06-22 05:52
Duplicate of https://github.com/stefan-niedermann/nextcloud-deck/issues/962

**Closed by stefan-niedermann** 2021-06-22 05:52 UTC
