### ISSUE TITLE
Flexible view of lists within a deck (for larger screens - like tablets)

### ISSUE THREAD

**Issue by JoPyCh** [stefan-niedermann/nextcloud-deck#1625] opened 2024-05-14 07:23 UTC
### Is your feature request related to a problem? Please describe.

I'm working on a large screen tablet and have my deck sorted with 4 lists each which i want to have an overview over without needing to switch view.

### Describe the solution you'd like

It would be nice to have a setting like "lists to be shown besides each other: default = 1" of maybe even a setting in Pixels so that it adjusts automatically when the sceen is turnd

**Comment by stefan-niedermann** [comment] 2024-05-14 07:29
Duplicate of https://github.com/stefan-niedermann/nextcloud-deck/issues/781

**Closed by stefan-niedermann** 2024-05-14 07:29 UTC
Labels: enhancement
