### ISSUE TITLE
When added, the lebels are not synchronized with the server.

### ISSUE THREAD

**Issue by krestyanikov** [stefan-niedermann/nextcloud-deck#414] opened 2020-04-25 12:10 UTC
**Describe the bug**
Thank you for your work. The application is really great. We use custom labels a lot. Usually we use 5 to 10 of them. However, there is a problem with them. When you try to add a label through an application in the autocomplete set, there are always only 3 options, although in reality there are more.

**To Reproduce**
1. Add more custom labels on the server
2. Go to 'New Card' in Android App
3. Click on 'Change Lebels'
4. Scroll 'Lebels' in 'Change Lebels' autocomplete
5. See error

**Expected behavior**
Should be able to choose from more than 3 labels

**Screenshots**
![image](https://user-images.githubusercontent.com/60046135/80279042-b0dac380-8703-11ea-8821-b77eb0a9dd48.png)
![image](https://user-images.githubusercontent.com/60046135/80279062-c94ade00-8703-11ea-813b-a7ea9d65655f.png)
![image](https://user-images.githubusercontent.com/60046135/80279494-bf76aa00-8706-11ea-9d1b-4923a5634423.png)
![image](https://user-images.githubusercontent.com/60046135/80279102-07480200-8704-11ea-9bc0-d113bada564d.png)

**Smartphone (please complete the following information):**
- Server: Nextcloud 18.0.2
- Nextcloud Deck: 0.8.2
- Nextcloud Deck Android: 0.6.0
- Device: Samsung Galaxy S10e
- Android-Version: Android 10
- App-Store:
  - [ ] F-Droid

Thanks!

**Comment by stefan-niedermann** [comment] 2020-04-25 12:19
Yeah, it's a duplicate of https://github.com/stefan-niedermann/nextcloud-deck/issues/263

You can just start typing then the other tags will occur. We just thought that we display the most often used tags directly when clicking on the input field.

**Closed** 2020-04-25 12:20 UTC
Labels: bug
