### ISSUE TITLE
Fehler beim hochladen eines Anhangs

### ISSUE THREAD

**Issue by droogi** [stefan-niedermann/nextcloud-deck#799] opened 2021-01-12 22:08 UTC
```
App Version: 1.13.5
App Version Code: 1013005
Server App Version: 1.2.3
App Flavor: fdroid

Files App Version Code: 30140190

---

OS Version: 4.14.117-perf-gaf11d57(V12.0.1.0.QCXEUXM)
OS API Level: 29
Device: willow
Manufacturer: Xiaomi
Model (and Product): Redmi Note 8T (willow_eea)

---

java.io.IOException: Failed to create cacheFile
	at it.niedermann.nextcloud.deck.util.AttachmentUtil.getTempCacheFile(AttachmentUtil.java:120)
	at it.niedermann.nextcloud.deck.util.AttachmentUtil.copyContentUriToTempFile(AttachmentUtil.java:83)
	at it.niedermann.nextcloud.deck.ui.card.attachments.CardAttachmentsFragment.uploadNewAttachmentFromUri(CardAttachmentsFragment.java:415)
	at it.niedermann.nextcloud.deck.ui.card.attachments.CardAttachmentsFragment.onActivityResult(CardAttachmentsFragment.java:382)
	at it.niedermann.nextcloud.deck.ui.card.attachments.CardAttachmentsFragment.lambda$null$8$CardAttachmentsFragment(CardAttachmentsFragment.java:314)
	at it.niedermann.nextcloud.deck.ui.card.attachments.-$$Lambda$CardAttachmentsFragment$vFO-xrLYu4LzPCPDOg0MBHBki2E.onChanged(Unknown Source:6)
	at it.niedermann.nextcloud.deck.persistence.sync.adapters.db.util.LiveDataHelper$2.onChanged(LiveDataHelper.java:79)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:149)
	at androidx.lifecycle.LiveData.setValue(LiveData.java:307)
	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
	at it.niedermann.nextcloud.deck.ui.card.attachments.previewdialog.PreviewDialogViewModel.setResult(PreviewDialogViewModel.java:48)
	at it.niedermann.nextcloud.deck.ui.card.attachments.previewdialog.PreviewDialog.lambda$onCreateDialog$3$PreviewDialog(PreviewDialog.java:71)
	at it.niedermann.nextcloud.deck.ui.card.attachments.previewdialog.-$$Lambda$PreviewDialog$eiD5n7fR7lscMEqqZ5GFWF5ZIYo.onClick(Unknown Source:2)
	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:225)
	at android.app.ActivityThread.main(ActivityThread.java:7564)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

```

**Comment by stefan-niedermann** [comment] 2021-01-31 11:06
Are you able to reproduce this issue?
Might the storage of your phone be full?

**Comment by droogi** [comment] 2021-01-31 12:00
Hello, indeed I noticed two days ago that the SD in my mobil is full. I cleaned up a bit and used my second account my.owndrive.com for testing. I could not reproduce the failure. I cannot test with my raspberry nextcloud, it was installed fresh and I can't install deck because of unzip error. 
I ll send a comment when deck is available in my installation. 
Regards, droogi

**Comment by droogi** [comment] 2021-02-12 19:01
i could not reproduce the error anymore. 
But i found a lot of error messages when internetconnection (mobile connection) is not available, this is not noticed by the deck app. i did not notice that there is no connection. i collected 5 different messages, should i send it by message or attach it here anywhere?

**Comment by desperateCoder** [comment] 2021-02-12 19:04
If it states "Offline exception", this is absolutely normal. Of it is something else, feel free to post them here or in a new issue, I don't really care since they need to be reviewed anyways.

Thanks for the research! ❤️

**Comment by desperateCoder** [comment] 2021-02-12 19:04
If it states "Offline exception", this is absolutely normal. Of it is something else, feel free to post them here or in a new issue, I don't really care since they need to be reviewed anyways.

Thanks for the research! ❤️

**Comment by desperateCoder** [comment] 2021-02-16 10:55
Closing because not reproduceable anymore, maybe due to old version. Feel free to reopen or create a new issue, if this occurs again @droogi

**Closed** 2021-02-16 11:09 UTC
Labels: 🐞 bug

**Comment by stefan-niedermann** [comment] 2021-02-16 13:08
> I noticed two days ago that the SD in my mobil is full.

Actually i think that this was the root cause as it makes sense that no temporary fipe can be created when the storage is full.
But yes, closing since not reproducible.
