### ISSUE TITLE
Allow moving cards to different decks/boards

### ISSUE THREAD

**Issue by niccokunzmann** [stefan-niedermann/nextcloud-deck#464] opened 2020-05-07 15:32 UTC
When I want to move a card, I open the menu. There, I expect an entry named "to deck >" which opens a new menu with the decks. When I click on a deck, it opens the menu with the columns of the deck and shows the name of the deck at the top. When I click on a column name of the new deck, I would like to see a bar at the bottom for a long time which says "moved card.to column X of deck Y" and a button to switch to this column of the new deck. "Switch to card".

**Comment by stefan-niedermann** [comment] 2020-05-07 15:34
Duplicate of #453

**Closed by stefan-niedermann** 2020-05-07 15:34 UTC
