### ISSUE TITLE
No widgets on Xiaomi phone

### ISSUE THREAD

**Issue by dtcg** [stefan-niedermann/nextcloud-deck#914] opened 2021-04-02 21:40 UTC
On Xiaomi Redmi phone, nextcloud deck widgets are no longer available (in both system default launcher and 3rd party "nova launcher"). They used to appear and work before. I haven't updated the OS and I constantly update the deck app when released. 

**Versions**
 - Nextcloud: 17.0.0.9
 - Nextcloud Deck: 1.3.1
 - Nextcloud Android: 3.15.1
 - Nextcloud Android Deck: 1.15.7

**Smartphone (please complete the following information):**
- Device: Xiaomi Redmi 7
- Android-Version: 9
- App-Store:
  - [ ] Google Play Store
  - [ ] Google Play Store (Beta channel)
  - [x] F-Droid
  - [ ] Huawei AppGallery

**Stacktrace**

**Comment by stefan-niedermann** [comment] 2021-04-02 22:24
Hi,

first of all: Nextcloud 17 has reached [end of life in 2020-10](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule), so you really really should update.

Regarding the widgets: "Aren't available": This is not enough. You will need to be way more verbose so we can try to help you.

1. Are they still provided as addable widgets and just don't appear when adding them to the homescreen? Or can't you even see them in the widgets overview of android next to other apps widgets?
2. What happened to existing widgets? Stopped working? Vanished completely?
3. Which of the three widget types have you tested?
4. Enable Debug logs in the expert settings, try to add a widget and then press the bug button in the sidebar. Remove sensitive data from the logfile and then upload it somewhere so we can analyze it
5. Check whether widgets of the Notes or News App are working, both are available on F-Droid, too.
6. Please make a screen cast / video record of the try to add a widget and post it here

**Comment by dtcg** [comment] 2021-04-03 17:37
Thanks for the reply. 

I have accounts on different instances, one of them runs nextcloud 20.0.8.1. I think the issue lies between the app and the phone, rather than between the server and the app but thanks for the suggestion.

Regarding the Deck widgets:
1. I can't see them in the widgets overview of android next to other apps widgets
2. The previously existing widgets vanished completely
3. I used to run a single card widget
4. Unfortunately, there is nothing in the clipboard after I press the bug button, and try to copy to clipboard or copy/paste to a note
5. Widgets from both Notes and News apps are available in the widget overview of android and both are working fine
6. I could but there's nothing special: see no.1

**Comment by stefan-niedermann** [comment] 2021-04-03 18:48
That's indeed strange. Can you please uninstall the app and install the version you had before? This way we can fence the cause either to a local environment issue or to the recent version update.

Are you using a custom ROM (which?) or any other special constellation?

Just for the record: I can't reproduce this issue on my Xiaomi Pocophone F1.

NC 17 has nothing to do with the widgets but of course you should upgrade this instance 😉

**Comment by dtcg** [comment] 2021-04-06 09:02
I've had the issue for a while. Do you have an apk from, say December 2020?
No custom ROM. I use Netguard as a firewall with some drastic restrictions so I'm in control of what data leaves my phone.

**Comment by stefan-niedermann** [comment] 2021-04-06 09:25
F-Droid provides the three latest builds put of the box (see "versions" to install one of them). For the complete history you can add the "F-Droid Archive" repository in the settings. Please make sure to uninstall the app before installing an older version.

**Comment by dtcg** [comment] 2021-04-06 15:09
F-Droid Archive: nice trick, thanks.
Unfortunately, no changes with an older version (1.13.0).
I'm starting to wonder if Xiaomi didn't push some OS update in my back...

**Comment by stefan-niedermann** [comment] 2021-04-06 16:24
You're welcome :)

So honestly, since i can't reproduce this issue and no one else reported it yet, i doubt that it is caused by a specific update of the Deck app. Since also old versions fail which previously worked on your device, i guess it is some environment related issue which you are facing here. I'm afraid there's not much we can do on our side to solve it.

I suppose to close this issue therefore until you got new information (maybe reproducing it on another device? or wait for the next Xiaomi update?). Is this fine for you?

**Comment by dtcg** [comment] 2021-04-06 17:16
Yep, thanks for the effort.

**Closed** 2021-04-06 17:23 UTC
