### ISSUE TITLE
Instable handling of connection changes from wifi, celular,...

### ISSUE THREAD

**Issue by MrLoverLoverMMMM** [stefan-niedermann/nextcloud-deck#1169] opened 2021-11-29 11:45 UTC
**Reproduce:**

You can recreate the problem relatively easily.
Install the apps, take the Deck account from the main Nextcloud app.
 on a Samsung Phone (Note10, Note10+, Z Fold 2) with android 11.
Use Deck.
Switch back and forth between different WLANs and Cellular and try to create entries in the app from time to time.
You will see it will load like endless and after 10-20 seconds you receive the excpetion on creation of a new item.

It also happens at connection which are in general unstable, such as wifi in trains, air crafts ==> everywhere on the go.

The problem is currently only present with Deck. Nextcloud Favourites Android, Nextcloud General App Android, Nextcloud Passwords Android, Nextcloud Talk Android do not have this issue.

**Versions**

Nextcloud Server Version: 22.2.3
Nextcloud Deck Server App Version: 1.5.5
Nextcloud App Android Version: 3,18.0
Nextcloud Deck Android App Version: 1.19.4

**Exception on Note10+ Android 11:**

```
App Version: 1.19.4
App Version Code: 1019004
Server App Version: 1.5.5
App Flavor: play

Files App Version Code: 30180090

---

OS Version: 4.14.113-22340613(N975FXXS7FUJ1)
OS API Level: 30
Device: d2s
Manufacturer: samsung
Model (and Product): SM-N975F (d2seea)

---

java.lang.ClassNotFoundException: org.apache.commons.httpclient.ConnectTimeoutException
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:454)
	at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:682)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1703)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1594)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1872)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1412)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:427)
	at com.nextcloud.android.sso.api.AidlNetworkRequest.deserializeObjectV2(AidlNetworkRequest.java:329)
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:167)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:171)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$NextcloudAPI(NextcloudAPI.java:110)
	at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda0.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.httpclient.ConnectTimeoutException
	... 24 more
```

**Solution Suggestion**

- Stabilization for frequent connection changes
- Cache, which can be remembered later at the next connection

**Comment by stefan-niedermann** [comment] 2021-11-30 09:38
> Stabilization for frequent connection changes

Well it's a matter of how to handle a problem → Currently we display them based on the assumption that the user should get notified in case something did not work as expected

> Cache, which can be remembered later at the next connection

We already do that, as you already noticed yourself, the items should be synced eventually the next time one synchronizes with an available network.

But i agree, that those kind of network related errors are a bit annoying, so my proposal is to handle them like in the Notes app, which basically means:
1. If a synchronization was triggered by the app (network change, background sync, synchronization on startup) we should simply hide network related errors (like `ConnectTimeoutException`)
2. If a synchronization was triggered by the user (by manually pulling down to refresh), we should continue to display those errors, to make the accessible and visible in case a user wants to find problem causes

@MrLoverLoverMMMM what do you think about this solution?

**Comment by MrLoverLoverMMMM** [comment] 2021-11-30 12:13
Hi!
Well important for is would be, if I can just modificate the list offline in the apps-cache and as soon as the connection reapears it tries to syncronize it back into the server-app.
You could try to merge and if the list have changed since the last offline version you could ask to overwrite or keep server version or so when the app gets again a connection.
The reason is I need to modificate the contents of lists on the go and if that does not work the app is basically useless for on-the-go usage.
best regards

Patrick

**Comment by stefan-niedermann** [comment] 2021-11-30 12:29
> if I can just modificate the list offline in the apps-cache and as soon as the connection reapears it tries to syncronize it back into the server-app.

That's what we are doing<sup>[1](https://github.com/stefan-niedermann/nextcloud-deck/blob/master/app/src/main/java/it/niedermann/nextcloud/deck/ui/MainActivity.java#L976)</sup>. Due to Android limitations we can only do that while the app is open. Otherwise you will have to wait for the next background synchronization (depending on your settings), which obviously will take longer then.

> You could try to merge and if the list have changed since the last offline version you could ask to overwrite or keep server version or so when the app gets again a connection.

Conflict handling is a very different topic, please don't mix it with offline capabilities :wink: 

> The reason is I need to modificate the contents of lists on the go and if that does not work the app is basically useless for on-the-go usage.

The app *is* offline capable. It stores changes always on the device first and then synchronizes it, as soon as a synchronization is possible again. If you are experiencing data loss or it does not work at all, then this would clearly be a bug. Though then we will need a way more detailed explanation including steps to reproduce. (For example: Go to airplane mode, add a new card, disable airplane mode, pull to refresh, card is still not at the server, ...).

**Comment by MrLoverLoverMMMM** [comment] 2021-11-30 12:34
Well..
Currently I have no possibility at all to change the list or delete something or add something new when the connection is unstable as this error I posted initially is always interupting.
After I close the error the list stays the same and does not modify. Also not if I keep the app open and wait till the connection to reconnect.
The only way to get my change currently in the app is to look for a very stable connection and do all the modifications again.
And thats very cumbersome if I have no possibility to edit offline because of this endless reoccuring error.

**Comment by MrLoverLoverMMMM** [comment] 2021-11-30 12:34
+ Merging was just an idea for future ;)

**Comment by stefan-niedermann** [comment] 2021-11-30 12:41
> Currently I have no possibility at all to change the list or delete something or add something new when the connection is unstable as this error I posted initially is always interupting.

So if i got you right, you try to create a new card in an unreliable network. After saving, you get the message (currently intended) and after closing the error message the card is "lost"? You can not see it on your Android device?

**Comment by MrLoverLoverMMMM** [comment] 2021-11-30 12:50
Yes exactly.
This happens if I add a new card, modificate a card and try to save or just wanna delete a card.

**Comment by desperateCoder** [comment] 2021-11-30 13:09
@stefan-niedermann an offline exception isn't a problem here, it would behave just as @MrLoverLoverMMMM wants it to. The problem is the unreliable connection, leading to classnotfound. If you two allow, i'll handle that in a central manner and throw an offline exception so it behaves as intended. It will be a little of an odd implementation, but I think it's worth doing so in favor of not including all the Apache libs into deck.

**Comment by MrLoverLoverMMMM** [comment] 2021-11-30 15:47
> @stefan-niedermann an offline exception isn't a problem here, it would behave just as @MrLoverLoverMMMM wants it to. The problem is the unreliable connection, leading to classnotfound. If you two allow, i'll handle that in a central manner and throw an offline exception so it behaves as intended. It will be a little of an odd implementation, but I think it's worth doing so in favor of not including all the Apache libs into deck.

Makes sense ;)
Thank you

**Comment by MrLoverLoverMMMM** [comment] 2021-12-27 18:35
Is there a roadmap when it will be fixed?
I found another problem on note 10 + only.
On Note 10 + I always receive:

```
Full Crash:

App Version: 1.19.4
App Version Code: 1019004
App Flavor: play

Files App Version Code: 30180190

---

OS Version: 4.14.113-22340613(N975FXXS7FUJ1)
OS API Level: 30
Device: d2s
Manufacturer: samsung
Model (and Product): SM-N975F (d2seea)

---

java.lang.IllegalStateException: Fragment NewCardDialog{8c650bd} (1a544995-504c-4b88-95e1-fe16911e7e63) not attached to a context.
	at androidx.fragment.app.Fragment.requireContext(Fragment.java:900)
	at it.niedermann.nextcloud.deck.ui.card.NewCardDialog$2.lambda$onResponse$0$NewCardDialog$2(NewCardDialog.java:170)
	at it.niedermann.nextcloud.deck.ui.card.NewCardDialog$2$$ExternalSyntheticLambda1.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8633)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

```

**Comment by piscocgn** [comment] 2022-01-05 11:04
Hi, I came along this issue while searching because I discovered a similar issue if I'm in cellular only. It does not happen if I'm in WiFi or cellular via VPN to my nextcloud instance at home.
If I create the item I get this message, but the item is created locally, but not remote. Sync is not working, same error message. If I'm back to Wifi I  can get it synced both (new remote items and local only items). For other nextcloud related applications I do no not observe similar issues.

```
App Version: 1.19.4
App Version Code: 1019004
Server App Version: 1.5.5
App Flavor: play

Files App Version Code: 30180190

---

OS Version: 4.14.243-g84269d3777f9-ab7793573(7888514)
OS API Level: 31
Device: sunfish
Manufacturer: Google
Model (and Product): Pixel 4a (sunfish)

---

com.nextcloud.android.sso.exceptions.UnknownErrorException: failed to connect to myhome.example.com/2222:A:B:C:D (port 443) from /2020:A:B:C:D (port 42803) after 60000ms: isConnected failed: ECONNREFUSED (Connection refused)
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:171)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$NextcloudAPI(NextcloudAPI.java:110)
	at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda0.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
```

**Comment by stefan-niedermann** [comment] 2022-01-05 11:30
@piscocgn your issue should be covered by [the proposal of @desperateCoder](https://github.com/stefan-niedermann/nextcloud-deck/issues/1169#issuecomment-982621343) as far as i can see, thanks for also bringing in your use case 🙂

**Closed** 2022-01-17 11:46 UTC

**Comment by desperateCoder** [comment] 2022-01-17 11:50
@piscocgn @MrLoverLoverMMMM 

We now handle these exceptions properly and display a message stating whats happened instead of crashing. You should face the expected behavior after updating to version `1.20.1`.

In case you face further problems, please open a new issue. We hope you guys like it :blush:
